Repository Alfresco/alfresco-community-repo, pull requests merged in 2020-12, with the labels that each got.

#189 ACS-986 : Azure Connector 1.3 Alpha Release
  pom.xml
Labels: PR: unreviewed

#190 ACS-976 Metadata extraction NPE thrown in multi-node cluster using ATS
  remote-api/src/test/java/org/alfresco/rest/api/tests/SharedLinkApiTest.java
  repository/src/main/java/org/alfresco/repo/content/metadata/AsynchronousExtractor.java
  repository/src/test/java/org/alfresco/repo/action/executer/AsynchronousExtractorTest.java
Labels: PR: partially-approved

#187 ACS-960 Disable very frequent intermittent test failures
  core/src/test/java/org/alfresco/util/testing/category/FrequentlyFailingTests.java
  core/src/test/java/org/alfresco/util/testing/category/IntermittentlyFailingTests.java
  packaging/tests/tas-cmis/src/test/java/org/alfresco/cmis/DeleteTreeTests.java
  packaging/tests/tas-cmis/src/test/java/org/alfresco/cmis/GetChildrenTests.java
  packaging/tests/tas-integration/src/test/java/org/alfresco/tas/integration/IntegrationFullTests.java
  packaging/tests/tas-integration/src/test/java/org/alfresco/tas/integration/IntegrationFullTests1.java
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/comments/AddCommentsTests.java
  remote-api/src/test/java/org/alfresco/repo/web/scripts/servlet/RemoteAuthenticatorFactoryAdminConsoleAccessTest.java
  remote-api/src/test/java/org/alfresco/repo/webdav/WebDAVMethodTest.java
  remote-api/src/test/java/org/alfresco/rest/DeletedNodesTest.java
  remote-api/src/test/java/org/alfresco/rest/api/tests/AbstractEnterpriseOpenCMIS11TCKTest.java
  remote-api/src/test/java/org/alfresco/rest/api/tests/SharedLinkApiTest.java
  repository/src/test/java/org/alfresco/encryption/EncryptionTests.java
  repository/src/test/java/org/alfresco/opencmis/CMISTest.java
  repository/src/test/java/org/alfresco/opencmis/OpenCmisLocalTest.java
  repository/src/test/java/org/alfresco/repo/event2/ChildAssociationRepoEventIT.java
  repository/src/test/java/org/alfresco/repo/transfer/NodeCrawlerTest.java
Labels: PR: unreviewed

#194 revert of webscripts to version 8.12
  pom.xml
Labels: PR: partially-approved

#193 Fix/search 2602 missed information search page
  .travis.yml
  repository/src/main/java/org/alfresco/repo/search/impl/solr/SolrChildApplicationContextFactory.java
  repository/src/test/java/org/alfresco/repo/search/SearchTestSuite.java
  repository/src/test/java/org/alfresco/repo/search/impl/solr/SolrChildApplicationContextFactoryTest.java
Labels: PR: unreviewed

#198 Added check for properties of jsonObject scheduler.start.
  remote-api/src/main/java/org/alfresco/repo/web/scripts/replication/AbstractReplicationWebscript.java
Labels: PR: reviewed-approved

#199 SEARCH-2589: Check Solr6 subsystem doesn't include the ShardRegistry …
  repository/src/test/java/org/alfresco/repo/search/SearchTestSuite.java
  repository/src/test/java/org/alfresco/repo/search/impl/solr/SolrSubsystemTest.java
Labels: PR: unreviewed

#202 APPS-688: Fixed the issue by using System user instead of the admin user
  remote-api/src/main/resources/alfresco/templates/webscripts/org/alfresco/repository/archive/archivednode.put.desc.xml
  remote-api/src/main/resources/alfresco/templates/webscripts/org/alfresco/repository/archive/archivednodes.delete.desc.xml
  remote-api/src/main/resources/alfresco/templates/webscripts/org/alfresco/repository/archive/archivednodes.get.desc.xml
Labels: PR: partially-approved

#188 MNT-22040 Copying nodes that contain sys:pendingFixAcl aspect
  repository/src/main/java/org/alfresco/repo/domain/permissions/ADMAccessControlListDAO.java
  repository/src/main/java/org/alfresco/repo/domain/permissions/AccessControlListDAO.java
  repository/src/main/java/org/alfresco/repo/domain/permissions/FixedAclUpdater.java
  repository/src/test/java/org/alfresco/repo/domain/permissions/FixedAclUpdaterTest.java
Labels: PR: unreviewed

#208 Bugfix/acs 1041 fix test failure
  repository/src/test/java/org/alfresco/repo/event2/ChildAssociationRepoEventIT.java
Labels: PR: reviewed-approved

#209 Fix/mnt 22040 fixed acl updater copy fix 62 n
  repository/src/main/java/org/alfresco/repo/domain/permissions/ADMAccessControlListDAO.java
  repository/src/main/java/org/alfresco/repo/domain/permissions/AccessControlListDAO.java
  repository/src/main/java/org/alfresco/repo/domain/permissions/FixedAclUpdater.java
  repository/src/test/java/org/alfresco/repo/domain/permissions/FixedAclUpdaterTest.java
Labels: PR: unreviewed

#212 ACS-1033 : Spring upgrade on ACS 7.0 - 5.2.12.RELEASE
  pom.xml
Labels: PR: reviewed-approved

#211 Added new method to convert system type to ordinal
  repository/src/main/java/org/alfresco/repo/domain/node/NodePropertyValue.java
Labels: PR: reviewed-approved

#213 ACS-1033 : Spring upgrade to 5.3.2
  core/src/main/java/org/alfresco/util/transaction/SpringAwareUserTransaction.java
  pom.xml
  remote-api/src/test/java/org/alfresco/repo/web/scripts/quickshare/QuickShareRestApiTest.java
  repository/src/test/java/org/alfresco/repo/transaction/TransactionServiceImplTest.java
Labels: PR: unreviewed
