Repository Alfresco/alfresco-community-repo, pull requests merged in 2020-11, with the labels that each got.

#97 Changes to poms to support compatibility with JDK9+ module system
  data-model/pom.xml
  pom.xml
  repository/pom.xml
Labels: PR: reviewed-approved

#122 LOC-264 - fixes to punctuation in JAPANESE and SIMP CHINESE
  remote-api/src/main/resources/alfresco/messages/custommodel-restapi-messages_ja.properties
  remote-api/src/main/resources/alfresco/templates/webscripts/org/alfresco/repository/admin/support-tools/admin-nodebrowser.get_zh_CN.properties
  repository/src/main/resources/alfresco/messages/activiti-engine-messages_ja.properties
  repository/src/main/resources/alfresco/messages/activiti-engine-messages_zh_CN.properties
  repository/src/main/resources/alfresco/messages/bootstrap-content-template-examples_ja.properties
  repository/src/main/resources/alfresco/messages/bootstrap-content-template-examples_zh_CN.properties
  repository/src/main/resources/alfresco/messages/bootstrap-messages_zh_CN.properties
  repository/src/main/resources/alfresco/messages/content-model_zh_CN.properties
  repository/src/main/resources/alfresco/messages/custommodel-service_ja.properties
  repository/src/main/resources/alfresco/messages/custommodel-service_zh_CN.properties
  repository/src/main/resources/alfresco/messages/repoadmin-service_zh_CN.properties
  repository/src/main/resources/alfresco/messages/system-messages_ja.properties
  repository/src/main/resources/alfresco/messages/transfer-service_zh_CN.properties
Labels: PR: reviewed-approved

#128 MNT-21967 - ClassCastException when using CMIS query with SCORE() function
  repository/src/main/java/org/alfresco/opencmis/search/CMISResultSetRow.java
Labels: PR: reviewed-approved

#134 MNT-21967 - ClassCastException when using CMIS query with SCORE() function
  repository/src/main/java/org/alfresco/opencmis/search/CMISResultSetRow.java
Labels: PR: unreviewed

#136 MNT-21967 - ClassCastException when using CMIS query with SCORE() function
  repository/src/main/java/org/alfresco/opencmis/search/CMISResultSetRow.java
Labels: PR: unreviewed

#135 OPSEXP-492: Add ANSIBLE deployment method
  repository/src/main/java/org/alfresco/repo/deployment/DeploymentMethod.java
  repository/src/main/resources/alfresco/repository.properties
Labels: PR: partially-approved

#137 MNT-21800 - CMIS Web Service Check Out returns error
  repository/src/main/java/org/alfresco/opencmis/TransactionAwareHolder.java
Labels: PR: unreviewed

#113 REPO-5209: Prevent creation of node updated event when property added…
  README.md
  repository/src/main/java/org/alfresco/repo/event2/EventConsolidator.java
  repository/src/test/java/org/alfresco/repo/event2/UpdateRepoEventIT.java
Labels: PR: partially-approved

#141 [MNT-22015] REST api does not update the primary path on new version upload
  remote-api/src/main/java/org/alfresco/rest/api/impl/NodesImpl.java
  remote-api/src/test/java/org/alfresco/rest/api/tests/NodeApiTest.java
Labels: PR: reviewed-approved

#139 SEARCH-2532: Add Permission Update events to be generated from alfres…
  repository/src/main/java/org/alfresco/repo/event2/EventConsolidator.java
  repository/src/main/java/org/alfresco/repo/event2/EventGenerator.java
  repository/src/main/java/org/alfresco/repo/event2/EventJSONSchema.java
  repository/src/main/java/org/alfresco/repo/event2/EventType.java
  repository/src/main/java/org/alfresco/repo/event2/NodeResourceHelper.java
  repository/src/main/resources/alfresco/events2-context.xml
Labels: PR: reviewed-approved

#116 REPO-5208 Metadata extract: overwritePolicy, enableStringTagging and carryAspectProperties tests
  .gitignore
  repository/src/main/java/org/alfresco/repo/search/impl/AbstractCategoryServiceImpl.java
  repository/src/test/java/org/alfresco/repo/action/executer/AsynchronousExtractorTest.java
  repository/src/test/resources/quick/quick.carryAspectFalse_metadata.json
  repository/src/test/resources/quick/quick.carryAspectTrue_metadata.json
  repository/src/test/resources/quick/quick.cautious_policy_metadata.json
  repository/src/test/resources/quick/quick.eager_policy_metadata.json
  repository/src/test/resources/quick/quick.pragmatic_policy_metadata.json
  repository/src/test/resources/quick/quick.prudent_policy_metadata.json
  repository/src/test/resources/quick/quick.tagging_metadata.json
  repository/src/test/resources/quick/quick.tagging_metadata_enable_false.json
Labels: PR: reviewed-approved

#145 [MNT-22015] REST api does not update the primary path on new version upload
  remote-api/src/main/java/org/alfresco/rest/api/impl/NodesImpl.java
  remote-api/src/test/java/org/alfresco/rest/api/tests/NodeApiTest.java
Labels: PR: reviewed-approved

#148 REPO-5190 Remove Metadata Extractors that are been offloaded in 7.0.0
  .travis.yml
  remote-api/src/test/java/org/alfresco/rest/api/tests/NodeApiTest.java
  remote-api/src/test/java/org/alfresco/rest/api/tests/RenditionsTest.java
  remote-api/src/test/java/org/alfresco/rest/api/tests/SharedLinkApiTest.java
  remote-api/src/test/java/org/alfresco/rest/api/tests/TestCMIS.java
  remote-api/src/test/resources/log4j.properties
  repository/src/main/java/org/alfresco/repo/action/ActionServiceImpl.java
  repository/src/main/java/org/alfresco/repo/action/executer/ActionExecuter.java
  repository/src/main/java/org/alfresco/repo/action/executer/ContentMetadataExtracter.java
  repository/src/main/java/org/alfresco/repo/content/metadata/AbstractMappingMetadataExtracter.java
  repository/src/main/java/org/alfresco/repo/content/metadata/AsynchronousExtractor.java
  repository/src/main/java/org/alfresco/repo/content/metadata/DWGMetadataExtracter.java
  repository/src/main/java/org/alfresco/repo/content/metadata/HtmlMetadataExtracter.java
  repository/src/main/java/org/alfresco/repo/content/metadata/JodConverterMetadataExtracter.java
  repository/src/main/java/org/alfresco/repo/content/metadata/JodConverterMetadataExtracterWorker.java
  repository/src/main/java/org/alfresco/repo/content/metadata/MP3MetadataExtracter.java
  repository/src/main/java/org/alfresco/repo/content/metadata/MailMetadataExtracter.java
  repository/src/main/java/org/alfresco/repo/content/metadata/OfficeMetadataExtracter.java
  repository/src/main/java/org/alfresco/repo/content/metadata/OpenDocumentMetadataExtracter.java
  repository/src/main/java/org/alfresco/repo/content/metadata/OpenOfficeMetadataWorker.java
  repository/src/main/java/org/alfresco/repo/content/metadata/PdfBoxMetadataExtracter.java
  repository/src/main/java/org/alfresco/repo/content/metadata/PoiMetadataExtracter.java
  repository/src/main/java/org/alfresco/repo/content/metadata/RFC822MetadataExtracter.java
  repository/src/main/java/org/alfresco/repo/content/metadata/TikaAudioMetadataExtracter.java
  repository/src/main/java/org/alfresco/repo/content/metadata/TikaAutoMetadataExtracter.java
  repository/src/main/java/org/alfresco/repo/content/metadata/TikaPoweredMetadataExtracter.java
  repository/src/main/java/org/alfresco/repo/content/metadata/TikaSpringConfiguredMetadataExtracter.java
  repository/src/main/java/org/alfresco/repo/content/transform/LocalTransformServiceRegistry.java
  repository/src/main/resources/alfresco/content-services-context.xml
  repository/src/main/resources/alfresco/subsystems/OOoJodconverter/default/jodconverter-context.xml
  repository/src/test/java/org/alfresco/MiscContextTestSuite.java
  repository/src/test/java/org/alfresco/filesys/repo/ContentDiskDriverTest.java
  repository/src/test/java/org/alfresco/repo/action/ActionServiceImpl2Test.java
  repository/src/test/java/org/alfresco/repo/action/executer/ContentMetadataEmbedderTest.java
  repository/src/test/java/org/alfresco/repo/action/executer/ContentMetadataExtracterTagMappingTest.java
  repository/src/test/java/org/alfresco/repo/action/executer/ContentMetadataExtracterTest.java
  repository/src/test/java/org/alfresco/repo/content/metadata/ConcurrencyOfficeMetadataExtracterTest.java
  repository/src/test/java/org/alfresco/repo/content/metadata/ConcurrencyPdfBoxMetadataExtracterTest.java
  repository/src/test/java/org/alfresco/repo/content/metadata/DWGMetadataExtracterTest.java
  repository/src/test/java/org/alfresco/repo/content/metadata/HtmlMetadataExtracterTest.java
  repository/src/test/java/org/alfresco/repo/content/metadata/JodMetadataExtractorOOoTest.java
  repository/src/test/java/org/alfresco/repo/content/metadata/MP3MetadataExtracterTest.java
  repository/src/test/java/org/alfresco/repo/content/metadata/MailMetadataExtracterTest.java
  repository/src/test/java/org/alfresco/repo/content/metadata/OfficeMetadataExtracterTest.java
  repository/src/test/java/org/alfresco/repo/content/metadata/OpenDocumentMetadataExtracterTest.java
  repository/src/test/java/org/alfresco/repo/content/metadata/PdfBoxMetadataExtracterTest.java
  repository/src/test/java/org/alfresco/repo/content/metadata/PoiMetadataExtracterTest.java
  repository/src/test/java/org/alfresco/repo/content/metadata/RFC822MetadataExtracterTest.java
  repository/src/test/java/org/alfresco/repo/content/metadata/TikaAudioMetadataExtracterTest.java
  repository/src/test/java/org/alfresco/repo/content/metadata/TikaAutoMetadataExtracterTest.java
  repository/src/test/java/org/alfresco/repo/rendition2/AbstractRenditionIntegrationTest.java
  repository/src/test/java/org/alfresco/repo/rendition2/AbstractRenditionTest.java
  repository/src/test/java/org/alfresco/repo/rendition2/LegacyRenditionTest.java
  repository/src/test/java/org/alfresco/repo/rendition2/NoneRenditionTest.java
Labels: PR: reviewed-approved

#120 [ACS-777] Email notification for digital workspace
  packaging/war/src/main/webapp/images/logo/workspace.png
  remote-api/src/main/java/org/alfresco/rest/api/SiteMembershipRequests.java
  remote-api/src/main/java/org/alfresco/rest/api/impl/SiteMembershipRequestsImpl.java
  remote-api/src/main/java/org/alfresco/rest/api/model/SiteMembershipRequest.java
  remote-api/src/main/java/org/alfresco/rest/api/people/PersonSiteMembershipRequestsRelation.java
  repository/src/main/java/org/alfresco/repo/invitation/InvitationImpl.java
  repository/src/main/java/org/alfresco/repo/invitation/InvitationServiceImpl.java
  repository/src/main/java/org/alfresco/repo/invitation/ModeratedInvitationImpl.java
  repository/src/main/java/org/alfresco/repo/invitation/WorkflowModelModeratedInvitation.java
  repository/src/main/java/org/alfresco/repo/invitation/activiti/SendModeratedInviteDelegate.java
  repository/src/main/java/org/alfresco/repo/invitation/site/InviteModeratedSender.java
  repository/src/main/java/org/alfresco/repo/invitation/site/InviteSender.java
  repository/src/main/java/org/alfresco/service/cmr/invitation/Invitation.java
  repository/src/main/java/org/alfresco/service/cmr/invitation/InvitationService.java
  repository/src/main/java/org/alfresco/util/UrlUtil.java
  repository/src/main/resources/alfresco/application-context-core.xml
  repository/src/main/resources/alfresco/application-context-highlevel.xml
  repository/src/main/resources/alfresco/client/config/repo-clients-apps.properties
  repository/src/main/resources/alfresco/invitation-service-context.xml
  repository/src/main/resources/alfresco/messages/templates-messages.properties
  repository/src/main/resources/alfresco/templates/workspace/invite-email-moderated.html.ftl
  repository/src/main/resources/alfresco/workflow/invitation-moderated-workflow-model.xml
  repository/src/test/java/org/alfresco/repo/invitation/AbstractInvitationServiceImplTest.java
  repository/src/test/java/org/alfresco/repo/invitation/site/InviteModeratedSenderTest.java
Labels: PR: partially-approved

#149 MNT-22036 : REST API always applies versioning
  remote-api/src/main/java/org/alfresco/rest/api/impl/NodesImpl.java
  remote-api/src/test/java/org/alfresco/rest/api/tests/NodeApiTest.java
  remote-api/src/test/java/org/alfresco/rest/api/tests/util/MultiPartBuilder.java
Labels: PR: partially-approved

#155 OPSEXP-492: Added ANSIBLE as an option for deployment method
  repository/src/main/java/org/alfresco/repo/deployment/DeploymentMethod.java
  repository/src/main/resources/alfresco/repository.properties
Labels: PR: partially-approved

#156 MNT-22036 : REST API always applies versioning
  remote-api/src/main/java/org/alfresco/rest/api/impl/NodesImpl.java
  remote-api/src/test/java/org/alfresco/rest/api/tests/NodeApiTest.java
  remote-api/src/test/java/org/alfresco/rest/api/tests/util/MultiPartBuilder.java
Labels: PR: unreviewed

#96 [ACS-727] run tas-cmis tests on Atom and Webservices bindings
  .travis.yml
  packaging/tests/tas-cmis/pom.xml
  packaging/tests/tas-cmis/src/test/java/org/alfresco/cmis/AclTests.java
  packaging/tests/tas-cmis/src/test/java/org/alfresco/cmis/AddObjectToFolderTests.java
  packaging/tests/tas-cmis/src/test/java/org/alfresco/cmis/AllowableActionTests.java
  packaging/tests/tas-cmis/src/test/java/org/alfresco/cmis/AppendContentStreamTests.java
  packaging/tests/tas-cmis/src/test/java/org/alfresco/cmis/CancelCheckOutTests.java
  packaging/tests/tas-cmis/src/test/java/org/alfresco/cmis/CheckInTests.java
  packaging/tests/tas-cmis/src/test/java/org/alfresco/cmis/CheckOutTests.java
  packaging/tests/tas-cmis/src/test/java/org/alfresco/cmis/CopyTests.java
  packaging/tests/tas-cmis/src/test/java/org/alfresco/cmis/CreateDocumentFromSourceTests.java
  packaging/tests/tas-cmis/src/test/java/org/alfresco/cmis/CreateDocumentTests.java
  packaging/tests/tas-cmis/src/test/java/org/alfresco/cmis/CreateFolderTests.java
  packaging/tests/tas-cmis/src/test/java/org/alfresco/cmis/DeleteAllVersionsTests.java
  packaging/tests/tas-cmis/src/test/java/org/alfresco/cmis/DeleteContentStreamTests.java
  packaging/tests/tas-cmis/src/test/java/org/alfresco/cmis/DeleteTests.java
  packaging/tests/tas-cmis/src/test/java/org/alfresco/cmis/DeleteTreeTests.java
  packaging/tests/tas-cmis/src/test/java/org/alfresco/cmis/GetAllVersionsTests.java
  packaging/tests/tas-cmis/src/test/java/org/alfresco/cmis/GetCheckedOutDocumentsTests.java
  packaging/tests/tas-cmis/src/test/java/org/alfresco/cmis/GetChildrenTests.java
  packaging/tests/tas-cmis/src/test/java/org/alfresco/cmis/GetContentStreamTests.java
  packaging/tests/tas-cmis/src/test/java/org/alfresco/cmis/GetDescendantsTests.java
  packaging/tests/tas-cmis/src/test/java/org/alfresco/cmis/GetExtensionTests.java
  packaging/tests/tas-cmis/src/test/java/org/alfresco/cmis/GetFolderParentTests.java
  packaging/tests/tas-cmis/src/test/java/org/alfresco/cmis/GetFolderTreeTests.java
  packaging/tests/tas-cmis/src/test/java/org/alfresco/cmis/GetObjectOfLatestVersionTests.java
  packaging/tests/tas-cmis/src/test/java/org/alfresco/cmis/GetObjectTypeTests.java
  packaging/tests/tas-cmis/src/test/java/org/alfresco/cmis/GetParentsTests.java
  packaging/tests/tas-cmis/src/test/java/org/alfresco/cmis/GetPropertiesTests.java
  packaging/tests/tas-cmis/src/test/java/org/alfresco/cmis/GetTypeChildrenTests.java
  packaging/tests/tas-cmis/src/test/java/org/alfresco/cmis/GetTypeDefinitionTests.java
  packaging/tests/tas-cmis/src/test/java/org/alfresco/cmis/GetTypeDescendantsTests.java
  packaging/tests/tas-cmis/src/test/java/org/alfresco/cmis/IsLatestMajorVersionTests.java
  packaging/tests/tas-cmis/src/test/java/org/alfresco/cmis/IsPrivateWorkingCopyTests.java
  packaging/tests/tas-cmis/src/test/java/org/alfresco/cmis/MoveTests.java
  packaging/tests/tas-cmis/src/test/java/org/alfresco/cmis/RelationshipTests.java
  packaging/tests/tas-cmis/src/test/java/org/alfresco/cmis/RemoveObjectFromFolderTests.java
  packaging/tests/tas-cmis/src/test/java/org/alfresco/cmis/RenameTests.java
  packaging/tests/tas-cmis/src/test/java/org/alfresco/cmis/RenditionTests.java
  packaging/tests/tas-cmis/src/test/java/org/alfresco/cmis/RepositoryInfoTests.java
  packaging/tests/tas-cmis/src/test/java/org/alfresco/cmis/SecondaryTypesTests.java
  packaging/tests/tas-cmis/src/test/java/org/alfresco/cmis/SetContentTests.java
  packaging/tests/tas-cmis/src/test/java/org/alfresco/cmis/UpdatePropertiesTests.java
  packaging/tests/tas-cmis/src/test/resources/cmis-suite.xml
  packaging/tests/tas-cmis/src/test/resources/default.properties
  pom.xml
Labels: PR: reviewed-approved

#158 [SEARCH-2533]
  pom.xml
  repository/src/main/java/org/alfresco/repo/event2/ChildAssociationEventConsolidator.java
  repository/src/main/java/org/alfresco/repo/event2/EventConsolidator.java
  repository/src/main/java/org/alfresco/repo/event2/EventGenerator.java
  repository/src/main/java/org/alfresco/repo/event2/EventJSONSchema.java
  repository/src/main/java/org/alfresco/repo/event2/EventType.java
  repository/src/main/java/org/alfresco/repo/event2/PeerAssociationEventConsolidator.java
  repository/src/test/java/org/alfresco/repo/event2/AbstractContextAwareRepoEvent.java
  repository/src/test/java/org/alfresco/repo/event2/ChildAssociationRepoEventIT.java
  repository/src/test/java/org/alfresco/repo/event2/CreateRepoEventIT.java
  repository/src/test/java/org/alfresco/repo/event2/DeleteRepoEventIT.java
  repository/src/test/java/org/alfresco/repo/event2/EventJSONSchemaUnitTest.java
  repository/src/test/java/org/alfresco/repo/event2/PeerAssociationRepoEventIT.java
  repository/src/test/java/org/alfresco/repo/event2/UpdateRepoEventIT.java
Labels: PR: unreviewed

#157 MNT-22036 : REST API always applies versioning
  remote-api/src/main/java/org/alfresco/rest/api/impl/NodesImpl.java
  remote-api/src/test/java/org/alfresco/rest/api/tests/NodeApiTest.java
  remote-api/src/test/java/org/alfresco/rest/api/tests/util/MultiPartBuilder.java
Labels: PR: unreviewed

#37 MNT-20250: Model updates not working for deployment in cluster
  repository/src/main/java/org/alfresco/repo/cache/DefaultSimpleCache.java
  repository/src/main/resources/alfresco/tx-cache-context.xml
  repository/src/test/java/org/alfresco/repo/cache/DefaultSimpleCacheTest.java
Labels: PR: reviewed-approved

#163 ACS-778: Fixed IDS authentication component.
  repository/src/main/java/org/alfresco/repo/security/authentication/identityservice/IdentityServiceAuthenticationComponent.java
  repository/src/test/java/org/alfresco/AppContext05TestSuite.java
  repository/src/test/java/org/alfresco/repo/security/authentication/identityservice/IdentityServiceAuthenticationComponentTest.java
Labels: PR: reviewed-approved

#168 MNT-22061: REST api does not update the primary path on new version upload
  remote-api/src/main/java/org/alfresco/rest/api/impl/NodesImpl.java
  remote-api/src/test/java/org/alfresco/rest/api/tests/NodeApiTest.java
Labels: PR: reviewed-approved

#169 REPO-5219 Allow AGS AMP to specify metadata extract mapping (REPO)
  l10n.properties
  repository/src/main/java/org/alfresco/repo/content/metadata/AsynchronousExtractor.java
  repository/src/main/java/org/alfresco/repo/content/metadata/MetadataExtractorPropertyMappingOverride.java
  repository/src/main/java/org/alfresco/repo/content/metadata/RFC822MetadataExtracter.java
  repository/src/main/resources/alfresco/content-services-context.xml
  repository/src/main/resources/alfresco/metadata/DWGMetadataExtracter.properties
  repository/src/main/resources/alfresco/metadata/HtmlMetadataExtracter.properties
  repository/src/main/resources/alfresco/metadata/JodConverterMetadataExtracter.properties
  repository/src/main/resources/alfresco/metadata/MP3MetadataExtracter.properties
  repository/src/main/resources/alfresco/metadata/MailMetadataExtracter.properties
  repository/src/main/resources/alfresco/metadata/OfficeMetadataExtracter.properties
  repository/src/main/resources/alfresco/metadata/OpenDocumentMetadataExtracter.properties
  repository/src/main/resources/alfresco/metadata/PdfBoxMetadataExtracter.properties
  repository/src/main/resources/alfresco/metadata/PoiMetadataExtracter.properties
  repository/src/main/resources/alfresco/metadata/TikaAudioMetadataExtracter.properties
  repository/src/main/resources/alfresco/metadata/TikaAutoMetadataExtracter.properties
  repository/src/main/resources/alfresco/metadata/TikaSpringConfiguredMetadataExtracter.properties
  repository/src/test/java/org/alfresco/MiscContextTestSuite.java
  repository/src/test/java/org/alfresco/repo/content/metadata/RFC822MetadataExtracterTest.java
Labels: PR: reviewed-approved

#165 Feature/repo 5398 special support for type inside the query
  repository/src/main/java/org/alfresco/repo/search/impl/querymodel/impl/db/DBQueryBuilderPredicatePartCommand.java
  repository/src/main/java/org/alfresco/repo/search/impl/querymodel/impl/db/DBQueryEngine.java
  repository/src/main/java/org/alfresco/repo/search/impl/querymodel/impl/db/PropertySupport.java
Labels: PR: reviewed-approved

#170 MNT-22055 : Metadata extraction fails for certain documents
  pom.xml
  repository/src/main/java/org/alfresco/repo/content/metadata/TikaAutoMetadataExtracter.java
Labels: PR: unreviewed

#164 ACS-896 Fix community PR builds
  .travis.settings.xml
  .travis.yml
  scripts/travis/init.sh
Labels: PR: partially-approved

#152 Feature/repo 5395 backport new query acc optimisations
  remote-api/src/main/java/org/alfresco/rest/api/search/SearchApiWebscript.java
  repository/src/main/java/org/alfresco/repo/search/impl/querymodel/impl/db/DBQueryEngine.java
  repository/src/main/java/org/alfresco/repo/search/impl/querymodel/impl/db/DBStats.java
  repository/src/main/java/org/alfresco/repo/search/impl/querymodel/impl/db/SingleTaskRestartableWatch.java
  repository/src/main/resources/alfresco/ibatis/org.alfresco.repo.domain.dialect.Dialect/metadata-query-SqlMap.xml
  repository/src/main/resources/alfresco/subsystems/Search/common-search-context.xml
  repository/src/test/java/org/alfresco/repo/quickshare/QuickShareServiceIntegrationTest.java
  repository/src/test/java/org/alfresco/repo/search/impl/querymodel/impl/db/DBQueryEngineTest.java
  repository/src/test/java/org/alfresco/repo/search/impl/querymodel/impl/db/NodePermissionAssessorTest.java
Labels: PR: reviewed-approved

#175 ACS-894: Log WARN message on startup if ActiveMQ is not available
  packaging/war/src/main/resources/log4j.properties
Labels: PR: unreviewed

#176 ACS-938 metadata is not added when using Transform Service
  repository/src/main/java/org/alfresco/repo/content/metadata/AsynchronousExtractor.java
  repository/src/main/java/org/alfresco/repo/rendition2/RenditionDefinitionRegistry2Impl.java
  repository/src/main/java/org/alfresco/repo/rendition2/TransformDefinition.java
  repository/src/main/java/org/alfresco/repo/rendition2/TransformRequestProcessor.java
  repository/src/main/resources/alfresco/content-services-context.xml
  repository/src/test/java/org/alfresco/repo/action/executer/AsynchronousExtractorTest.java
Labels: PR: reviewed-approved

#183 ACS-953 Unable to upgrade from ACS-7.0-M1 or ACS-7.0-M2 to ACS-7.0-A12
  core/src/test/java/org/alfresco/util/VersionNumberTest.java
  repository/src/main/java/org/alfresco/repo/module/ModuleVersionNumber.java
  repository/src/test/java/org/alfresco/AllUnitTestsSuite.java
  repository/src/test/java/org/alfresco/repo/module/ModuleVersionNumberTest.java
Labels: PR: unreviewed
