Repository Alfresco/alfresco-community-repo, pull requests merged in 2021-04, with the labels that each got.

#291 MNT-20500 - Admin console breaks with serialised objects
  remote-api/src/main/resources/alfresco/templates/webscripts/org/alfresco/repository/admin/support-tools/admin-nodebrowser.get.html.ftl
Labels: PR: reviewed-approved

#371 SEARCH-2782 use current transaction timestamp instead of current time as event time
  repository/src/main/java/org/alfresco/repo/event2/EventGenerator.java
  repository/src/main/resources/alfresco/events2-context.xml
  repository/src/test/java/org/alfresco/repo/event2/CreateRepoEventIT.java
Labels: PR: partially-approved

#376 Revert "SEARCH-2782 use current transaction timestamp instead of current time as event time"
  repository/src/main/java/org/alfresco/repo/event2/EventGenerator.java
  repository/src/main/resources/alfresco/events2-context.xml
  repository/src/test/java/org/alfresco/repo/event2/CreateRepoEventIT.java
Labels: PR: reviewed-approved

#360 Bugfix/repo 5610 events are not actually sent to activemq
  repository/src/main/java/org/alfresco/repo/event2/EventGenerator.java
  repository/src/main/java/org/alfresco/repo/event2/EventGeneratorQueue.java
  repository/src/main/resources/alfresco/events2-context.xml
  repository/src/main/resources/alfresco/repository.properties
  repository/src/test/java/org/alfresco/repo/event2/AbstractContextAwareRepoEvent.java
  repository/src/test/java/org/alfresco/repo/event2/EventGeneratorQueueUnitTest.java
  repository/src/test/java/org/alfresco/repo/event2/EventGeneratorTest.java
  repository/src/test/java/org/alfresco/repo/event2/RepoEvent2ITSuite.java
  repository/src/test/java/org/alfresco/repo/event2/RepoEvent2UnitSuite.java
Labels: PR: partially-approved

#380 MNT-22300/MNT-22301 Performance of property update in 7.0.0
  repository/src/main/java/org/alfresco/repo/event2/EventGenerator.java
  repository/src/main/java/org/alfresco/repo/event2/EventGeneratorQueue.java
  repository/src/main/resources/alfresco/events2-context.xml
  repository/src/main/resources/alfresco/repository.properties
  repository/src/test/java/org/alfresco/repo/event2/AbstractContextAwareRepoEvent.java
  repository/src/test/java/org/alfresco/repo/event2/EventGeneratorQueueUnitTest.java
  repository/src/test/java/org/alfresco/repo/event2/EventGeneratorTest.java
  repository/src/test/java/org/alfresco/repo/event2/RepoEvent2ITSuite.java
  repository/src/test/java/org/alfresco/repo/event2/RepoEvent2UnitSuite.java
Labels: PR: unreviewed

#382 Feature/search 2802 shared secret auth
  core/src/main/java/org/alfresco/httpclient/HttpClientFactory.java
  core/src/main/java/org/alfresco/httpclient/RequestHeadersHttpClient.java
  remote-api/src/main/java/org/alfresco/repo/web/scripts/solr/SOLRAuthenticationFilter.java
  remote-api/src/main/java/org/alfresco/web/app/servlet/AlfrescoX509ServletFilter.java
  repository/src/main/resources/alfresco/subsystems/Search/solr6/solr-search-context.xml
  repository/src/test/java/org/alfresco/repo/search/impl/solr/SolrStoreMappingWrapperTest.java
Labels: PR: partially-approved

#368 Add unit test to look for unreferenced test classes.
  repository/pom.xml
  repository/src/test/java/org/alfresco/AllUnitTestsSuite.java
  repository/src/test/java/org/alfresco/messaging/camel/CamelComponentsTest.java
  repository/src/test/java/org/alfresco/messaging/camel/CamelRoutesTest.java
  repository/src/test/java/org/alfresco/repo/action/constraint/ActionParameterConstraintTest.java
  repository/src/test/java/org/alfresco/repo/action/evaluator/HasChildEvaluatorTest.java
  repository/src/test/java/org/alfresco/repo/action/evaluator/HasTagEvaluatorTest.java
  repository/src/test/java/org/alfresco/repo/action/executer/CheckOutActionExecuterTest.java
  repository/src/test/java/org/alfresco/repo/action/executer/ExecuteAllRulesActionExecuterTest.java
  repository/src/test/java/org/alfresco/repo/action/executer/TakeOwnershipActionExecuterTest.java
  repository/src/test/java/org/alfresco/repo/action/executer/TransitionSimpleWorkflowActionExecuterTest.java
  repository/src/test/java/org/alfresco/repo/action/scheduled/FreeMarkerModelLuceneFunctionTest.java
  repository/src/test/java/org/alfresco/repo/bulkimport/impl/AbstractBulkImportTests.java
  repository/src/test/java/org/alfresco/repo/content/MimetypeMapContentTest.java
  repository/src/test/java/org/alfresco/repo/content/caching/CachingContentStoreSpringTest.java
  repository/src/test/java/org/alfresco/repo/content/filestore/BucketAwareFileContentStoreTest.java
  repository/src/test/java/org/alfresco/repo/content/filestore/VolumeAwareFileContentStoreTest.java
  repository/src/test/java/org/alfresco/repo/content/metadata/xml/XmlMetadataExtracterTest.java
  repository/src/test/java/org/alfresco/repo/content/replication/AggregatingContentStoreTest.java
  repository/src/test/java/org/alfresco/repo/content/transform/RemoteTransformerClientTest.java
  repository/src/test/java/org/alfresco/repo/dictionary/DictionaryDAOTest.java
  repository/src/test/java/org/alfresco/repo/dictionary/DictionaryLoadDAOTest.java
  repository/src/test/java/org/alfresco/repo/domain/node/NodePropertyHelperTest.java
  repository/src/test/java/org/alfresco/repo/domain/subscriptions/SubscriptionDAOTest.java
  repository/src/test/java/org/alfresco/repo/imap/LoadTester.java
  repository/src/test/java/org/alfresco/repo/imap/RemoteLoadTester.java
  repository/src/test/java/org/alfresco/repo/invitation/FullInvitationServiceImplTests.java
  repository/src/test/java/org/alfresco/repo/node/MetadataEncryptorTests.java
  repository/src/test/java/org/alfresco/repo/notification/NotificationServiceImplSystemTest.java
  repository/src/test/java/org/alfresco/repo/rendition/executer/AbstractRenderingEngineTest.java
  repository/src/test/java/org/alfresco/repo/rendition2/LocalSynchronousTransformClientIntegrationTest.java
  repository/src/test/java/org/alfresco/repo/rendition2/RenditionEventProcessorTest.java
  repository/src/test/java/org/alfresco/repo/rule/BaseRuleTest.java
  repository/src/test/java/org/alfresco/repo/search/impl/querymodel/impl/db/DBQueryTest.java
  repository/src/test/java/org/alfresco/repo/security/authority/script/ScriptAuthorityServiceTest.java
  repository/src/test/java/org/alfresco/repo/security/permissions/impl/AbstractPermissionTest.java
  repository/src/test/java/org/alfresco/repo/security/permissions/impl/AbstractReadPermissionTest.java
  repository/src/test/java/org/alfresco/repo/site/CustomRoleTest.java
  repository/src/test/java/org/alfresco/repo/site/SiteServiceTestHuge.java
  repository/src/test/java/org/alfresco/repo/tenant/AbstractTenantRoutingContentStoreTest.java
  repository/src/test/java/org/alfresco/repo/version/VersionableAspectTest.java
  repository/src/test/java/org/alfresco/repo/workflow/activiti/AbstractActivitiComponentTest.java
  repository/src/test/java/org/alfresco/repo/workflow/activiti/ActivitiSmokeTest.java
  repository/src/test/java/org/alfresco/repo/workflow/activiti/ActivitiSpringTest.java
  repository/src/test/java/org/alfresco/repo/workflow/activiti/ActivitiTaskComponentTest.java
  repository/src/test/java/org/alfresco/util/debug/OutputSpacesStoreSystemTest.java
  repository/src/test/java/org/alfresco/util/test/OmittedTestClassFinderUnitTest.java
Labels: PR: reviewed-approved

#358 ACS-276 tas test for rendition version
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/renditions/RenditionVersionTests.java
Labels: PR: partially-approved

#390 MNT-22186: propTablesCleanupJobDetail v2 can cause Out of Memory erro…
  repository/src/main/java/org/alfresco/repo/domain/schema/script/DeleteNotExistsExecutor.java
  repository/src/main/java/org/alfresco/repo/domain/schema/script/ScriptExecutorImpl.java
  repository/src/test/java/org/alfresco/repo/domain/schema/script/DeleteNotExistsExecutorTest.java
Labels: PR: reviewed-approved

#377 SEARCH-2782 commit time as event time
  repository/src/main/java/org/alfresco/repo/domain/node/AbstractNodeDAOImpl.java
  repository/src/main/java/org/alfresco/repo/domain/node/NodeDAO.java
  repository/src/main/java/org/alfresco/repo/domain/permissions/AclDAO.java
  repository/src/main/java/org/alfresco/repo/domain/permissions/AclDAOImpl.java
  repository/src/main/java/org/alfresco/repo/event2/EventGenerator.java
  repository/src/main/resources/alfresco/events2-context.xml
  repository/src/test/java/org/alfresco/repo/domain/node/NodeDAOTest.java
  repository/src/test/java/org/alfresco/repo/event2/CreateRepoEventIT.java
  repository/src/test/java/org/alfresco/repo/security/permissions/impl/AclDaoComponentTest.java
Labels: PR: unreviewed

#394 Revert "MNT-22186: propTablesCleanupJobDetail v2 can cause Out of Memory erro…"
  repository/src/main/java/org/alfresco/repo/domain/schema/script/DeleteNotExistsExecutor.java
  repository/src/main/java/org/alfresco/repo/domain/schema/script/ScriptExecutorImpl.java
  repository/src/test/java/org/alfresco/repo/domain/schema/script/DeleteNotExistsExecutorTest.java
Labels: PR: unreviewed

#395 SEARCH-2748 Bump restapi from 1.57 to 1.58
  pom.xml
Labels: PR: reviewed-approved

#402 MNT-22186: propTablesCleanupJobDetail v2 can cause Out of Memory erro…
  repository/src/main/java/org/alfresco/repo/domain/schema/script/DeleteNotExistsExecutor.java
  repository/src/main/java/org/alfresco/repo/domain/schema/script/MySQLDeleteNotExistsExecutor.java
  repository/src/main/java/org/alfresco/repo/domain/schema/script/ScriptExecutorImpl.java
  repository/src/test/java/org/alfresco/AllDBTestsTestSuite.java
  repository/src/test/java/org/alfresco/AppContextExtraTestSuite.java
  repository/src/test/java/org/alfresco/repo/domain/schema/script/DeleteNotExistsExecutorTest.java
Labels: PR: reviewed-approved

#407 Apps 937 Run AGS community tests
  .travis.yml
  amps/ags/pom.xml
  amps/ags/rm-automation/pom.xml
  amps/ags/rm-automation/rm-automation-community-rest-api/pom.xml
  amps/ags/rm-automation/rm-automation-community-rest-api/src/main/java/org/alfresco/rest/rm/community/requests/gscore/api/RMSiteAPI.java
  amps/ags/rm-community/rm-community-repo/config/alfresco/module/org_alfresco_module_rm/security/rm-policy-context.xml
  amps/ags/rm-community/rm-community-repo/docker-compose.yml
  amps/ags/rm-community/rm-community-repo/pom.xml
  scripts/travis/cleanup_cache.sh
Labels: PR: unreviewed

#408 ACS-1404 : Trashcan Cleaner job doesn't work when trying to delete from a big amount of data
  pom.xml
Labels: PR: reviewed-approved

#386 [ACS-1455] Schema validation report expansion with patch specific problems told apart
  repository/src/main/java/org/alfresco/repo/admin/patch/impl/SchemaUpgradeScriptPatch.java
  repository/src/main/java/org/alfresco/repo/domain/schema/SchemaBootstrap.java
  repository/src/main/java/org/alfresco/repo/domain/schema/SchemaBootstrapRegistration.java
  repository/src/main/java/org/alfresco/util/schemacomp/SchemaDifferenceHelper.java
  repository/src/main/resources/alfresco/bootstrap-context.xml
  repository/src/main/resources/alfresco/dbscripts/db-schema-context.xml
  repository/src/main/resources/alfresco/messages/system-messages.properties
  repository/src/test/java/org/alfresco/AllUnitTestsSuite.java
  repository/src/test/java/org/alfresco/AppContext04TestSuite.java
  repository/src/test/java/org/alfresco/util/schemacomp/SchemaBootstrapTest.java
  repository/src/test/java/org/alfresco/util/schemacomp/SchemaDifferenceHelperUnitTest.java
  repository/src/test/resources/alfresco/dbscripts/create/org.alfresco.repo.domain.dialect.PostgreSQLDialect/Test-Schema-Reference-ALF.xml
  repository/src/test/resources/alfresco/dbscripts/test-bootstrap-context.xml
  repository/src/test/resources/alfresco/dbscripts/upgrade/0/org.alfresco.repo.domain.dialect.PostgreSQLDialect/add-index-test-problem-patterns.txt
  repository/src/test/resources/alfresco/dbscripts/upgrade/0/org.alfresco.repo.domain.dialect.PostgreSQLDialect/add-index-test.sql
Labels: PR: unreviewed

#417 Feature/acs 1425 long running tmdq
  repository/src/main/java/org/alfresco/repo/search/impl/querymodel/impl/db/DBQueryEngine.java
  repository/src/test/java/org/alfresco/repo/search/impl/querymodel/impl/db/DBQueryEngineTest.java
Labels: PR: reviewed-approved

#421 ACS-1425 Get stores at start of query
  repository/src/main/java/org/alfresco/repo/search/impl/querymodel/impl/db/DBQueryEngine.java
Labels: PR: reviewed-approved
