Repository Alfresco/alfresco-community-repo, pull requests merged in 2021-06, with the labels that each got.

#508 Feature/rm 7103 changes from governance pr#1421
  amps/ags/rm-community/rm-community-repo/source/java/org/alfresco/module/org_alfresco_module_rm/disposition/DispositionServiceImpl.java
  amps/ags/rm-community/rm-community-repo/test/java/org/alfresco/module/org_alfresco_module_rm/test/integration/disposition/DispositionScheduleInheritanceTest.java
  amps/ags/rm-community/rm-community-repo/test/java/org/alfresco/module/org_alfresco_module_rm/test/util/CommonRMTestUtils.java
Labels: PR: partially-approved

#507 MNT-22186: propTablesCleanupJobDetail v2 can cause Out of Memory erro…
  repository/src/main/java/org/alfresco/repo/domain/schema/script/DeleteNotExistsExecutor.java
  repository/src/main/java/org/alfresco/repo/domain/schema/script/MySQLDeleteNotExistsExecutor.java
Labels: PR: reviewed-approved

#513 Revert "Bump mariadb-java-client from 2.7.2 to 2.7.3"
  pom.xml
Labels: PR: unreviewed

#500 REPO-5234: Metadata extraction fails for Embedded files
  pom.xml
Labels: PR: partially-approved

#502 APPS-491 - [AGS] Value saved for Retention Parameter is different
  amps/ags/rm-community/rm-community-repo/source/java/org/alfresco/repo/rule/ExtendedRuleServiceImpl.java
Labels: PR: partially-approved

#498 ACS-1602 : Update & tests for AbstractRoutingContentStore
  repository/src/main/java/org/alfresco/repo/content/AbstractRoutingContentStore.java
  repository/src/test/java/org/alfresco/repo/content/RoutingContentStoreTest.java
Labels: PR: partially-approved

#517 ACS-1630 : Storage classes - REST api - GET /nodes/{nodeId}
  data-model/src/main/java/org/alfresco/repo/content/ContentStore.java
  remote-api/src/main/java/org/alfresco/rest/api/Nodes.java
  remote-api/src/main/java/org/alfresco/rest/api/impl/NodesImpl.java
  remote-api/src/main/java/org/alfresco/rest/api/model/ContentInfo.java
  remote-api/src/main/java/org/alfresco/rest/framework/resource/content/BinaryProperty.java
  remote-api/src/main/java/org/alfresco/rest/framework/resource/content/ContentInfo.java
  remote-api/src/main/java/org/alfresco/rest/framework/resource/content/ContentInfoImpl.java
  remote-api/src/test/java/org/alfresco/rest/api/tests/NodeApiTest.java
  remote-api/src/test/java/org/alfresco/rest/api/tests/client/data/ContentInfo.java
  repository/src/main/resources/alfresco/public-services-security-context.xml
  repository/src/test/java/org/alfresco/repo/version/ContentServiceImplTest.java
Labels: PR: unreviewed

#509 ACS-1584: REST API storage-classes endpoint
  remote-api/src/main/java/org/alfresco/rest/api/ContentStorageClasses.java
  remote-api/src/main/java/org/alfresco/rest/api/impl/ContentStorageClassesImpl.java
  remote-api/src/main/java/org/alfresco/rest/api/model/StorageClass.java
  remote-api/src/main/java/org/alfresco/rest/api/storageclasses/StorageClassesEntityResource.java
  remote-api/src/main/java/org/alfresco/rest/api/storageclasses/package-info.java
  remote-api/src/main/resources/alfresco/public-rest-context.xml
  remote-api/src/test/java/org/alfresco/AppContext02TestSuite.java
  remote-api/src/test/java/org/alfresco/rest/api/tests/ApiTest.java
  remote-api/src/test/java/org/alfresco/rest/api/tests/StorageClassesTest.java
  repository/src/main/resources/alfresco/public-services-security-context.xml
Labels: PR: partially-approved

#526 ACS-1646 Reduce time to buid AGS jobs in repo projects
  .travis.yml
  amps/ags/rm-community/rm-community-repo/pom.xml
  amps/ags/rm-community/rm-community-repo/test/java/org/alfresco/module/org_alfresco_module_rm/test/AllTestSuitePt1.java
  amps/ags/rm-community/rm-community-repo/test/java/org/alfresco/module/org_alfresco_module_rm/test/AllTestSuitePt2.java
  amps/ags/rm-community/rm-community-repo/test/java/org/alfresco/module/org_alfresco_module_rm/test/AllTestSuitePt3.java
Labels: PR: reviewed-approved

#528 RM-7169 : Disposition Lifecycle job runs in a infinite loop
  amps/ags/rm-community/rm-community-repo/source/java/org/alfresco/module/org_alfresco_module_rm/job/DispositionLifecycleJobExecuter.java
  amps/ags/rm-community/rm-community-repo/unit-test/java/org/alfresco/module/org_alfresco_module_rm/job/DispositionLifecycleJobExecuterUnitTest.java
Labels: PR: reviewed-approved

#534 RM-7171 Remove reference to http://swagger.io/v2/schema.json to avoid downloading schema.
  amps/ags/rm-community/rm-community-repo/unit-test/resources/rest/schema.json
Labels: PR: partially-approved

#536 MNT-20500 - Admin console breaks with serialised objects
  amps/share-services/src/main/resources/alfresco/templates/webscripts/org/alfresco/slingshot/node-browser/node-browser.get.json.ftl
  remote-api/src/main/resources/alfresco/templates/webscripts/org/alfresco/repository/admin/support-tools/admin-nodebrowser.get.html.ftl
Labels: PR: reviewed-approved

#535 ATS-936 : bump T-engines to version 2.5.0
  .travis.yml
  amps/ags/rm-community/rm-community-repo/.env
  packaging/tests/environment/.env
Labels: PR: partially-approved

#538 MNT-20500 - Admin console breaks with serialised objects
  remote-api/src/main/resources/alfresco/templates/webscripts/org/alfresco/repository/admin/support-tools/admin-nodebrowser.get.html.ftl
Labels: PR: unreviewed

#539 MNT-22388 [Security] multiple pdfbox vulnerabilities (Repo)
  data-model/pom.xml
  repository/src/main/java/org/alfresco/repo/rendition/executer/HTMLRenderingEngine.java
  repository/src/main/resources/alfresco/rendition-services-context.xml
  repository/src/test/java/org/alfresco/AppContext02TestSuite.java
  repository/src/test/java/org/alfresco/AppContext04TestSuite.java
  repository/src/test/java/org/alfresco/repo/content/MimetypeMapContentTest.java
  repository/src/test/java/org/alfresco/repo/rendition/AllRenditionTests.java
  repository/src/test/java/org/alfresco/repo/rendition/executer/HTMLRenderingEngineTest.java
Labels: PR: reviewed-approved

#541 MNT-21837 License expires 23h earlier
  repository/src/main/java/org/alfresco/repo/usage/RepoUsageComponentImpl.java
  repository/src/main/java/org/alfresco/util/DateUtil.java
  repository/src/test/java/org/alfresco/repo/usage/RepoUsageComponentTest.java
Labels: PR: reviewed-approved

#543 MNT-21837 License expires 23h earlier (#541)
  repository/src/main/java/org/alfresco/repo/usage/RepoUsageComponentImpl.java
  repository/src/main/java/org/alfresco/util/DateUtil.java
  repository/src/test/java/org/alfresco/repo/usage/RepoUsageComponentTest.java
Labels: PR: unreviewed

#544 MNT-21837 - License expires 23h earlier - correction
  repository/src/main/java/org/alfresco/repo/usage/RepoUsageComponentImpl.java
  repository/src/main/java/org/alfresco/util/DateUtil.java
  repository/src/test/java/org/alfresco/repo/usage/RepoUsageComponentTest.java
Labels: PR: unreviewed

#547 MNT-21837 - License expires 23h earlier - correction (#544)
  repository/src/main/java/org/alfresco/repo/usage/RepoUsageComponentImpl.java
  repository/src/main/java/org/alfresco/util/DateUtil.java
  repository/src/test/java/org/alfresco/repo/usage/RepoUsageComponentTest.java
Labels: PR: unreviewed

#391 [MNT-21611] Removed HTML transformation pipelines (with LibreOffice). Added new HTML pipelines via TEXT.
  repository/src/main/resources/alfresco/transforms/0100-basePipelines.json
Labels: PR: partially-approved

#553 [MNT-21611] Removed HTML transformation pipelines (with LibreOffice). Added new HTML pipelines via TEXT.
  repository/src/main/resources/alfresco/transforms/0100-basePipelines.json
Labels: PR: reviewed-approved

#554 [MNT-21611] Removed HTML transformation pipelines (with LibreOffice). Added new HTML pipelines via TEXT.
  repository/src/main/resources/alfresco/transforms/0100-basePipelines.json
Labels: PR: reviewed-approved

#563 SEARCH-2876 Update Solr 2.0.2-RC1
  amps/ags/rm-community/rm-community-repo/.env
  packaging/tests/environment/.env
Labels: PR: unreviewed

#564 SEARCH-2876 Update Solr 2.0.2-RC1
  packaging/tests/environment/.env
Labels: PR: unreviewed

#565 ACS-1633 : Storage classes - REST api - PUT /nodes/{nodeId}
  remote-api/src/main/java/org/alfresco/rest/api/impl/NodesImpl.java
  repository/src/main/resources/alfresco/public-services-security-context.xml
Labels: PR: partially-approved

#558 [ACS-1715] Deprecate reset-password APIs
  remote-api/src/main/java/org/alfresco/rest/api/People.java
  remote-api/src/main/java/org/alfresco/rest/api/impl/PeopleImpl.java
  remote-api/src/main/java/org/alfresco/rest/api/people/PeopleEntityResource.java
  repository/src/main/java/org/alfresco/repo/security/authentication/ResetPasswordService.java
  repository/src/main/java/org/alfresco/repo/security/authentication/ResetPasswordServiceImpl.java
  repository/src/main/java/org/alfresco/repo/security/authentication/activiti/AbstractResetPasswordDelegate.java
  repository/src/main/java/org/alfresco/repo/security/authentication/activiti/PerformResetPasswordDelegate.java
  repository/src/main/java/org/alfresco/repo/security/authentication/activiti/SendResetPasswordConfirmationEmailDelegate.java
  repository/src/main/java/org/alfresco/repo/security/authentication/activiti/SendResetPasswordEmailDelegate.java
  repository/src/main/java/org/alfresco/repo/workflow/WorkflowModelResetPassword.java
Labels: PR: partially-approved

#567 Bump camel-amqp 3.7.1 to 3.7.4 and netty 4.1.58.Final to 4.1.60.Final
  pom.xml
Labels: PR: unreviewed

#559 ACS-1711 : [SPIKE] Update the S3 connector to support Storage Classes
  data-model/src/main/java/org/alfresco/repo/content/ContentStore.java
  data-model/src/main/java/org/alfresco/repo/content/StorageClassSet.java
  remote-api/src/main/java/org/alfresco/rest/api/impl/ContentStorageClassesImpl.java
  remote-api/src/main/java/org/alfresco/rest/framework/resource/content/BinaryProperty.java
  remote-api/src/test/java/org/alfresco/rest/api/tests/NodeApiTest.java
  remote-api/src/test/java/org/alfresco/rest/api/tests/StorageClassesTest.java
  repository/src/main/java/org/alfresco/repo/content/AbstractRoutingContentStore.java
  repository/src/main/java/org/alfresco/repo/content/ContentServiceImpl.java
  repository/src/main/java/org/alfresco/repo/content/caching/CachingContentStore.java
  repository/src/main/java/org/alfresco/repo/content/replication/AggregatingContentStore.java
  repository/src/main/java/org/alfresco/repo/tenant/AbstractTenantRoutingContentStore.java
  repository/src/main/java/org/alfresco/service/cmr/repository/ContentService.java
  repository/src/test/java/org/alfresco/repo/content/RoutingContentStoreTest.java
  repository/src/test/java/org/alfresco/repo/content/caching/CachingContentStoreTest.java
  repository/src/test/java/org/alfresco/repo/content/filestore/FileContentStoreTest.java
  repository/src/test/java/org/alfresco/repo/content/replication/AggregatingContentStoreTest.java
  repository/src/test/java/org/alfresco/repo/tenant/AbstractTenantRoutingContentStoreTest.java
  repository/src/test/java/org/alfresco/repo/version/ContentServiceImplTest.java
  repository/src/test/java/org/alfresco/repo/version/ContentServiceImplWithMockedContentStoreTest.java
Labels: PR: partially-approved

#511 APPS-986: [AGS] Export of records with size> 4 MB fails
  remote-api/src/main/java/org/alfresco/repo/web/scripts/RepositoryContainer.java
Labels: PR: reviewed-approved

#540 ACS-1631 : Storage classes - REST api - POST & GET /nodes/{nodeId}/children
  data-model/src/main/java/org/alfresco/repo/content/ContentContext.java
  data-model/src/main/java/org/alfresco/repo/content/StorageClassSet.java
  remote-api/src/main/java/org/alfresco/rest/api/impl/NodesImpl.java
  remote-api/src/main/java/org/alfresco/rest/api/model/ContentInfo.java
  remote-api/src/main/java/org/alfresco/rest/framework/resource/content/ContentInfo.java
  remote-api/src/main/java/org/alfresco/rest/framework/resource/content/ContentInfoImpl.java
  remote-api/src/test/java/org/alfresco/rest/api/tests/NodeApiTest.java
  remote-api/src/test/java/org/alfresco/rest/api/tests/client/data/ContentInfo.java
  repository/src/main/java/org/alfresco/repo/content/ContentServiceImpl.java
  repository/src/main/java/org/alfresco/repo/content/NodeContentContext.java
  repository/src/main/java/org/alfresco/service/cmr/repository/ContentService.java
Labels: PR: partially-approved

#572 ACS-1734 Remove broken transformerFailover from libreofficeToPdf
  repository/src/main/resources/alfresco/transforms/0100-basePipelines.json
Labels: PR: reviewed-approved
