Repository Alfresco/alfresco-community-repo, pull requests merged in 2021-09, with the labels that each got.

#687 ACS-1880 handle defaults for missing properties
  remote-api/src/main/resources/alfresco/public-rest-context.xml
  repository/src/main/resources/alfresco/content-services-context.xml
Labels: PR: reviewed-approved

#688 Feature/acs 1924 remove version renditions end point
  remote-api/src/main/java/org/alfresco/rest/api/nodes/NodeRenditionsRelation.java
  remote-api/src/main/java/org/alfresco/rest/api/nodes/NodeVersionRenditionsRelation.java
  remote-api/src/main/java/org/alfresco/rest/api/nodes/NodeVersionsRelation.java
  remote-api/src/main/java/org/alfresco/rest/api/nodes/NodesEntityResource.java
  remote-api/src/main/java/org/alfresco/rest/api/trashcan/TrashcanEntityResource.java
  remote-api/src/main/java/org/alfresco/rest/api/trashcan/TrashcanRenditionsRelation.java
  remote-api/src/main/resources/alfresco/public-rest-context.xml
  remote-api/src/test/java/org/alfresco/rest/api/tests/NodeApiTest.java
Labels: PR: reviewed-approved

#691 LOC-329 - Fixed, updated UI files in 15 languages as per RM-6941
  amps/ags/rm-community/rm-community-repo/config/alfresco/module/org_alfresco_module_rm/messages/action-service_cs.properties
  amps/ags/rm-community/rm-community-repo/config/alfresco/module/org_alfresco_module_rm/messages/action-service_da.properties
  amps/ags/rm-community/rm-community-repo/config/alfresco/module/org_alfresco_module_rm/messages/action-service_de.properties
  amps/ags/rm-community/rm-community-repo/config/alfresco/module/org_alfresco_module_rm/messages/action-service_es.properties
  amps/ags/rm-community/rm-community-repo/config/alfresco/module/org_alfresco_module_rm/messages/action-service_fi.properties
  amps/ags/rm-community/rm-community-repo/config/alfresco/module/org_alfresco_module_rm/messages/action-service_fr.properties
  amps/ags/rm-community/rm-community-repo/config/alfresco/module/org_alfresco_module_rm/messages/action-service_it.properties
  amps/ags/rm-community/rm-community-repo/config/alfresco/module/org_alfresco_module_rm/messages/action-service_ja.properties
  amps/ags/rm-community/rm-community-repo/config/alfresco/module/org_alfresco_module_rm/messages/action-service_nb.properties
  amps/ags/rm-community/rm-community-repo/config/alfresco/module/org_alfresco_module_rm/messages/action-service_nl.properties
  amps/ags/rm-community/rm-community-repo/config/alfresco/module/org_alfresco_module_rm/messages/action-service_pl.properties
  amps/ags/rm-community/rm-community-repo/config/alfresco/module/org_alfresco_module_rm/messages/action-service_pt_BR.properties
  amps/ags/rm-community/rm-community-repo/config/alfresco/module/org_alfresco_module_rm/messages/action-service_ru.properties
  amps/ags/rm-community/rm-community-repo/config/alfresco/module/org_alfresco_module_rm/messages/action-service_sv.properties
  amps/ags/rm-community/rm-community-repo/config/alfresco/module/org_alfresco_module_rm/messages/action-service_zh_CN.properties
  repository/src/main/resources/alfresco/messages/content-model_da.properties
  repository/src/main/resources/alfresco/messages/iptc-model_da.properties
  repository/src/main/resources/alfresco/messages/system-messages_de.properties
  repository/src/main/resources/alfresco/messages/system-messages_es.properties
  repository/src/main/resources/alfresco/messages/system-messages_fr.properties
  repository/src/main/resources/alfresco/messages/system-messages_it.properties
  repository/src/main/resources/alfresco/messages/system-messages_ja.properties
  repository/src/main/resources/alfresco/messages/system-messages_nb.properties
  repository/src/main/resources/alfresco/messages/system-messages_nl.properties
  repository/src/main/resources/alfresco/messages/system-messages_pt_BR.properties
  repository/src/main/resources/alfresco/messages/system-messages_ru.properties
  repository/src/main/resources/alfresco/messages/system-messages_zh_CN.properties
Labels: PR: unreviewed

#689 Feature/acs 1835 test dau for deleted renditions
  remote-api/src/test/java/org/alfresco/rest/DeletedNodesTest.java
  remote-api/src/test/java/org/alfresco/rest/api/tests/AbstractBaseApiTest.java
Labels: PR: reviewed-approved

#690 REPO-5664/REPO-5665: System admin webscripts
  pom.xml
  remote-api/src/main/java/org/alfresco/repo/web/scripts/RepositoryContainer.java
  remote-api/src/main/java/org/alfresco/web/scripts/WebScriptUtils.java
  remote-api/src/main/resources/alfresco/templates/webscripts/org/alfresco/repository/admin/admin-common.lib.js
  remote-api/src/main/resources/alfresco/templates/webscripts/org/alfresco/repository/admin/admin-communitysummary.get.desc.xml
  remote-api/src/main/resources/alfresco/templates/webscripts/org/alfresco/repository/admin/admin-root.get.desc.xml
  remote-api/src/main/resources/alfresco/templates/webscripts/org/alfresco/repository/admin/jmxdump.get.desc.xml
  remote-api/src/main/resources/alfresco/templates/webscripts/org/alfresco/repository/admin/usage.post.desc.xml
  remote-api/src/test/java/org/alfresco/repo/web/scripts/admin/AdminWebScriptTest.java
Labels: PR: partially-approved

#693 ACS-1970-switch-to-cenos-7-base-image
  packaging/docker-alfresco/Dockerfile
Labels: PR: reviewed-approved

#694 Update api-explorer to 7.1.0.1
  pom.xml
Labels: PR: reviewed-approved

#698 MNT-22428: configurable unsecure jsonp callback CMIS operation
  remote-api/src/main/java/org/alfresco/opencmis/CMISServletDispatcher.java
  remote-api/src/main/java/org/alfresco/rest/framework/core/exceptions/JsonpCallbackNotAllowedException.java
  remote-api/src/main/resources/alfresco/messages/rest-framework-messages.properties
  remote-api/src/main/resources/alfresco/public-rest-context.xml
  remote-api/src/test/java/org/alfresco/rest/api/tests/TestCMIS.java
  repository/src/main/resources/alfresco/repository.properties
Labels: PR: partially-approved

#699 MNT-22611 - Fix bulk import parameters parsing
  remote-api/src/main/java/org/alfresco/repo/web/scripts/bulkimport/AbstractBulkFileSystemImportWebScript.java
  remote-api/src/main/java/org/alfresco/repo/web/scripts/bulkimport/copy/BulkFilesystemImportWebScript.java
  remote-api/src/test/java/org/alfresco/AppContext01TestSuite.java
  remote-api/src/test/java/org/alfresco/repo/web/scripts/bulkimport/BulkImportParametersExtractorTest.java
Labels: PR: reviewed-approved

#702 MNT-22600 Nodes with security marks appear unfiltered on CMIS DB queries
  amps/ags/rm-automation/rm-automation-community-rest-api/src/test/java/org/alfresco/rest/rm/community/base/BaseRMRestTest.java
  amps/ags/rm-community/rm-community-repo/source/java/org/alfresco/module/org_alfresco_module_rm/capability/RMAfterInvocationProvider.java
Labels: PR: unreviewed

#704 MNT-22428: configurable unsecure jsonp callback CMIS operation (#698)
  remote-api/src/main/java/org/alfresco/opencmis/CMISServletDispatcher.java
  remote-api/src/main/java/org/alfresco/rest/framework/core/exceptions/JsonpCallbackNotAllowedException.java
  remote-api/src/main/resources/alfresco/messages/rest-framework-messages.properties
  remote-api/src/main/resources/alfresco/public-rest-context.xml
  remote-api/src/test/java/org/alfresco/rest/api/tests/TestCMIS.java
  repository/src/main/resources/alfresco/repository.properties
Labels: PR: reviewed-approved

#700 ACS-2067: Fix probes when DAU (Direct Access Url) support is enabled
  remote-api/src/main/resources/alfresco/public-rest-context.xml
Labels: PR: partially-approved
