Repository Alfresco/alfresco-community-repo, pull requests merged in 2021-08, with the labels that each got.

#630 APPS-1073_Automated Rest API tests for checking Export for Records ha…
  amps/ags/rm-automation/rm-automation-community-rest-api/src/main/java/org/alfresco/rest/v0/ExportAPI.java
  amps/ags/rm-automation/rm-automation-community-rest-api/src/test/java/org/alfresco/rest/rm/community/records/ExportRecordsTests.java
  amps/ags/rm-automation/rm-automation-community-rest-api/src/test/java/org/alfresco/rest/rm/community/utils/FilePlanComponentsUtil.java
Labels: PR: unreviewed

#619 APPS-1068 : [AGS] Publish AGS-specific docker images from acs-packaging
  amps/ags/rm-community/rm-community-repo/pom.xml
Labels: PR: reviewed-approved

#639 MNT-22512: propTablesCleanupJobDetail v2 can cause Out of Memory
  repository/src/main/java/org/alfresco/repo/domain/schema/script/DeleteNotExistsExecutor.java
  repository/src/main/java/org/alfresco/repo/domain/schema/script/MySQLDeleteNotExistsExecutor.java
  repository/src/main/java/org/alfresco/repo/domain/schema/script/ScriptExecutorImpl.java
  repository/src/test/java/org/alfresco/AllDBTestsTestSuite.java
  repository/src/test/java/org/alfresco/AppContextExtraTestSuite.java
  repository/src/test/java/org/alfresco/repo/domain/schema/script/DeleteNotExistsExecutorTest.java
Labels: PR: reviewed-approved

#634 Acs 1865 impl configs for da us
  remote-api/src/main/java/org/alfresco/rest/api/impl/directurl/RestApiDirectUrlConfig.java
  remote-api/src/test/java/org/alfresco/AppContext04TestSuite.java
  remote-api/src/test/java/org/alfresco/rest/api/impl/RestApiDirectUrlConfigUnitTest.java
  repository/src/main/java/org/alfresco/repo/content/directurl/AbstractDirectUrlConfig.java
  repository/src/main/java/org/alfresco/repo/content/directurl/ContentStoreDirectUrlConfig.java
  repository/src/main/java/org/alfresco/repo/content/directurl/DirectUrlConfig.java
  repository/src/main/java/org/alfresco/repo/content/directurl/InvalidDirectAccessUrlConfigException.java
  repository/src/main/java/org/alfresco/repo/content/directurl/SystemWideDirectUrlConfig.java
  repository/src/main/resources/alfresco/content-services-context.xml
  repository/src/main/resources/alfresco/repository.properties
  repository/src/test/java/org/alfresco/AllUnitTestsSuite.java
  repository/src/test/java/org/alfresco/repo/content/directurl/ContentStoreDirectUrlConfigUnitTest.java
  repository/src/test/java/org/alfresco/repo/content/directurl/SystemWideDirectUrlConfigUnitTest.java
Labels: PR: reviewed-approved

#624 feature/APPS-1004
  amps/ags/rm-community/rm-community-repo/config/alfresco/module/org_alfresco_module_rm/rm-model-context.xml
  amps/ags/rm-community/rm-community-repo/source/java/org/alfresco/module/org_alfresco_module_rm/model/behaviour/AbstractDisposableItem.java
  amps/ags/rm-community/rm-community-repo/source/java/org/alfresco/module/org_alfresco_module_rm/model/rma/type/RecordCategoryType.java
  amps/ags/rm-community/rm-community-repo/source/java/org/alfresco/module/org_alfresco_module_rm/model/rma/type/RecordFolderType.java
  amps/ags/rm-community/rm-community-repo/test/java/org/alfresco/module/org_alfresco_module_rm/test/integration/disposition/DispositionScheduleInheritanceTest.java
  amps/ags/rm-community/rm-community-repo/test/java/org/alfresco/module/org_alfresco_module_rm/test/util/CommonRMTestUtils.java
Labels: PR: unreviewed

#644 PRODSEC-4422 - Scripts not in Data Dictionary can be executed by acti…
  repository/src/main/java/org/alfresco/repo/action/executer/ScriptActionExecuter.java
  repository/src/test/java/org/alfresco/repo/action/ActionServiceImpl2Test.java
  repository/src/test/java/org/alfresco/repo/action/ActionServiceImplTest.java
Labels: PR: unreviewed

#643 PRODSEC-4422 - Scripts not in Data Dictionary can be executed by acti…
  repository/src/main/java/org/alfresco/repo/action/executer/ScriptActionExecuter.java
  repository/src/test/java/org/alfresco/repo/action/ActionServiceImpl2Test.java
  repository/src/test/java/org/alfresco/repo/action/ActionServiceImplTest.java
Labels: PR: unreviewed

#641 ACS-1742 - Marked test as NOT_SUPPORTED_ON_SINGLE_PIPELINE
  packaging/tests/tas-cmis/src/test/java/org/alfresco/cmis/CancelCheckOutTests.java
  pom.xml
Labels: PR: partially-approved

#646 PRODSEC-4421 - Bump surf-webscripts to 7.22
  pom.xml
Labels: PR: unreviewed

#647 PRODSEC-4421 - Bump surf-webscripts to 8.22
  pom.xml
Labels: PR: unreviewed

#584 ACS-1773 APPS-986 Refactor on TempOutputStream, BufferedRequest, BufferedResponse & RepositoryContainer
  remote-api/src/main/java/org/alfresco/repo/web/scripts/BufferedRequest.java
  remote-api/src/main/java/org/alfresco/repo/web/scripts/BufferedResponse.java
  remote-api/src/main/java/org/alfresco/repo/web/scripts/RepositoryContainer.java
  remote-api/src/main/java/org/alfresco/repo/web/scripts/TempOutputStream.java
  remote-api/src/main/java/org/alfresco/repo/web/scripts/TempOutputStreamFactory.java
  remote-api/src/main/java/org/alfresco/repo/web/scripts/model/filefolder/FileFolderLoaderPost.java
  remote-api/src/main/java/org/alfresco/repo/web/scripts/transfer/PostSnapshotCommandProcessor.java
  remote-api/src/main/java/org/alfresco/rest/framework/webscripts/ApiWebScript.java
  remote-api/src/main/java/org/alfresco/web/scripts/WebScriptUtils.java
  remote-api/src/test/java/org/alfresco/rest/api/tests/BufferedResponseTest.java
  remote-api/src/test/java/org/alfresco/rest/api/tests/TempOutputStreamTest.java
Labels: PR: partially-approved

#645 Feature/acs 1782 impl request DAU in content service
  data-model/src/main/java/org/alfresco/repo/content/ContentStore.java
  data-model/src/main/java/org/alfresco/service/cmr/repository/DirectAccessUrl.java
  repository/src/main/java/org/alfresco/repo/content/ContentServiceImpl.java
  repository/src/main/java/org/alfresco/repo/content/caching/CachingContentStore.java
  repository/src/main/java/org/alfresco/repo/content/directurl/DirectAccessUrlDisabledException.java
  repository/src/main/java/org/alfresco/repo/content/replication/AggregatingContentStore.java
  repository/src/main/java/org/alfresco/service/cmr/repository/ContentService.java
  repository/src/main/resources/alfresco/content-services-context.xml
  repository/src/main/resources/alfresco/repository.properties
  repository/src/test/java/org/alfresco/AllUnitTestsSuite.java
  repository/src/test/java/org/alfresco/repo/content/ContentServiceImplUnitTest.java
  repository/src/test/java/org/alfresco/repo/content/caching/CachingContentStoreTest.java
  repository/src/test/java/org/alfresco/repo/content/replication/AggregatingContentStoreTest.java
  repository/src/test/java/org/alfresco/repo/version/ContentServiceImplTest.java
Labels: PR: reviewed-approved

#653 Feature/acs 1783 impl rest api for nodes
  remote-api/src/main/java/org/alfresco/rest/api/DirectAccessUrlHelper.java
  remote-api/src/main/java/org/alfresco/rest/api/Nodes.java
  remote-api/src/main/java/org/alfresco/rest/api/impl/NodesImpl.java
  remote-api/src/main/java/org/alfresco/rest/api/model/DirectAccessUrlRequest.java
  remote-api/src/main/java/org/alfresco/rest/api/nodes/NodesEntityResource.java
  remote-api/src/main/resources/alfresco/public-rest-context.xml
  repository/src/main/resources/alfresco/public-services-security-context.xml
Labels: PR: reviewed-approved

#655 ACS-1783 restore contexts
  remote-api/src/main/resources/alfresco/public-rest-context.xml
  repository/src/main/resources/alfresco/public-services-security-context.xml
Labels: PR: unreviewed

#656 ACS-1830 - Test requestContentDirectUrl for Nodes REST API endpoint (…
  remote-api/src/test/java/org/alfresco/rest/api/tests/AbstractBaseApiTest.java
  remote-api/src/test/java/org/alfresco/rest/api/tests/NodeApiTest.java
Labels: PR: unreviewed

#654 Feature/acs 1785 impl rest api for versions
  remote-api/src/main/java/org/alfresco/rest/api/nodes/NodeVersionsRelation.java
Labels: PR: unreviewed

#658 [PRODSEC-5254] Bump commons-compress to 1.21
  pom.xml
Labels: PR: reviewed-approved

#659 [PRODSEC-5254] Bump commons-compress to 1.21 (#658)
  pom.xml
Labels: PR: unreviewed

#660 [PRODSEC-5254] Bump commons-compress to 1.21 (#658)
  pom.xml
Labels: PR: unreviewed

#640 Fix/rm 6941 retention action on frozen nodes
  amps/ags/rm-automation/rm-automation-community-rest-api/src/test/java/org/alfresco/rest/rm/community/hold/PreventActionsOnFrozenContentTests.java
  amps/ags/rm-community/rm-community-repo/config/alfresco/module/org_alfresco_module_rm/messages/action-service.properties
  amps/ags/rm-community/rm-community-repo/config/alfresco/module/org_alfresco_module_rm/rm-job-context.xml
  amps/ags/rm-community/rm-community-repo/config/alfresco/module/org_alfresco_module_rm/rm-service-context.xml
  amps/ags/rm-community/rm-community-repo/pom.xml
  amps/ags/rm-community/rm-community-repo/source/java/org/alfresco/module/org_alfresco_module_rm/action/RecordsManagementActionServiceImpl.java
  amps/ags/rm-community/rm-community-repo/source/java/org/alfresco/module/org_alfresco_module_rm/disposition/DispositionServiceImpl.java
  amps/ags/rm-community/rm-community-repo/source/java/org/alfresco/module/org_alfresco_module_rm/freeze/FreezeService.java
  amps/ags/rm-community/rm-community-repo/source/java/org/alfresco/module/org_alfresco_module_rm/freeze/FreezeServiceImpl.java
  amps/ags/rm-community/rm-community-repo/source/java/org/alfresco/module/org_alfresco_module_rm/job/DispositionLifecycleJobExecuter.java
  amps/ags/rm-community/rm-community-repo/test/java/org/alfresco/module/org_alfresco_module_rm/test/legacy/service/FreezeServiceImplTest.java
  amps/module-info.java
  pom.xml
Labels: PR: unreviewed

#665 APPS-1068 Update the docker-compose
  amps/ags/rm-community/rm-community-repo/docker-compose.yml
Labels: PR: unreviewed

#661 ACS-1832 - Test requestContentDirectUrl for Versions REST API endpoint
  remote-api/src/test/java/org/alfresco/rest/api/tests/NodeApiTest.java
Labels: PR: partially-approved

#668 REPO-5659: Added ALFRESCO_SYSTEM_ADMINISTRATORS group authority.
  remote-api/src/test/java/org/alfresco/rest/api/tests/GroupsTest.java
  repository/src/main/java/org/alfresco/repo/security/authority/AuthorityServiceImpl.java
  repository/src/main/java/org/alfresco/service/cmr/security/AuthorityService.java
  repository/src/main/resources/alfresco/bootstrap/alfrescoAuthorityStore.xml
  repository/src/main/resources/alfresco/bootstrap/alfrescoAuthorityStoreDefaultMembers.xml
  repository/src/main/resources/alfresco/public-services-security-context.xml
  repository/src/test/java/org/alfresco/repo/security/authority/AuthorityServiceTest.java
Labels: PR: partially-approved

#666 PRODSEC-4331 - Bump spring version from 5.3.3 to 5.3.9
  pom.xml
  repository/src/main/java/org/alfresco/repo/management/SafeApplicationEventMulticaster.java
Labels: PR: reviewed-approved

#662 Feature/acs 1784 impl rest api for renditions
  remote-api/src/main/java/org/alfresco/rest/api/Renditions.java
  remote-api/src/main/java/org/alfresco/rest/api/impl/RenditionsImpl.java
  remote-api/src/main/java/org/alfresco/rest/api/nodes/NodeRenditionsRelation.java
  remote-api/src/main/java/org/alfresco/rest/api/nodes/NodeVersionsRelation.java
  remote-api/src/main/resources/alfresco/public-rest-context.xml
Labels: PR: reviewed-approved

#669 REPO-5660: A patch for the ALFRESCO_SYSTEM_ADMINISTRATORS group
  repository/src/main/resources/alfresco/messages/patch-service.properties
  repository/src/main/resources/alfresco/patch/patch-services-context.xml
  repository/src/main/resources/alfresco/repository.properties
Labels: PR: partially-approved

#670 ACS-1831 - Test requestContentDirectUrl for Renditions REST API endpoint
  remote-api/src/test/java/org/alfresco/rest/api/tests/NodeApiTest.java
Labels: PR: reviewed-approved

#673 [ACS-1893] Bump tas-restapi to 1.63
  pom.xml
Labels: PR: reviewed-approved

#648 ACS-1778 Common transform routing code for Repo and t-router
  pom.xml
  repository/pom.xml
  repository/src/main/java/org/alfresco/repo/content/transform/LocalCombinedConfig.java
  repository/src/main/java/org/alfresco/repo/content/transform/LocalTransformServiceRegistry.java
  repository/src/main/java/org/alfresco/transform/client/registry/CombinedConfig.java
  repository/src/main/java/org/alfresco/transform/client/registry/TransformServiceRegistryImpl.java
  repository/src/test/java/org/alfresco/AllUnitTestsSuite.java
  repository/src/test/java/org/alfresco/transform/client/registry/LocalTransformServiceRegistryConfigTest.java
  repository/src/test/java/org/alfresco/transform/client/registry/TransformServiceRegistryConfigTest.java
  repository/src/test/resources/alfresco/transform-service-config-pipeline-test.json
  repository/src/test/resources/alfresco/transform-service-config-test.json
Labels: PR: unreviewed

#675 ACS-1833 - Test requestContentDirectUrl for Versions Renditions
  remote-api/src/test/java/org/alfresco/rest/api/tests/NodeApiTest.java
Labels: PR: reviewed-approved

#672 Feature/acs 1787 endpoint for deleted nodes
  remote-api/src/main/java/org/alfresco/rest/api/DeletedNodes.java
  remote-api/src/main/java/org/alfresco/rest/api/impl/DeletedNodesImpl.java
  remote-api/src/main/java/org/alfresco/rest/api/trashcan/TrashcanEntityResource.java
  remote-api/src/main/resources/alfresco/public-rest-context.xml
Labels: PR: reviewed-approved

#674 end to end tests for APPS-1004 and APPS-1005
  amps/ags/rm-automation/rm-automation-community-rest-api/src/main/java/org/alfresco/rest/rm/community/model/record/RecordProperties.java
  amps/ags/rm-automation/rm-automation-community-rest-api/src/main/java/org/alfresco/rest/rm/community/model/recordcategory/RecordCategoryChildProperties.java
  amps/ags/rm-automation/rm-automation-community-rest-api/src/test/java/org/alfresco/rest/rm/community/recordcategories/MoveRecCategoriesWithRSTests.java
Labels: PR: unreviewed

#677 ACS-566 Fix Poms
  pom.xml
Labels: PR: reviewed-approved

#680 Feature/acs 1904 fix node ref vs content url
  data-model/src/main/java/org/alfresco/repo/content/ContentStore.java
  repository/src/main/java/org/alfresco/repo/content/ContentServiceImpl.java
  repository/src/main/java/org/alfresco/repo/content/caching/CachingContentStore.java
  repository/src/main/java/org/alfresco/repo/content/replication/AggregatingContentStore.java
  repository/src/main/java/org/alfresco/service/cmr/repository/ContentService.java
  repository/src/test/java/org/alfresco/repo/content/caching/CachingContentStoreTest.java
  repository/src/test/java/org/alfresco/repo/content/replication/AggregatingContentStoreTest.java
Labels: PR: reviewed-approved

#685 PRODSEC-5480 - Bump jsoup version from 1.13.1 to 1.14.2
  pom.xml
Labels: PR: unreviewed

#686 Feature/acs 1834 test dau for deleted nodes
  remote-api/src/test/java/org/alfresco/rest/DeletedNodesTest.java
  remote-api/src/test/java/org/alfresco/rest/api/tests/AbstractBaseApiTest.java
Labels: PR: reviewed-approved
