Repository Alfresco/alfresco-community-repo, pull requests merged in 2021-02, with the labels that each got.

#263 MNT-14308: CMIS - optionally request rendition(s) when uploading docs
  repository/src/main/java/org/alfresco/opencmis/AlfrescoCmisServiceFactory.java
  repository/src/main/java/org/alfresco/opencmis/AlfrescoCmisServiceImpl.java
  repository/src/main/resources/alfresco/opencmis-context.xml
  repository/src/main/resources/alfresco/repository.properties
Labels: PR: unreviewed

#191 Fix MNT-21991 customizable personLookupProperties for REST API
  remote-api/src/main/java/org/alfresco/rest/api/impl/NodesImpl.java
  remote-api/src/main/java/org/alfresco/rest/api/lookups/PersonPropertyLookup.java
  remote-api/src/main/resources/alfresco/public-rest-context.xml
  remote-api/src/test/java/org/alfresco/rest/api/tests/NodeApiTest.java
Labels: PR: reviewed-approved

#272 Bugfix/APPS-766 classification children job not picking rm types
  repository/src/main/java/org/alfresco/repo/search/impl/lucene/PagingLuceneResultSet.java
  repository/src/main/java/org/alfresco/repo/search/impl/querymodel/impl/db/DBQueryEngine.java
  repository/src/main/java/org/alfresco/repo/search/impl/querymodel/impl/db/NodePermissionAssessor.java
  repository/src/test/java/org/alfresco/repo/search/impl/querymodel/impl/db/DBQueryEngineTest.java
  repository/src/test/java/org/alfresco/repo/search/impl/querymodel/impl/db/NodePermissionAssessorLimitsTest.java
  repository/src/test/java/org/alfresco/repo/search/impl/querymodel/impl/db/NodePermissionAssessorPermissionsTest.java
Labels: PR: unreviewed

#261 Aspect and Type api implementation
  remote-api/src/main/java/org/alfresco/rest/api/Aspects.java
  remote-api/src/main/java/org/alfresco/rest/api/ClassDefinitionMapper.java
  remote-api/src/main/java/org/alfresco/rest/api/Types.java
  remote-api/src/main/java/org/alfresco/rest/api/aspects/AspectEntityResource.java
  remote-api/src/main/java/org/alfresco/rest/api/aspects/package-info.java
  remote-api/src/main/java/org/alfresco/rest/api/impl/AbstractClassImpl.java
  remote-api/src/main/java/org/alfresco/rest/api/impl/AspectsImpl.java
  remote-api/src/main/java/org/alfresco/rest/api/impl/ClassDefinitionMapperImpl.java
  remote-api/src/main/java/org/alfresco/rest/api/impl/CustomModelsImpl.java
  remote-api/src/main/java/org/alfresco/rest/api/impl/NodesImpl.java
  remote-api/src/main/java/org/alfresco/rest/api/impl/TypesImpl.java
  remote-api/src/main/java/org/alfresco/rest/api/model/AbstractClass.java
  remote-api/src/main/java/org/alfresco/rest/api/model/AbstractCustomClass.java
  remote-api/src/main/java/org/alfresco/rest/api/model/Aspect.java
  remote-api/src/main/java/org/alfresco/rest/api/model/ClassDefinition.java
  remote-api/src/main/java/org/alfresco/rest/api/model/ConstraintDefinition.java
  remote-api/src/main/java/org/alfresco/rest/api/model/CustomAspect.java
  remote-api/src/main/java/org/alfresco/rest/api/model/CustomType.java
  remote-api/src/main/java/org/alfresco/rest/api/model/Node.java
  remote-api/src/main/java/org/alfresco/rest/api/model/PropertyDefinition.java
  remote-api/src/main/java/org/alfresco/rest/api/model/Type.java
  remote-api/src/main/java/org/alfresco/rest/api/types/TypeEntityResource.java
  remote-api/src/main/java/org/alfresco/rest/api/types/package-info.java
  remote-api/src/main/resources/alfresco/public-rest-context.xml
  remote-api/src/test/java/org/alfresco/rest/api/tests/BaseCustomModelApiTest.java
  remote-api/src/test/java/org/alfresco/rest/api/tests/NodeApiTest.java
  remote-api/src/test/java/org/alfresco/rest/api/tests/TestAspects.java
  remote-api/src/test/java/org/alfresco/rest/api/tests/TestTypes.java
  remote-api/src/test/java/org/alfresco/rest/api/tests/client/PublicApiClient.java
  remote-api/src/test/java/org/alfresco/rest/api/tests/client/data/Aspect.java
  remote-api/src/test/java/org/alfresco/rest/api/tests/client/data/Node.java
  remote-api/src/test/java/org/alfresco/rest/api/tests/client/data/Type.java
  remote-api/src/test/resources/models/mycompany-model.xml
  remote-api/src/test/resources/models/test-scan.xml
  remote-api/src/test/resources/rest-api-test-context.xml
Labels: PR: partially-approved

#274 ACS-1215 Update JMS/ActiveMQ configuration after the Camel 3.7 upgrade
  pom.xml
  repository/pom.xml
  repository/src/main/resources/alfresco/subsystems/Messaging/default/activemq/activemq.xml
  repository/src/main/resources/alfresco/subsystems/Messaging/default/activemq/credentials.properties
  repository/src/main/resources/alfresco/subsystems/Messaging/default/messaging-context.xml
  repository/src/main/resources/alfresco/subsystems/Messaging/default/messaging.properties
Labels: PR: partially-approved

#222 [REPO-5317] TAS REPO-5184 and REPO-5185
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/sites/groups/AddSiteGroupTests.java
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/sites/groups/GetSiteGroupTests.java
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/sites/groups/GetSiteGroupsTests.java
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/sites/groups/RemoveSiteGroupTests.java
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/sites/groups/UpdateSiteGroupTests.java
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/sites/members/GetSiteMembersTests.java
Labels: PR: unreviewed

#275 MNT-22135 Filter policy to only run on admin auth - Unit test
  repository/src/test/java/org/alfresco/repo/security/authority/AuthorityServiceTest.java
Labels: PR: reviewed-approved

#278 LOC-282 - FIX pending languages (Czech, Polish and Danish) plus FR am…
  remote-api/src/main/resources/alfresco/templates/webscripts/org/alfresco/repository/admin/admin-communitysummary.get_da.properties
  repository/src/main/resources/alfresco/messages/action-config_pl.properties
  repository/src/main/resources/alfresco/messages/activiti-engine-messages_cs.properties
  repository/src/main/resources/alfresco/messages/activiti-engine-messages_da.properties
  repository/src/main/resources/alfresco/messages/authentication_cs.properties
  repository/src/main/resources/alfresco/messages/bootstrap-messages_cs.properties
  repository/src/main/resources/alfresco/messages/bootstrap-messages_da.properties
  repository/src/main/resources/alfresco/messages/bpm-messages_cs.properties
  repository/src/main/resources/alfresco/messages/content-filter-languages_pl.properties
  repository/src/main/resources/alfresco/messages/content-model_cs.properties
  repository/src/main/resources/alfresco/messages/content-model_da.properties
  repository/src/main/resources/alfresco/messages/custommodel-service_cs.properties
  repository/src/main/resources/alfresco/messages/email-service_cs.properties
  repository/src/main/resources/alfresco/messages/quickshare-service_cs.properties
  repository/src/main/resources/alfresco/messages/replication_cs.properties
  repository/src/main/resources/alfresco/messages/repoadmin-service_cs.properties
  repository/src/main/resources/alfresco/messages/system-messages_cs.properties
  repository/src/main/resources/alfresco/messages/system-messages_da.properties
  repository/src/main/resources/alfresco/messages/templates-messages_cs.properties
  repository/src/main/resources/alfresco/messages/templates-messages_da.properties
  repository/src/main/resources/alfresco/messages/templates-messages_fr.properties
  repository/src/main/resources/alfresco/messages/templates-messages_pl.properties
  repository/src/main/resources/alfresco/messages/transfer-service_cs.properties
  repository/src/main/resources/alfresco/workflow/invitation-moderated-workflow-messages_cs.properties
  repository/src/main/resources/alfresco/workflow/invitation-nominated-workflow-messages_cs.properties
  repository/src/main/resources/alfresco/workflow/invitation-nominated-workflow-messages_da.properties
  repository/src/main/resources/alfresco/workflow/workflow-messages_da.properties
Labels: PR: unreviewed

#279 [REPO-5568] Owner permissions not evaluated in enterprise code
  repository/src/main/java/org/alfresco/repo/search/impl/querymodel/impl/db/DBQueryEngine.java
  repository/src/test/java/org/alfresco/repo/search/impl/querymodel/impl/db/DBQueryEngineTest.java
  repository/src/test/java/org/alfresco/repo/search/impl/querymodel/impl/db/NodePermissionAssessorPermissionsTest.java
Labels: PR: reviewed-approved

#281 MNT-22135 Filter policy to only run on admin auth - Unit test (#275)
  repository/src/test/java/org/alfresco/repo/security/authority/AuthorityServiceTest.java
Labels: PR: unreviewed

#283 MNT-14308: CMIS - optionally request rendition(s) when uploading docs - part 2
  remote-api/src/main/resources/alfresco/public-rest-context.xml
  repository/src/main/java/org/alfresco/opencmis/AlfrescoCmisServiceFactory.java
Labels: PR: partially-approved

#284 MNT-21694 500 error on new logo upload with Legacy transforms
  repository/src/main/java/org/alfresco/repo/rendition2/TransformationOptionsConverter.java
  repository/src/test/java/org/alfresco/repo/rendition2/TransformationOptionsConverterTest.java
Labels: PR: reviewed-approved

#285 [REPO-5440] show model in the aspect/type api
  remote-api/src/main/java/org/alfresco/rest/api/model/AbstractClass.java
  remote-api/src/main/java/org/alfresco/rest/api/model/Aspect.java
  remote-api/src/main/java/org/alfresco/rest/api/model/Model.java
  remote-api/src/main/java/org/alfresco/rest/api/model/Type.java
  remote-api/src/test/java/org/alfresco/rest/api/tests/BaseModelApiTest.java
  remote-api/src/test/java/org/alfresco/rest/api/tests/TestAspects.java
  remote-api/src/test/java/org/alfresco/rest/api/tests/TestTypes.java
  remote-api/src/test/java/org/alfresco/rest/api/tests/client/data/Aspect.java
  remote-api/src/test/java/org/alfresco/rest/api/tests/client/data/Type.java
Labels: PR: partially-approved

#292 ACS-1185 Update activemq image to 5.16.1
  .travis.yml
  packaging/tests/environment/.env
Labels: PR: partially-approved

#294 bump of gdrive and aos
  pom.xml
Labels: PR: partially-approved

#296 Feature/apps 703 bumps gdrive 3.2.1-A2
  pom.xml
Labels: PR: partially-approved

#297 ATS-862 2.3.8 T-Engines
  .travis.yml
  packaging/tests/environment/.env
  pom.xml
Labels: PR: unreviewed

#289 ACS-1264: Content Model changes dynamically updated to node caches across a cluster deadlock
  core/src/main/java/org/alfresco/util/cache/AbstractAsynchronouslyRefreshedCache.java
  repository/src/main/java/org/alfresco/repo/cache/DefaultSimpleCache.java
  repository/src/main/resources/alfresco/tx-cache-context.xml
  repository/src/test/java/org/alfresco/repo/cache/DefaultSimpleCacheTest.java
Labels: PR: reviewed-approved

#286 [SEARCH-2677] Extract SearchEngineResultSet and SearchEngineResultMetadata interfaces
  remote-api/src/main/java/org/alfresco/rest/api/search/impl/ResultMapper.java
  remote-api/src/test/java/org/alfresco/rest/api/search/ResultMapperTests.java
  repository/src/main/java/org/alfresco/repo/search/SearchEngineResultMetadata.java
  repository/src/main/java/org/alfresco/repo/search/SearchEngineResultSet.java
  repository/src/main/java/org/alfresco/repo/search/impl/solr/SolrJSONResultSet.java
  repository/src/main/java/org/alfresco/repo/search/impl/solr/SolrJsonProcessor.java
  repository/src/main/java/org/alfresco/repo/search/impl/solr/SolrQueryHTTPClient.java
  repository/src/main/java/org/alfresco/repo/search/impl/solr/SolrSQLHttpClient.java
  repository/src/main/java/org/alfresco/repo/search/impl/solr/SolrSQLJSONResultSet.java
  repository/src/main/java/org/alfresco/repo/search/impl/solr/SolrStatsResult.java
  repository/src/test/java/org/alfresco/repo/search/impl/solr/SolrSQLJSONResultMetadataSetTest.java
Labels: PR: reviewed-approved

#295 ACS-1253 Enable Camel JMX management
  packaging/tests/environment/docker-compose-minimal+transforms.yml
  packaging/tests/environment/docker-compose-minimal.yml
  pom.xml
  repository/pom.xml
  repository/src/main/resources/alfresco/subsystems/Messaging/default/messaging-context.xml
  repository/src/main/resources/alfresco/subsystems/Messaging/default/messaging.properties
Labels: PR: partially-approved

#302 MNT-21671 : Download as zip REST api does not include custom folders …
  repository/src/main/java/org/alfresco/repo/download/CreateDownloadArchiveAction.java
  repository/src/main/java/org/alfresco/repo/download/ZipDownloadExporter.java
  repository/src/main/resources/alfresco/download-services-context.xml
  repository/src/test/java/org/alfresco/repo/download/DownloadServiceIntegrationTest.java
Labels: PR: reviewed-approved

#301 [REPO-5552] more filtering capablities for aspect/type api
  remote-api/src/main/java/org/alfresco/rest/api/Aspects.java
  remote-api/src/main/java/org/alfresco/rest/api/Types.java
  remote-api/src/main/java/org/alfresco/rest/api/aspects/AspectEntityResource.java
  remote-api/src/main/java/org/alfresco/rest/api/impl/AbstractClassImpl.java
  remote-api/src/main/java/org/alfresco/rest/api/impl/AspectsImpl.java
  remote-api/src/main/java/org/alfresco/rest/api/impl/TypesImpl.java
  remote-api/src/main/java/org/alfresco/rest/api/model/AbstractClass.java
  remote-api/src/main/java/org/alfresco/rest/api/model/Aspect.java
  remote-api/src/main/java/org/alfresco/rest/api/model/Association.java
  remote-api/src/main/java/org/alfresco/rest/api/model/AssociationSource.java
  remote-api/src/main/java/org/alfresco/rest/api/model/Type.java
  remote-api/src/test/java/org/alfresco/rest/api/tests/BaseModelApiTest.java
  remote-api/src/test/java/org/alfresco/rest/api/tests/TestAspects.java
  remote-api/src/test/java/org/alfresco/rest/api/tests/TestTypes.java
  remote-api/src/test/java/org/alfresco/rest/api/tests/client/data/Aspect.java
  remote-api/src/test/java/org/alfresco/rest/api/tests/client/data/Type.java
  remote-api/src/test/resources/models/mycompany-model.xml
  remote-api/src/test/resources/models/test-api-model.xml
  remote-api/src/test/resources/models/test-scan.xml
  remote-api/src/test/resources/rest-api-test-context.xml
Labels: PR: partially-approved

#293 REPO-5571 : Change the tempFileCleanerTrigger to work at scale
  core/src/main/java/org/alfresco/util/TempFileProvider.java
  repository/src/main/resources/alfresco/repository.properties
  repository/src/main/resources/alfresco/scheduled-jobs-context.xml
Labels: PR: partially-approved

#308 REPO-5376 Query Accelerator Remove all temporary code
  remote-api/src/main/java/org/alfresco/rest/api/search/SearchApiWebscript.java
  remote-api/src/main/resources/alfresco/project-remote-api.properties
  remote-api/src/main/resources/alfresco/public-rest-context.xml
  repository/src/main/java/org/alfresco/repo/domain/node/ibatis/NodeDAOImpl.java
  repository/src/main/java/org/alfresco/repo/search/impl/querymodel/impl/db/DBQueryEngine.java
  repository/src/main/java/org/alfresco/repo/search/impl/querymodel/impl/db/DBStats.java
  repository/src/main/java/org/alfresco/repo/search/impl/querymodel/impl/db/NodePermissionAssessor.java
  repository/src/main/java/org/alfresco/repo/search/impl/querymodel/impl/db/SingleTaskRestartableWatch.java
  repository/src/main/resources/alfresco/subsystems/Search/common-search-context.xml
  repository/src/test/java/org/alfresco/repo/search/impl/querymodel/impl/db/DBQueryEngineTest.java
  repository/src/test/java/org/alfresco/repo/search/impl/querymodel/impl/db/NodePermissionAssessorPermissionsTest.java
Labels: PR: reviewed-approved

#309 fix/APPS-update-webscripts-version to 8.17
  pom.xml
Labels: PR: partially-approved

#310 REPO-5571 : Add tempFileCleanerTrigger configurations to be able to limit the job duration/quantity
  core/src/main/java/org/alfresco/util/TempFileProvider.java
Labels: PR: unreviewed

#312 ACS-1183 ACS 7 Stacks: PostgreSQL
  .gitbugtraq
  .travis.yml
  packaging/tests/environment/.env
Labels: PR: unreviewed

#311 REPO-5571
  core/src/main/java/org/alfresco/util/TempFileProvider.java
Labels: PR: unreviewed

#315 APPS-692: after properties is removed by direct acces. Created a copy.
  repository/src/main/java/org/alfresco/repo/event2/EventConsolidator.java
Labels: PR: reviewed-approved

#314 ACS-1253 Remove ignored JMX namespace argument on Camel context
  repository/src/main/resources/alfresco/subsystems/Messaging/default/messaging-context.xml
Labels: PR: reviewed-approved

#313 [REPO-5552] Fix get Aspect/Type api random error
  remote-api/src/main/java/org/alfresco/rest/api/impl/AspectsImpl.java
  remote-api/src/main/java/org/alfresco/rest/api/impl/TypesImpl.java
Labels: PR: partially-approved

#316 Update the ACS build scripts
  scripts/travis/build_functions.sh
Labels: PR: reviewed-approved
