Repository Alfresco/alfresco-community-repo, pull requests merged in 2021-11, with the labels that each got.

#785 PRODSEC-4343 Build the MMT tool in alfreaco-community-repo so it picks up the latest libraries
  .gitignore
  mmt/pom.xml
  mmt/src/main/resources/LICENSE
  packaging/docker-alfresco/pom.xml
  pom.xml
  repository/pom.xml
Labels: PR: reviewed-approved

#793 ACS-2238 Added missing BatchProcessWorkProvider implementations
  repository/src/main/java/org/alfresco/repo/admin/patch/impl/SurfConfigFolderPatch.java
  repository/src/main/java/org/alfresco/repo/batch/BatchProcessor.java
Labels: PR: reviewed-approved

#797 ACS-1795: Bump tas-utility to 3.0.47 and tas-restapi to 1.65.
  pom.xml
Labels: PR: unreviewed

#796 ACS-1998 Enhance the transform config
  .travis.yml
  amps/ags/rm-community/rm-community-repo/.env
  packaging/tests/environment/.env
  pom.xml
  repository/src/main/java/org/alfresco/repo/content/transform/LocalPassThroughTransform.java
  repository/src/main/java/org/alfresco/repo/content/transform/LocalTransformServiceRegistry.java
  repository/src/main/java/org/alfresco/transform/client/registry/CombinedConfig.java
  repository/src/test/java/org/alfresco/transform/client/registry/LocalTransformServiceRegistryConfigTest.java
Labels: PR: unreviewed

#803 [PRODSEC-5795] Bump surf-webscripts to 8.25
  pom.xml
Labels: PR: reviewed-approved

#804 [PRODSEC-5795] Bump surf-webscripts to 8.25 (#803)
  pom.xml
Labels: PR: unreviewed

#805 MNT-18700 - Dynamic Message bundles do not deploy/reload automatically
  repository/src/main/java/org/alfresco/repo/dictionary/DictionaryRepositoryBootstrap.java
  repository/src/test/java/org/alfresco/repo/admin/RepoAdminServiceImplTest.java
  repository/src/test/java/org/alfresco/repo/dictionary/DictionaryRepositoryBootstrapTest.java
  repository/src/test/resources/alfresco/extension/messages/mycustommessages.properties
  repository/src/test/resources/alfresco/extension/messages/mycustommessages_de_DE.properties
  repository/src/test/resources/alfresco/extension/messages/mycustommessages_fr_FR.properties
Labels: PR: reviewed-approved

#802 ACS-2222 Add ArchivedIOException
  data-model/src/main/java/org/alfresco/service/cmr/repository/ArchivedIOException.java
  remote-api/src/main/java/org/alfresco/repo/web/scripts/content/ContentStreamer.java
  remote-api/src/main/java/org/alfresco/rest/framework/core/exceptions/ApiException.java
  remote-api/src/main/java/org/alfresco/rest/framework/core/exceptions/ArchivedContentException.java
  remote-api/src/main/java/org/alfresco/rest/framework/webscripts/AbstractResourceWebScript.java
  remote-api/src/main/resources/alfresco/public-rest-context.xml
  repository/src/main/java/org/alfresco/repo/content/AbstractContentReader.java
Labels: PR: unreviewed

#810 MNT-18700 - Dynamic Message bundles do not deploy/reload automaticall…
  repository/src/main/java/org/alfresco/repo/dictionary/DictionaryRepositoryBootstrap.java
  repository/src/test/java/org/alfresco/repo/admin/RepoAdminServiceImplTest.java
  repository/src/test/java/org/alfresco/repo/dictionary/DictionaryRepositoryBootstrapTest.java
  repository/src/test/resources/alfresco/extension/messages/mycustommessages.properties
  repository/src/test/resources/alfresco/extension/messages/mycustommessages_de_DE.properties
  repository/src/test/resources/alfresco/extension/messages/mycustommessages_fr_FR.properties
Labels: PR: unreviewed

#806 ACS-2270 Read T-Engine config in alphabetical order
  repository/src/main/java/org/alfresco/repo/content/transform/LocalTransformServiceRegistry.java
  repository/src/test/java/org/alfresco/repo/content/transform/LocalTransformServiceRegistryTest.java
  repository/src/test/java/org/alfresco/repo/content/transform/TransformerConfigTestSuite.java
Labels: PR: reviewed-approved

#812 ACS-222 Add missing ArchivedIOException throw
  repository/src/main/java/org/alfresco/repo/content/AbstractContentReader.java
Labels: PR: reviewed-approved

#814 [MNT-22680] Bump surf-webscripts to 8.26
  pom.xml
Labels: PR: unreviewed

#815 [MNT-22680] Bump surf-webscripts to 8.26 (#814)
  pom.xml
Labels: PR: unreviewed

#752 [MNT-21953] [MNT-22491] Clear rendition content data on content change. Prevent rendition from having contentHashCode without content
  repository/src/main/java/org/alfresco/repo/rendition/RenditionServiceImpl.java
  repository/src/main/java/org/alfresco/repo/rendition2/RenditionService2Impl.java
  repository/src/main/java/org/alfresco/repo/thumbnail/ThumbnailServiceImpl.java
  repository/src/test/java/org/alfresco/repo/rendition2/AbstractRenditionIntegrationTest.java
  repository/src/test/java/org/alfresco/repo/rendition2/RenditionService2IntegrationTest.java
Labels: PR: unreviewed

#819 [MNT-21953] [MNT-22491] Clear rendition content data on content chang…
  repository/src/main/java/org/alfresco/repo/rendition/RenditionServiceImpl.java
  repository/src/main/java/org/alfresco/repo/rendition2/RenditionService2Impl.java
  repository/src/main/java/org/alfresco/repo/thumbnail/ThumbnailServiceImpl.java
  repository/src/test/java/org/alfresco/repo/rendition2/AbstractRenditionIntegrationTest.java
  repository/src/test/java/org/alfresco/repo/rendition2/RenditionService2IntegrationTest.java
Labels: PR: unreviewed

#818 MNT-22136: WebDAV PROPFIND returns 302 instead of 404 (for docker image only)
  packaging/tests/tas-webdav/src/test/java/org/alfresco/webdav/UnlockFileTests.java
  packaging/war/src/main/webapp/error.jsp
Labels: PR: partially-approved

#696 ADF-5234: [BE] Viewer - the Mimetype property should be changed when a new type of file is uploaded
  data-model/src/main/java/org/alfresco/repo/content/MimetypeMap.java
  data-model/src/main/resources/alfresco/mimetype/mimetype-map.xml
  data-model/src/test/java/org/alfresco/repo/content/MimetypeMapTest.java
  repository/src/test/java/org/alfresco/repo/content/MimetypeMapContentTest.java
  repository/src/test/resources/quick/quick.icns
Labels: PR: partially-approved
