Repository Alfresco/alfresco-community-repo, pull requests merged in 2021-07, with the labels that each got.

#573 ACS-1734 Remove libreofficeToPdf + libreofficeToPdfBoxViaPdf
  repository/src/main/resources/alfresco/transforms/0100-basePipelines.json
Labels: PR: partially-approved

#576 Use LF for Dockerfile(s) and .sh scripts (.gitattributes) [skip ci]
  .gitattributes
Labels: PR: partially-approved

#577 ACS-1734 Remove libreofficeToPdf + libreofficeToPdfBoxViaPdf
  repository/src/main/resources/alfresco/transforms/0100-basePipelines.json
Labels: PR: partially-approved

#578 ACS-1734 Remove libreofficeToPdf + libreofficeToPdfBoxViaPdf
  repository/src/main/resources/alfresco/transforms/0100-basePipelines.json
Labels: PR: partially-approved

#586 [ACS-1776] Add missing pipeline outlookMsgToLibreofficeViaText
  repository/src/main/resources/alfresco/transforms/0100-basePipelines.json
Labels: PR: unreviewed

#588 SEARCH-2878 Update the supported for SearchService to 2.0.2-RC2
  packaging/tests/environment/.env
Labels: PR: reviewed-approved

#522 ACS-1585: storage classes e2e tests
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/nodes/NodesTests.java
  repository/src/test/java/org/alfresco/AppContext03TestSuite.java
  repository/src/test/java/org/alfresco/repo/content/StorageClassTest.java
Labels: PR: partially-approved

#587 SEARCH-2878 Update the supported for SearchService
  packaging/tests/environment/.env
Labels: PR: unreviewed

#598 MNT-22481 - Unable to Create Custom Metadata
  amps/ags/rm-community/rm-community-repo/source/java/org/alfresco/module/org_alfresco_module_rm/script/CustomPropertyDefinitionPost.java
Labels: PR: unreviewed

#596 PRODSEC-4422 - Scripts not in Data Dictionary can be executed
  amps/ags/rm-community/rm-community-repo/test/java/org/alfresco/module/org_alfresco_module_rm/test/legacy/action/ExecuteScriptActionTest.java
  amps/ags/rm-community/rm-community-repo/test/java/org/alfresco/module/org_alfresco_module_rm/test/util/BaseRMTestCase.java
  repository/src/main/java/org/alfresco/repo/action/executer/ScriptActionExecuter.java
  repository/src/test/java/org/alfresco/repo/action/ActionServiceImpl2Test.java
  repository/src/test/java/org/alfresco/repo/action/ActionServiceImplTest.java
Labels: PR: unreviewed

#602 PRODENG-67/PRODENG-69 ACS 7.1 Supported Platforms: PostgreSQL 13.3, 12.7, 11.12 / MariaDB 10.6
  .travis.yml
  amps/ags/rm-community/rm-community-repo/.env
  amps/ags/rm-community/rm-community-repo/pom.xml
  packaging/tests/environment/.env
Labels: PR: reviewed-approved

#603 MNT-21534: Alfresco does not pull correct name for several scheduled jobs
  repository/src/main/resources/alfresco/scheduled-jobs-context.xml
  repository/src/main/resources/alfresco/subsystems/Search/solr6/solr-backup-context.xml
Labels: PR: reviewed-approved

#590 RM-6941 Changes related to retain frozen Records
  amps/ags/rm-community/rm-community-repo/config/alfresco/module/org_alfresco_module_rm/rm-job-context.xml
  amps/ags/rm-community/rm-community-repo/config/alfresco/module/org_alfresco_module_rm/rm-service-context.xml
  amps/ags/rm-community/rm-community-repo/source/java/org/alfresco/module/org_alfresco_module_rm/disposition/DispositionServiceImpl.java
  amps/ags/rm-community/rm-community-repo/source/java/org/alfresco/module/org_alfresco_module_rm/job/DispositionLifecycleJobExecuter.java
  amps/ags/rm-community/rm-community-repo/source/java/org/alfresco/module/org_alfresco_module_rm/job/RecordsManagementJobExecuter.java
  amps/ags/rm-community/rm-community-repo/unit-test/java/org/alfresco/module/org_alfresco_module_rm/job/DispositionLifecycleJobExecuterUnitTest.java
Labels: PR: partially-approved

#607 MNT-21611 disable html transformation
  repository/src/main/resources/alfresco/transforms/0100-basePipelines.json
Labels: PR: unreviewed

#610 MNT-21611 Removed HTML transformation pipelines (with LibreOffice)
  repository/src/main/resources/alfresco/transforms/0100-basePipelines.json
Labels: PR: reviewed-approved

#605 MNT-21611 - Disable HTML transformation - use plain text instead
  repository/src/main/resources/alfresco/subsystems/Transformers/default/transformers.properties
Labels: PR: unreviewed

#606 MNT-21611 - Disable HTML transformation - use plain text instead
  repository/src/main/resources/alfresco/subsystems/Transformers/default/transformers.properties
Labels: PR: unreviewed

#604 ATS-952: bump T-engines to version 2.5.2
  .travis.yml
  amps/ags/rm-community/rm-community-repo/.env
  packaging/tests/environment/.env
Labels: PR: reviewed-approved

#612 PRODSEC-4422 ScriptActionExecuter fix
  repository/src/main/java/org/alfresco/repo/action/executer/ScriptActionExecuter.java
  repository/src/test/java/org/alfresco/repo/action/ActionServiceImpl2Test.java
  repository/src/test/java/org/alfresco/repo/action/ActionServiceImplTest.java
Labels: PR: unreviewed

#614 PRODSEC-4422 - ScriptActionExecuter fix
  repository/src/main/java/org/alfresco/repo/action/executer/ScriptActionExecuter.java
  repository/src/test/java/org/alfresco/repo/action/ActionServiceImpl2Test.java
  repository/src/test/java/org/alfresco/repo/action/ActionServiceImplTest.java
Labels: PR: unreviewed

#616 PRODSEC-4422 - ScriptActionExecuter fix
  repository/src/main/java/org/alfresco/repo/action/executer/ScriptActionExecuter.java
  repository/src/test/java/org/alfresco/repo/action/ActionServiceImpl2Test.java
  repository/src/test/java/org/alfresco/repo/action/ActionServiceImplTest.java
Labels: PR: unreviewed

#617 PRODSEC-4422 - ScriptActionExecuter
  repository/src/main/java/org/alfresco/repo/action/executer/ScriptActionExecuter.java
  repository/src/test/java/org/alfresco/repo/action/ActionServiceImpl2Test.java
  repository/src/test/java/org/alfresco/repo/action/ActionServiceImplTest.java
Labels: PR: unreviewed

#615 PRODSEC-4422 - ScriptActionExecuter fix
  repository/src/main/java/org/alfresco/repo/action/executer/ScriptActionExecuter.java
  repository/src/test/java/org/alfresco/repo/action/ActionServiceImpl2Test.java
  repository/src/test/java/org/alfresco/repo/action/ActionServiceImplTest.java
Labels: PR: unreviewed

#620 PRODSEC-4421 - Bump surf-webscripts to 8.22
  pom.xml
Labels: PR: reviewed-approved

#621 PRODSEC-4421 - Bump surf-webscripts to 7.22
  pom.xml
Labels: PR: reviewed-approved

#622 PRODSEC-4421 - Bump surf-webscripts to 7.22
  pom.xml
Labels: PR: reviewed-approved

#625 PRODSEC-4421 - Bump surf-webscripts to 6.25
  pom.xml
Labels: PR: reviewed-approved

#626 PRODSEC-4421 - Bump surf-webscripts to 8.22
  pom.xml
Labels: PR: reviewed-approved

#627 [REPO-4514] Removed dom4j dependency
  core/pom.xml
Labels: PR: reviewed-approved
