Repository Alfresco/alfresco-community-repo, pull requests merged in 2021-03, with the labels that each got.

#320 REPO-5571 : Add tempFileCleanerTrigger configurations to be able to limit the job duration/quantity
  core/src/main/java/org/alfresco/util/TempFileProvider.java
Labels: PR: unreviewed

#319 [REPO-5552] TAS aspect/type api
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/models/aspects/GetAspectTests.java
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/models/aspects/GetAspectsTests.java
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/models/types/GetTypeTests.java
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/models/types/GetTypesTests.java
  packaging/tests/tas-restapi/src/test/resources/test-suites/part3-suite.xml
  pom.xml
Labels: PR: partially-approved

#322 Upgrade TAS restapi
  pom.xml
Labels: PR: reviewed-approved

#323 MNT-22184 Add security header for admin console
  packaging/war/src/main/resources/alfresco/web-client-security-config.xml
  packaging/war/src/main/webapp/WEB-INF/web.xml
Labels: PR: partially-approved

#334 ACS-1217 Additional option for SOLR to authenticate with a shared secret
  packaging/war/src/main/resources/alfresco/web-client-application-context.xml
  remote-api/src/main/java/org/alfresco/repo/web/scripts/solr/SOLRAuthenticationFilter.java
  remote-api/src/main/resources/alfresco/web-client-application-context.xml
  remote-api/src/test/java/org/alfresco/AppContextExtraTestSuite.java
  remote-api/src/test/java/org/alfresco/repo/web/scripts/solr/SOLRAuthenticationFilterTest.java
  repository/src/main/resources/alfresco/repository.properties
Labels: PR: reviewed-approved

#333 Update webscript version
  pom.xml
Labels: PR: reviewed-approved

#335 ACS-1071 revision not set in version.properties
  packaging/war/pom.xml
Labels: PR: unreviewed

#332 ACS-1201: Model integrity violation saving properties
  repository/src/main/java/org/alfresco/repo/forms/processor/node/ContentModelFormProcessor.java
Labels: PR: reviewed-approved

#336 ACS-1180 ACS 7 Stacks: MySQL 8
  .travis.yml
  repository/src/main/java/org/alfresco/util/schemacomp/ExportDb.java
  repository/src/main/resources/alfresco/dbscripts/create/org.alfresco.repo.domain.dialect.MySQLInnoDBDialect/Schema-Reference-ACT.xml
  repository/src/main/resources/alfresco/dbscripts/create/org.alfresco.repo.domain.dialect.MySQLInnoDBDialect/Schema-Reference-ALF.xml
Labels: PR: unreviewed

#338 ACS-855 : Long running patch in ACS 7.0.0.A2 upgrade
  repository/src/main/resources/alfresco/dbscripts/create/org.alfresco.repo.domain.dialect.MySQLInnoDBDialect/AlfrescoCreate-RepoTables.sql
  repository/src/main/resources/alfresco/dbscripts/create/org.alfresco.repo.domain.dialect.MySQLInnoDBDialect/Schema-Reference-ALF.xml
  repository/src/main/resources/alfresco/dbscripts/create/org.alfresco.repo.domain.dialect.PostgreSQLDialect/AlfrescoCreate-RepoTables.sql
  repository/src/main/resources/alfresco/dbscripts/create/org.alfresco.repo.domain.dialect.PostgreSQLDialect/Schema-Reference-ALF.xml
  repository/src/main/resources/alfresco/dbscripts/db-schema-context.xml
  repository/src/main/resources/alfresco/dbscripts/upgrade/6.3/org.alfresco.repo.domain.dialect.MySQLInnoDBDialect/remove-alf_server-table.sql
  repository/src/main/resources/alfresco/dbscripts/upgrade/6.3/org.alfresco.repo.domain.dialect.PostgreSQLDialect/remove-alf_server-table.sql
  repository/src/main/resources/alfresco/messages/patch-service.properties
  repository/src/main/resources/alfresco/patch/patch-services-context.xml
Labels: PR: partially-approved

#339 feature/APPS-update-dependencies:Removed suffix google-drive and aos versions from pom
  pom.xml
Labels: PR: partially-approved

#341 ATS-876 Update to T-Engine
  .travis.yml
  packaging/tests/environment/.env
Labels: PR: reviewed-approved

#342 Fixed typo for CPUs string in SPANISH
  remote-api/src/main/resources/alfresco/templates/webscripts/org/alfresco/repository/admin/admin-communitysummary.get_es.properties
Labels: PR: unreviewed

#344 MNT-21898 Unexpected ACLs when job runs Fix
  repository/src/main/java/org/alfresco/repo/domain/node/AbstractNodeDAOImpl.java
  repository/src/main/java/org/alfresco/repo/domain/permissions/ADMAccessControlListDAO.java
  repository/src/main/java/org/alfresco/repo/domain/permissions/AccessControlListDAO.java
  repository/src/main/java/org/alfresco/repo/domain/permissions/FixedAclUpdater.java
  repository/src/main/resources/alfresco/public-services-security-context.xml
  repository/src/main/resources/alfresco/repository.properties
  repository/src/test/java/org/alfresco/repo/domain/permissions/FixedAclUpdaterTest.java
Labels: PR: reviewed-approved

#345 [MNT-21847] - Aync permissions fail when new nodes are created (#1188)
  repository/src/main/java/org/alfresco/repo/domain/permissions/ADMAccessControlListDAO.java
  repository/src/test/java/org/alfresco/repo/domain/permissions/FixedAclUpdaterTest.java
Labels: PR: unreviewed

#346 MNT-22009 - When setting permissions async, nodes with the aspect app…
  repository/src/main/java/org/alfresco/repo/domain/permissions/FixedAclUpdater.java
  repository/src/test/java/org/alfresco/repo/domain/permissions/FixedAclUpdaterTest.java
Labels: PR: unreviewed

#347 MNT-22040 Copying nodes that contain sys:pendingFixAcl aspect (#188)
  repository/src/main/java/org/alfresco/repo/domain/permissions/ADMAccessControlListDAO.java
  repository/src/main/java/org/alfresco/repo/domain/permissions/AccessControlListDAO.java
  repository/src/main/java/org/alfresco/repo/domain/permissions/FixedAclUpdater.java
  repository/src/test/java/org/alfresco/repo/domain/permissions/FixedAclUpdaterTest.java
Labels: PR: unreviewed

#348 MNT-21898 Unexpected ACLs when job runs Fix (#344)
  repository/src/main/java/org/alfresco/repo/domain/node/AbstractNodeDAOImpl.java
  repository/src/main/java/org/alfresco/repo/domain/permissions/ADMAccessControlListDAO.java
  repository/src/main/java/org/alfresco/repo/domain/permissions/AccessControlListDAO.java
  repository/src/main/java/org/alfresco/repo/domain/permissions/FixedAclUpdater.java
  repository/src/main/resources/alfresco/public-services-security-context.xml
  repository/src/main/resources/alfresco/repository.properties
  repository/src/test/java/org/alfresco/repo/domain/permissions/FixedAclUpdaterTest.java
Labels: PR: unreviewed

#350 MNT-21898 Unexpected ACLs when job runs Fix (#344)
  repository/src/main/java/org/alfresco/repo/domain/node/AbstractNodeDAOImpl.java
  repository/src/main/java/org/alfresco/repo/domain/permissions/ADMAccessControlListDAO.java
  repository/src/main/java/org/alfresco/repo/domain/permissions/AccessControlListDAO.java
  repository/src/main/java/org/alfresco/repo/domain/permissions/FixedAclUpdater.java
  repository/src/main/resources/alfresco/public-services-security-context.xml
  repository/src/main/resources/alfresco/repository.properties
  repository/src/test/java/org/alfresco/repo/domain/permissions/FixedAclUpdaterTest.java
Labels: PR: unreviewed

#351 [ACS-1291] Asynchronous mechanism to send events
  repository/src/main/java/org/alfresco/repo/event2/EventGenerator.java
  repository/src/main/resources/alfresco/events2-context.xml
  repository/src/main/resources/alfresco/repository.properties
  repository/src/test/java/org/alfresco/repo/event2/AbstractContextAwareRepoEvent.java
Labels: PR: reviewed-approved

#352 ACS-1264: Content Model changes dynamically updated to node caches ac…
  core/src/main/java/org/alfresco/util/cache/AbstractAsynchronouslyRefreshedCache.java
  repository/src/main/java/org/alfresco/repo/cache/DefaultSimpleCache.java
Labels: PR: unreviewed

#356 ACS-1252 : Add tests for the JMS/ActiveMQ/Camel configuration in *alfresco-community-repo*
  .travis.yml
  repository/src/test/java/org/alfresco/messaging/camel/CamelComponentsTest.java
  repository/src/test/java/org/alfresco/messaging/camel/CamelRoutesTest.java
  repository/src/test/resources/test-messaging-context.xml
  repository/src/test/resources/test-messaging.properties
Labels: PR: partially-approved

#359 MNT-22295 - FixedACLJob not processing all nodes due to unordered results
  repository/src/main/java/org/alfresco/ibatis/IdsEntity.java
  repository/src/main/java/org/alfresco/repo/domain/node/AbstractNodeDAOImpl.java
  repository/src/main/java/org/alfresco/repo/domain/node/NodeDAO.java
  repository/src/main/java/org/alfresco/repo/domain/node/ibatis/NodeDAOImpl.java
  repository/src/main/java/org/alfresco/repo/domain/permissions/FixedAclUpdater.java
  repository/src/main/resources/alfresco/ibatis/org.alfresco.repo.domain.dialect.Dialect/node-common-SqlMap.xml
Labels: PR: reviewed-approved

#363 MNT-22295 - FixedACLJob not processing all nodes due to unordered res…
  repository/src/main/java/org/alfresco/ibatis/IdsEntity.java
  repository/src/main/java/org/alfresco/repo/domain/node/AbstractNodeDAOImpl.java
  repository/src/main/java/org/alfresco/repo/domain/node/NodeDAO.java
  repository/src/main/java/org/alfresco/repo/domain/node/ibatis/NodeDAOImpl.java
  repository/src/main/java/org/alfresco/repo/domain/permissions/FixedAclUpdater.java
  repository/src/main/resources/alfresco/ibatis/org.alfresco.repo.domain.dialect.Dialect/node-common-SqlMap.xml
Labels: PR: unreviewed

#362 MNT-22295 - FixedACLJob not processing all nodes due to unordered res…
  repository/src/main/java/org/alfresco/ibatis/IdsEntity.java
  repository/src/main/java/org/alfresco/repo/domain/node/AbstractNodeDAOImpl.java
  repository/src/main/java/org/alfresco/repo/domain/node/NodeDAO.java
  repository/src/main/java/org/alfresco/repo/domain/node/ibatis/NodeDAOImpl.java
  repository/src/main/java/org/alfresco/repo/domain/permissions/FixedAclUpdater.java
  repository/src/main/resources/alfresco/ibatis/org.alfresco.repo.domain.dialect.Dialect/node-common-SqlMap.xml
Labels: PR: unreviewed

#357 SEARCH-2768 Add callback feature for asynchronous ACL updates.
  repository/src/main/java/org/alfresco/repo/domain/permissions/FixedAclUpdater.java
  repository/src/main/java/org/alfresco/repo/domain/permissions/FixedAclUpdaterListener.java
  repository/src/main/resources/alfresco/repository.properties
  repository/src/test/java/org/alfresco/AllUnitTestsSuite.java
  repository/src/test/java/org/alfresco/repo/domain/permissions/FixedAclUpdaterUnitTest.java
Labels: PR: unreviewed

#326 Externalize the nodeServiceCleanup CRON expression
  repository/src/main/resources/alfresco/repository.properties
  repository/src/main/resources/alfresco/scheduled-jobs-context.xml
Labels: PR: reviewed-approved
