Repository Alfresco/alfresco-community-repo, pull requests merged in 2021-01, with the labels that each got.

#227 REPO-5191 Bug: T-Engine should provide mapping rather than the repo.
  repository/src/main/java/org/alfresco/repo/content/metadata/AbstractMappingMetadataExtracter.java
  repository/src/main/java/org/alfresco/repo/content/metadata/AsynchronousExtractor.java
  repository/src/test/java/org/alfresco/repo/action/executer/AsynchronousExtractorTest.java
  repository/src/test/java/org/alfresco/repo/action/executer/ContentMetadataEmbedderTest.java
Labels: PR: reviewed-approved

#219 ACS-1043: Upgrade camel version from 2.24.2 to 2.25.3
  pom.xml
Labels: PR: unreviewed

#192 Fix MNT-21968 catch NumberFormatException on parseInt
  repository/src/main/java/org/alfresco/repo/virtual/ref/ZeroReferenceParser.java
  repository/src/test/java/org/alfresco/repo/virtual/store/VirtualStoreImplTest.java
Labels: PR: unreviewed

#144 Decrease log severity
  repository/src/main/java/org/alfresco/repo/activities/feed/FeedTaskProcessor.java
Labels: PR: reviewed-approved

#234 ACS-247 Query accelerator
  remote-api/src/main/java/org/alfresco/rest/api/search/SearchApiWebscript.java
  remote-api/src/main/resources/alfresco/project-remote-api.properties
  remote-api/src/main/resources/alfresco/public-rest-context.xml
  repository/src/main/java/org/alfresco/ibatis/SqlSessionMetricsWrapper.java
  repository/src/main/java/org/alfresco/repo/domain/node/AbstractNodeDAOImpl.java
  repository/src/main/java/org/alfresco/repo/domain/node/NodePropertyValue.java
  repository/src/main/java/org/alfresco/repo/domain/node/ibatis/NodeDAOImpl.java
  repository/src/main/java/org/alfresco/repo/search/impl/lucene/PagingLuceneResultSet.java
  repository/src/main/java/org/alfresco/repo/search/impl/querymodel/impl/db/DBQueryBuilderPredicatePartCommand.java
  repository/src/main/java/org/alfresco/repo/search/impl/querymodel/impl/db/DBQueryEngine.java
  repository/src/main/java/org/alfresco/repo/search/impl/querymodel/impl/db/DBResultSet.java
  repository/src/main/java/org/alfresco/repo/search/impl/querymodel/impl/db/DBStats.java
  repository/src/main/java/org/alfresco/repo/search/impl/querymodel/impl/db/PropertySupport.java
  repository/src/main/java/org/alfresco/repo/search/impl/querymodel/impl/db/SingleTaskRestartableWatch.java
  repository/src/main/java/org/alfresco/repo/search/impl/solr/DbCmisQueryLanguage.java
  repository/src/main/resources/alfresco/ibatis/org.alfresco.repo.domain.dialect.Dialect/metadata-query-SqlMap.xml
  repository/src/main/resources/alfresco/ibatis/org.alfresco.repo.domain.dialect.Dialect/metadata-query-common-SqlMap.xml
  repository/src/main/resources/alfresco/ibatis/org.alfresco.repo.domain.dialect.MySQLInnoDBDialect/metadata-query-SqlMap.xml
  repository/src/main/resources/alfresco/subsystems/Search/common-search-context.xml
  repository/src/test/java/org/alfresco/repo/quickshare/QuickShareServiceIntegrationTest.java
  repository/src/test/java/org/alfresco/repo/search/impl/querymodel/impl/db/DBQueryEngineTest.java
  repository/src/test/java/org/alfresco/repo/search/impl/querymodel/impl/db/NodePermissionAssessorTest.java
Labels: PR: reviewed-approved

#236 ACS-1110 replace fabric8 with docker-maven-plugin
  README.md
  packaging/docker-alfresco/pom.xml
  pom.xml
  scripts/travis/init.sh
Labels: PR: unreviewed

#235 ACS-1043 : Camel upgrade to 3.7.0
  core/src/main/java/org/alfresco/util/transaction/SpringAwareUserTransaction.java
  data-model/src/main/java/org/alfresco/util/BaseApplicationContextHelper.java
  packaging/war/pom.xml
  pom.xml
  remote-api/pom.xml
  remote-api/src/test/java/org/alfresco/repo/web/util/HttpRangeProcessorTest.java
  remote-api/src/test/java/org/alfresco/repo/webdav/GetMethodRegressionTest.java
  remote-api/src/test/java/org/alfresco/repo/webdav/MoveMethodTest.java
  remote-api/src/test/java/org/alfresco/repo/webdav/UnlockMethodTest.java
  remote-api/src/test/java/org/alfresco/repo/webdav/WebDAVHelperTest.java
  remote-api/src/test/java/org/alfresco/repo/webdav/WebDAVLockServiceImplTest.java
  remote-api/src/test/java/org/alfresco/repo/webdav/WebDAVMethodTest.java
  remote-api/src/test/java/org/alfresco/rest/api/tests/ProbeApiTest.java
  remote-api/src/test/java/org/alfresco/rest/api/tests/QueriesPeopleApiTest.java
  repository/pom.xml
  repository/src/main/java/org/alfresco/messaging/camel/SpringContextRouteLoader.java
  repository/src/main/java/org/alfresco/messaging/camel/configuration/ConnectionFactoryConfiguration.java
  repository/src/main/java/org/alfresco/messaging/camel/routes/OnContentUpdateRenditionRoute.java
  repository/src/main/java/org/alfresco/messaging/camel/routes/RepoNodeEventsRouteBuilder.java
  repository/src/main/java/org/alfresco/messaging/camel/routes/TransformRequestConsumer.java
  repository/src/main/resources/alfresco/subsystems/Messaging/default/messaging-context.xml
  repository/src/test/java/org/alfresco/messaging/camel/CamelRoutesTest.java
  repository/src/test/java/org/alfresco/messaging/camel/routes/TestingRouteBuilder.java
  repository/src/test/java/org/alfresco/repo/event2/AbstractContextAwareRepoEvent.java
  repository/src/test/java/org/alfresco/repo/rendition2/RenditionEventProcessorTest.java
  repository/src/test/java/org/alfresco/repo/rendition2/TransformationOptionsConverterTest.java
Labels: PR: unreviewed

#241 LOC-282 - Partial fix. 12 language bundles updated.
  remote-api/src/main/resources/alfresco/messages/admin-console_sv.properties
  remote-api/src/main/resources/alfresco/messages/rest-framework-messages_fi.properties
  repository/src/main/resources/alfresco/messages/action-config_fi.properties
  repository/src/main/resources/alfresco/messages/action-config_fr.properties
  repository/src/main/resources/alfresco/messages/activiti-engine-messages_fi.properties
  repository/src/main/resources/alfresco/messages/authentication_fi.properties
  repository/src/main/resources/alfresco/messages/bootstrap-messages_nb.properties
  repository/src/main/resources/alfresco/messages/bootstrap-spaces_fr.properties
  repository/src/main/resources/alfresco/messages/bootstrap-spaces_it.properties
  repository/src/main/resources/alfresco/messages/categories_fi.properties
  repository/src/main/resources/alfresco/messages/coci-service_nb.properties
  repository/src/main/resources/alfresco/messages/content-model_fi.properties
  repository/src/main/resources/alfresco/messages/content-model_fr.properties
  repository/src/main/resources/alfresco/messages/email-service_fr.properties
  repository/src/main/resources/alfresco/messages/imap-service_fi.properties
  repository/src/main/resources/alfresco/messages/imap-service_fr.properties
  repository/src/main/resources/alfresco/messages/invitation-service_fr.properties
  repository/src/main/resources/alfresco/messages/notification-service_fi.properties
  repository/src/main/resources/alfresco/messages/notification-service_fr.properties
  repository/src/main/resources/alfresco/messages/rendition-config_fi.properties
  repository/src/main/resources/alfresco/messages/replication_fi.properties
  repository/src/main/resources/alfresco/messages/repoadmin-service_fi.properties
  repository/src/main/resources/alfresco/messages/system-messages_fi.properties
  repository/src/main/resources/alfresco/messages/system-messages_pt_BR.properties
  repository/src/main/resources/alfresco/messages/system-messages_sv.properties
  repository/src/main/resources/alfresco/messages/system-model_fi.properties
  repository/src/main/resources/alfresco/messages/templates-messages_de.properties
  repository/src/main/resources/alfresco/messages/templates-messages_es.properties
  repository/src/main/resources/alfresco/messages/templates-messages_fi.properties
  repository/src/main/resources/alfresco/messages/templates-messages_fr.properties
  repository/src/main/resources/alfresco/messages/templates-messages_it.properties
  repository/src/main/resources/alfresco/messages/templates-messages_ja.properties
  repository/src/main/resources/alfresco/messages/templates-messages_nb.properties
  repository/src/main/resources/alfresco/messages/templates-messages_nl.properties
  repository/src/main/resources/alfresco/messages/templates-messages_pt_BR.properties
  repository/src/main/resources/alfresco/messages/templates-messages_ru.properties
  repository/src/main/resources/alfresco/messages/templates-messages_zh_CN.properties
  repository/src/main/resources/alfresco/messages/transfer-model_fi.properties
  repository/src/main/resources/alfresco/messages/transfer-service_fi.properties
  repository/src/main/resources/alfresco/messages/webdav-messages_fi.properties
  repository/src/main/resources/alfresco/workflow/invitation-nominated-workflow-messages_fi.properties
Labels: PR: unreviewed

#243 ACS-1140: Added cluster-aware cache for QuerySet configs.
  repository/src/main/resources/alfresco/cache-context.xml
  repository/src/main/resources/alfresco/caches.properties
Labels: PR: unreviewed

#250 ACS-1170 : Release Gytheio 0.12 - ACS 7.0 compatible
  pom.xml
  repository/src/main/java/org/alfresco/messaging/camel/configuration/ConnectionFactoryConfiguration.java
  repository/src/main/resources/alfresco/subsystems/Messaging/default/messaging-context.xml
Labels: PR: reviewed-approved

#249 [ACS-1160] Handle null Authority
  repository/src/main/java/org/alfresco/repo/search/impl/querymodel/impl/db/DBQueryEngine.java
  repository/src/test/java/org/alfresco/repo/search/impl/querymodel/impl/db/DBQueryEngineTest.java
Labels: PR: reviewed-approved

#254 ACS-1146 Replace *javax* dependencies with *jakarta* libraries
  core/pom.xml
  data-model/pom.xml
  packaging/tests/tas-integration/pom.xml
  packaging/tests/tas-restapi/pom.xml
  packaging/war/pom.xml
  pom.xml
  remote-api/pom.xml
  remote-api/src/main/java/org/alfresco/repo/webdav/WebDAVServlet.java
  repository/pom.xml
Labels: PR: partially-approved

#255 MNT-20775 : deleted-nodes with maxitems parameter take longer
  core/src/main/java/org/alfresco/query/AbstractCannedQuery.java
  repository/src/main/java/org/alfresco/repo/node/archive/GetArchivedNodesCannedQuery.java
  repository/src/main/resources/alfresco/ibatis/org.alfresco.repo.domain.dialect.Dialect/query-archived-nodes-common-SqlMap.xml
Labels: PR: partially-approved

#262 MNT-20775 : deleted-nodes with maxitems parameter take longer
  core/src/main/java/org/alfresco/query/AbstractCannedQuery.java
  repository/src/main/java/org/alfresco/repo/node/archive/GetArchivedNodesCannedQuery.java
  repository/src/main/resources/alfresco/ibatis/org.alfresco.repo.domain.dialect.Dialect/query-archived-nodes-common-SqlMap.xml
Labels: PR: reviewed-approved

#264 REPO-5549 Fix: Local transformer names must exist and be unique docli…
  data-model/src/main/java/org/alfresco/util/ConfigScheduler.java
  repository/src/main/java/org/alfresco/repo/content/transform/LocalCombinedConfig.java
  repository/src/main/java/org/alfresco/repo/content/transform/LocalTransformImpl.java
  repository/src/main/java/org/alfresco/repo/content/transform/LocalTransformServiceRegistry.java
  repository/src/main/java/org/alfresco/transform/client/registry/CombinedConfig.java
  repository/src/test/java/org/alfresco/transform/client/registry/LocalTransformServiceRegistryConfigTest.java
  repository/src/test/resources/alfresco/local-transform-service-config-dup-name-test.json
  repository/src/test/resources/alfresco/local-transform-service-config-no-base-url-test.json
  repository/src/test/resources/alfresco/local-transform-service-config-no-name-test.json
  repository/src/test/resources/alfresco/local-transform-service-config-override-test.json
  repository/src/test/resources/alfresco/local-transform-service-config-override-with-pipeline-test.json
  repository/src/test/resources/alfresco/local-transform-service-config-pipeline-and-failover-test.json
  repository/src/test/resources/alfresco/transform-service-config-failover-missing-step-test.json
  repository/src/test/resources/alfresco/transform-service-config-pipeline-missing-step-test.json
Labels: PR: unreviewed
