Repository Alfresco/alfresco-community-repo, pull requests merged in 2021-12, with the labels that each got.

#807 ACS-2151 Get StorageProps endpoint
  remote-api/src/main/java/org/alfresco/rest/api/ContentStorageInformation.java
  remote-api/src/main/java/org/alfresco/rest/api/impl/ContentStorageInformationImpl.java
  remote-api/src/main/java/org/alfresco/rest/api/model/ContentStorageInfo.java
  remote-api/src/main/java/org/alfresco/rest/api/nodes/NodeStorageInfoRelation.java
  remote-api/src/main/resources/alfresco/public-rest-context.xml
  remote-api/src/test/java/org/alfresco/rest/api/impl/ContentStorageInformationImplTest.java
Labels: PR: partially-approved

#813 ACS-2216: Fix incorrect ContentService Java Interface - should accept content propQName
  remote-api/src/main/java/org/alfresco/rest/api/impl/NodesImpl.java
  repository/src/main/java/org/alfresco/repo/content/ContentServiceImpl.java
  repository/src/main/java/org/alfresco/service/cmr/repository/ContentService.java
  repository/src/test/java/org/alfresco/repo/content/ContentServiceImplUnitTest.java
  repository/src/test/java/org/alfresco/repo/version/ContentServiceImplTest.java
Labels: PR: partially-approved

#822 ACS-2321 Downloads throws 412 error if content is archived
  remote-api/src/main/java/org/alfresco/rest/api/impl/DownloadsImpl.java
  remote-api/src/main/resources/alfresco/public-rest-context.xml
  remote-api/src/test/java/org/alfresco/AppContext04TestSuite.java
  remote-api/src/test/java/org/alfresco/rest/api/impl/DownloadsImplCheckArchiveStatusUnitTest.java
  repository/src/main/resources/alfresco/repository.properties
Labels: PR: partially-approved

#824 [MNT-21551] Handle links path with a changed root-node
  amps/share-services/src/main/resources/alfresco/templates/webscripts/org/alfresco/slingshot/documentlibrary-v2/parse-args.lib.js
Labels: PR: reviewed-approved

#830 PRODESC-5780: ACS Repo DAU APIs to also use non-attach allow list
  remote-api/src/main/java/org/alfresco/opencmis/CMISServletDispatcher.java
  remote-api/src/main/java/org/alfresco/rest/api/impl/NodesImpl.java
  remote-api/src/main/resources/alfresco/public-rest-context.xml
  repository/src/main/java/org/alfresco/repo/content/ContentServiceImpl.java
  repository/src/main/resources/alfresco/content-services-context.xml
  repository/src/main/resources/alfresco/repository.properties
Labels: PR: partially-approved

#827 ATS-969 Upgrade tika (not poi)
  data-model/pom.xml
  data-model/src/main/java/org/alfresco/repo/content/MimetypeMap.java
  data-model/src/test/java/org/alfresco/repo/dictionary/DiffModelTest.java
  pom.xml
  remote-api/pom.xml
  repository/pom.xml
  repository/src/main/java/org/alfresco/repo/remoteconnector/RemoteConnectorResponseImpl.java
  repository/src/main/resources/alfresco/tika/tika-config.xml
Labels: PR: reviewed-approved

#820 MNT-22689 Bumping xmlsec to 2.3.0 due to vulnerabilities found.
  remote-api/pom.xml
Labels: PR: partially-approved

#825 ACS-2200: Java API for archive/archive-restore content
  data-model/src/main/java/org/alfresco/repo/content/ContentRestoreParams.java
  data-model/src/main/java/org/alfresco/repo/content/ContentStore.java
  repository/src/main/java/org/alfresco/repo/content/AbstractRoutingContentStore.java
  repository/src/main/java/org/alfresco/repo/content/ContentServiceImpl.java
  repository/src/main/java/org/alfresco/repo/content/caching/CachingContentStore.java
  repository/src/main/java/org/alfresco/repo/content/replication/AggregatingContentStore.java
  repository/src/main/java/org/alfresco/repo/tenant/AbstractTenantRoutingContentStore.java
  repository/src/main/java/org/alfresco/service/cmr/repository/ContentService.java
  repository/src/main/resources/alfresco/public-services-security-context.xml
  repository/src/test/java/org/alfresco/AllUnitTestsSuite.java
  repository/src/test/java/org/alfresco/repo/content/ContentServiceImplUnitTest.java
  repository/src/test/java/org/alfresco/repo/content/caching/CachingContentStoreTest.java
  repository/src/test/java/org/alfresco/repo/content/replication/AggregatingContentStoreTest.java
  repository/src/test/java/org/alfresco/repo/content/replication/AggregatingContentStoreUnitTest.java
Labels: PR: unreviewed

#831 MNT-22715 - Document Version Issue
  amps/ags/rm-community/rm-community-repo/source/java/org/alfresco/module/org_alfresco_module_rm/version/RecordableVersionServiceImpl.java
  repository/src/main/java/org/alfresco/repo/version/Version2ServiceImpl.java
  repository/src/test/java/org/alfresco/repo/version/VersionServiceImplTest.java
Labels: PR: reviewed-approved

#835 [MNT-21551] Handle links path with a changed root-node (#824)
  amps/share-services/src/main/resources/alfresco/templates/webscripts/org/alfresco/slingshot/documentlibrary-v2/parse-args.lib.js
Labels: PR: unreviewed

#836 MNT-22715 - Setting Version Child Assoc Index Configurable
  amps/ags/rm-community/rm-community-repo/source/java/org/alfresco/module/org_alfresco_module_rm/version/RecordableVersionServiceImpl.java
  repository/src/main/java/org/alfresco/repo/version/Version2ServiceImpl.java
  repository/src/main/resources/alfresco/core-services-context.xml
  repository/src/main/resources/alfresco/repository.properties
  repository/src/test/java/org/alfresco/repo/version/VersionServiceImplTest.java
Labels: PR: reviewed-approved

#837 MNT-22715 - Document Version Issue
  repository/src/main/java/org/alfresco/repo/version/Version2ServiceImpl.java
  repository/src/main/resources/alfresco/core-services-context.xml
  repository/src/main/resources/alfresco/repository.properties
  repository/src/test/java/org/alfresco/repo/version/VersionServiceImplTest.java
Labels: PR: unreviewed

#838 MNT-22715 - Document Version Issue
  amps/ags/rm-community/rm-community-repo/source/java/org/alfresco/module/org_alfresco_module_rm/version/RecordableVersionServiceImpl.java
  repository/src/main/java/org/alfresco/repo/version/Version2ServiceImpl.java
  repository/src/main/resources/alfresco/core-services-context.xml
  repository/src/main/resources/alfresco/repository.properties
  repository/src/test/java/org/alfresco/repo/version/VersionServiceImplTest.java
Labels: PR: unreviewed

#832 ACS-2331 Add RestoreInProgressException
  data-model/src/main/java/org/alfresco/service/cmr/repository/RestoreInProgressException.java
  remote-api/src/main/java/org/alfresco/rest/framework/core/exceptions/RestoreInProgressException.java
  remote-api/src/main/resources/alfresco/public-rest-context.xml
Labels: PR: partially-approved

#826 ACS-2336 POST endpoints for archive/archive-restore content
  remote-api/src/main/java/org/alfresco/rest/api/ContentStorageInformation.java
  remote-api/src/main/java/org/alfresco/rest/api/impl/ContentStorageInformationImpl.java
  remote-api/src/main/java/org/alfresco/rest/api/model/ArchiveContentRequest.java
  remote-api/src/main/java/org/alfresco/rest/api/model/RestoreArchivedContentRequest.java
  remote-api/src/main/java/org/alfresco/rest/api/nodes/NodeStorageInfoRelation.java
  remote-api/src/test/java/org/alfresco/AppContextExtraTestSuite.java
  remote-api/src/test/java/org/alfresco/rest/api/impl/ContentStorageInformationImplTest.java
  remote-api/src/test/java/org/alfresco/rest/api/nodes/NodeStorageInfoRelationTest.java
  repository/src/main/java/org/alfresco/service/cmr/repository/ContentService.java
Labels: PR: partially-approved

#839 ACS-2331 handle RestoreInProgressException
  remote-api/src/main/java/org/alfresco/rest/api/impl/ContentStorageInformationImpl.java
  remote-api/src/test/java/org/alfresco/rest/api/impl/ContentStorageInformationImplTest.java
Labels: PR: reviewed-approved

#840 ACS-2236: Fixing NPE when no body provided for POST requests.
  remote-api/src/main/java/org/alfresco/rest/api/impl/ContentStorageInformationImpl.java
  remote-api/src/test/java/org/alfresco/rest/api/impl/ContentStorageInformationImplTest.java
Labels: PR: partially-approved

#842 ACS-2102 Upgrade mysql driver
  .travis.yml
  pom.xml
Labels: PR: reviewed-approved

#845 MNT-22601 Bump surf-webscripts to 8.27
  pom.xml
Labels: PR: reviewed-approved

#847 [ACS-2158] tas-restapi version bumped to 1.66
  pom.xml
Labels: PR: reviewed-approved

#851 MNT-22601 Bump surf-webscripts to 8.27
  pom.xml
Labels: PR: reviewed-approved

#853 MNT-21506: sanitize username on nodeBrowser Repo (#756)
  remote-api/src/main/resources/alfresco/templates/webscripts/org/alfresco/repository/admin/support-tools/admin-nodebrowser.get.html.ftl
Labels: PR: unreviewed

#862 ACS-2243 Attempt to fix intermittent failure in JobLockServiceTest
  repository/src/test/java/org/alfresco/repo/lock/JobLockServiceTest.java
Labels: PR: reviewed-approved
