Repository Alfresco/alfresco-community-repo, pull requests merged in 2021-05, with the labels that each got.

#427 ATS-892 / ATS-909: Add IPTC model to core Repo
  repository/src/main/resources/alfresco/core-services-context.xml
  repository/src/main/resources/alfresco/messages/iptc-model.properties
  repository/src/main/resources/alfresco/messages/iptc-model_de.properties
  repository/src/main/resources/alfresco/messages/iptc-model_es.properties
  repository/src/main/resources/alfresco/messages/iptc-model_fr.properties
  repository/src/main/resources/alfresco/messages/iptc-model_it.properties
  repository/src/main/resources/alfresco/messages/iptc-model_ja.properties
  repository/src/main/resources/alfresco/messages/iptc-model_nb.properties
  repository/src/main/resources/alfresco/messages/iptc-model_nl.properties
  repository/src/main/resources/alfresco/messages/iptc-model_pt_BR.properties
  repository/src/main/resources/alfresco/messages/iptc-model_ru.properties
  repository/src/main/resources/alfresco/messages/iptc-model_zh_CN.properties
  repository/src/main/resources/alfresco/model/iptcModel.xml
Labels: PR: partially-approved

#429 ATS-892 / ATS-909: Add IPTC model
  repository/src/main/resources/alfresco/core-services-context.xml
Labels: PR: partially-approved, PR: unreviewed

#431 Pom and build cleanup [skip ci]
  .travis.yml
  amps/ags/.travis.yml
  amps/ags/pom.xml
  amps/ags/rm-automation/pom.xml
  amps/ags/rm-automation/rm-automation-community-rest-api/pom.xml
  amps/ags/rm-community/rm-community-repo/pom.xml
  amps/ags/rm-community/rm-community-rest-api-explorer/README.md
  amps/ags/rm-community/rm-community-rest-api-explorer/pom.xml
  amps/ags/travis/.travis.deploy-stage.yml
  amps/ags/travis/.travis.env-vars.yml
  amps/ags/travis/.travis.integration-test-MySQL.yml
  amps/ags/travis/.travis.tests-stage.yml
  amps/ags/travis/scripts/cleanImages.sh
  amps/ags/travis/scripts/cleanup.sh
  amps/ags/travis/scripts/create-worm-bucket.sh
  amps/ags/travis/scripts/delete-test-buckets-lambda.py
  amps/ags/travis/scripts/dockerLimitMemory.sh
  amps/ags/travis/scripts/pushDockerDigestTag.sh
  amps/ags/travis/scripts/source_clear.sh
  amps/ags/travis/scripts/start-compose.sh
  amps/ags/travis/scripts/startAlfresco.sh
  amps/ags/travis/scripts/waitForAlfrescoToStart.sh
  data-model/pom.xml
  packaging/war/pom.xml
  pom.xml
  repository/pom.xml
Labels: PR: unreviewed

#433 Fix/acs 1425 fix community sql
  repository/src/main/resources/alfresco/ibatis/org.alfresco.repo.domain.dialect.Dialect/metadata-query-common-SqlMap.xml
Labels: PR: reviewed-approved

#383 [MNT-22183] Use absolute paths for stylesheets
  packaging/war/src/main/webapp/error.jsp
  packaging/war/src/main/webapp/index.jsp
Labels: PR: partially-approved

#435 REPO-5624 Reimplement SchemaBootstrapTest
  repository/src/test/java/org/alfresco/util/schemacomp/SchemaBootstrapTest.java
Labels: PR: reviewed-approved

#425 Bugfix/ACS-1319 fix long running patch
  repository/src/main/java/org/alfresco/util/schemacomp/SchemaDifferenceHelper.java
  repository/src/main/resources/alfresco/dbscripts/create/org.alfresco.repo.domain.dialect.MySQLInnoDBDialect/AlfrescoCreate-RepoTables.sql
  repository/src/main/resources/alfresco/dbscripts/create/org.alfresco.repo.domain.dialect.MySQLInnoDBDialect/Schema-Reference-ALF.xml
  repository/src/main/resources/alfresco/dbscripts/create/org.alfresco.repo.domain.dialect.PostgreSQLDialect/AlfrescoCreate-RepoTables.sql
  repository/src/main/resources/alfresco/dbscripts/create/org.alfresco.repo.domain.dialect.PostgreSQLDialect/Schema-Reference-ALF.xml
  repository/src/main/resources/alfresco/dbscripts/db-schema-context.xml
  repository/src/main/resources/alfresco/dbscripts/upgrade/7.1.0/org.alfresco.repo.domain.dialect.MySQLInnoDBDialect/remove-alf_server-table.sql
  repository/src/main/resources/alfresco/dbscripts/upgrade/7.1.0/org.alfresco.repo.domain.dialect.PostgreSQLDialect/remove-alf_server-table.sql
  repository/src/main/resources/alfresco/dbscripts/upgrade/7.1.0/remove-alf_server-table.patterns
  repository/src/main/resources/alfresco/messages/patch-service.properties
  repository/src/main/resources/alfresco/patch/patch-services-context.xml
  repository/src/main/resources/alfresco/repository.properties
  repository/src/test/java/org/alfresco/util/schemacomp/SchemaBootstrapTest.java
  repository/src/test/java/org/alfresco/util/schemacomp/SchemaDifferenceHelperUnitTest.java
  repository/src/test/java/org/alfresco/util/schemacomp/SchemaReferenceFileTest.java
  repository/src/test/resources/alfresco/dbscripts/bootstrap-context-test.xml
  repository/src/test/resources/alfresco/dbscripts/create/org.alfresco.repo.domain.dialect.PostgreSQLDialect/Test-Schema-Reference-ALF.xml
Labels: PR: reviewed-approved

#440 Turn off db jobs on pull requests
  .travis.yml
Labels: PR: unreviewed

#441 ATS-912: Bump to T-Core 2.4.0
  .travis.yml
  packaging/tests/environment/.env
Labels: PR: partially-approved

#444 MNT-21694 transform option converter
  repository/src/main/java/org/alfresco/repo/rendition2/TransformationOptionsConverter.java
  repository/src/test/java/org/alfresco/repo/rendition2/TransformationOptionsConverterTest.java
Labels: PR: unreviewed

#387 ACS-895 - User email should not be necessary for joining a site
  repository/src/main/java/org/alfresco/repo/invitation/InvitationServiceImpl.java
Labels: PR: unreviewed

#447 ACS-1560 Update AGS amp build configuration for compatibility with ACS and its release plugin [skip ci]
  amps/ags/pom.xml
  amps/ags/rm-community/rm-community-repo/config/alfresco/module/org_alfresco_module_rm/module.properties
  amps/ags/rm-community/rm-community-repo/pom.xml
  amps/ags/rm-community/rm-community-repo/tomcat/context.xml
  amps/ags/rm-community/rm-community-rest-api-explorer/pom.xml
  pom.xml
Labels: PR: unreviewed

#446 APPS-988
  amps/ags/rm-automation/rm-automation-community-rest-api/pom.xml
  amps/ags/rm-automation/rm-automation-community-rest-api/src/main/java/org/alfresco/rest/rm/community/util/PojoUtility.java
Labels: PR: reviewed-approved

#317 [MNT-20006] Obtaining the site as system in order to allow the activity record when an user is not member of a site
  repository/src/main/java/org/alfresco/opencmis/ActivityPosterImpl.java
  repository/src/main/resources/alfresco/opencmis-context.xml
  repository/src/test/java/org/alfresco/opencmis/CMISTest.java
Labels: PR: reviewed-approved

#448 APPS-995 Refactor DispositionScheduleLinkedRecordsTest in order to create prec…
  amps/ags/rm-automation/rm-automation-community-rest-api/src/main/java/org/alfresco/rest/rm/community/model/recordcategory/RetentionPeriodProperty.java
  amps/ags/rm-automation/rm-automation-community-rest-api/src/main/java/org/alfresco/rest/v0/RecordCategoriesAPI.java
  amps/ags/rm-automation/rm-automation-community-rest-api/src/main/java/org/alfresco/rest/v0/service/DispositionScheduleService.java
  amps/ags/rm-automation/rm-automation-community-rest-api/src/main/java/org/alfresco/rest/v0/service/RoleService.java
  amps/ags/rm-automation/rm-automation-community-rest-api/src/test/java/org/alfresco/rest/rm/community/hold/PreventActionsOnFrozenContentTests.java
  amps/ags/rm-automation/rm-automation-community-rest-api/src/test/java/org/alfresco/rest/rm/community/recordcategories/AutomaticDispositionTest.java
  amps/ags/rm-automation/rm-automation-community-rest-api/src/test/java/org/alfresco/rest/rm/community/recordcategories/DispositionScheduleInheritanceTests.java
  amps/ags/rm-automation/rm-automation-community-rest-api/src/test/java/org/alfresco/rest/rm/community/records/DeleteRecordTests.java
Labels: PR: reviewed-approved

#454 REPO-5391 : [cmis webservices] isPrivateWorkingCopy throws NullPointerException
  packaging/tests/tas-cmis/src/test/java/org/alfresco/cmis/CancelCheckOutTests.java
  packaging/tests/tas-cmis/src/test/java/org/alfresco/cmis/CheckInTests.java
  packaging/tests/tas-cmis/src/test/java/org/alfresco/cmis/CheckOutTests.java
  packaging/tests/tas-cmis/src/test/java/org/alfresco/cmis/CreateDocumentTests.java
  packaging/tests/tas-cmis/src/test/java/org/alfresco/cmis/IsPrivateWorkingCopyTests.java
  pom.xml
Labels: PR: reviewed-approved

#457 [MNT-22183] Use absolute paths for stylesheets (#383)
  packaging/war/src/main/webapp/error.jsp
  packaging/war/src/main/webapp/index.jsp
Labels: PR: unreviewed

#458 [MNT-22183] Use absolute paths for stylesheets (#383)
  packaging/war/src/main/webapp/error.jsp
  packaging/war/src/main/webapp/index.jsp
Labels: PR: merged

#449 LOC-303 Fix for this ticket - Fully updated and localised iptc-model.…
  l10n.properties
  repository/src/main/resources/alfresco/messages/iptc-model_cs.properties
  repository/src/main/resources/alfresco/messages/iptc-model_da.properties
  repository/src/main/resources/alfresco/messages/iptc-model_de.properties
  repository/src/main/resources/alfresco/messages/iptc-model_es.properties
  repository/src/main/resources/alfresco/messages/iptc-model_fi.properties
  repository/src/main/resources/alfresco/messages/iptc-model_fr.properties
  repository/src/main/resources/alfresco/messages/iptc-model_it.properties
  repository/src/main/resources/alfresco/messages/iptc-model_ja.properties
  repository/src/main/resources/alfresco/messages/iptc-model_nb.properties
  repository/src/main/resources/alfresco/messages/iptc-model_nl.properties
  repository/src/main/resources/alfresco/messages/iptc-model_pl.properties
  repository/src/main/resources/alfresco/messages/iptc-model_pt_BR.properties
  repository/src/main/resources/alfresco/messages/iptc-model_ru.properties
  repository/src/main/resources/alfresco/messages/iptc-model_sv.properties
  repository/src/main/resources/alfresco/messages/iptc-model_zh_CN.properties
Labels: PR: partially-approved

#461 REPO-5630 Fix for intermittent failing test PeopleTest.testPagingAndSortingByFirstNameDesc
  remote-api/src/test/java/org/alfresco/rest/api/tests/TestPeople.java
Labels: PR: unreviewed

#463 SHA-2478 : Some Share features stop working if a site has description = null
  remote-api/src/main/resources/alfresco/templates/webscripts/org/alfresco/repository/site/site-admin-sites.get.json.ftl
  remote-api/src/main/resources/alfresco/templates/webscripts/org/alfresco/repository/site/site.lib.ftl
Labels: PR: partially-approved

#460 DESKTOPAPP-654
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/sites/members/GetSiteMemberTests.java
  pom.xml
Labels: PR: unreviewed

#464 ACS-1587 Postsql DB Test Schema Differences Are Reported Fails
  repository/src/main/java/org/alfresco/repo/domain/schema/SchemaBootstrap.java
Labels: PR: reviewed-approved

#468 MNT-22409 single page image previewACS 6.2.2: Legacy transformer with ImageMagick fails to generate multi-page TIFF -> multi-page PDF file preview
  repository/src/main/java/org/alfresco/repo/content/transform/magick/AbstractImageMagickContentTransformerWorker.java
  repository/src/main/java/org/alfresco/repo/content/transform/magick/ImageMagickContentTransformerWorker.java
  repository/src/main/resources/alfresco/renditions/0100-baseRenditions.json
  repository/src/main/resources/alfresco/repository.properties
  repository/src/test/java/org/alfresco/repo/rendition2/RenditionDefinitionTest.java
Labels: PR: unreviewed

#466 APPS-46: Enable SearchRecordsV1Cmis tests
  amps/ags/rm-automation/rm-automation-community-rest-api/src/test/java/org/alfresco/rest/rm/community/search/SearchRecordsV1CmisTests.java
Labels: PR: reviewed-approved

#471 ACS-895 User email should not be necessary for joining a site
  repository/src/main/java/org/alfresco/repo/invitation/InvitationServiceImpl.java
  repository/src/main/java/org/alfresco/repo/invitation/site/InviteNominatedSender.java
Labels: PR: unreviewed

#467 ACS-1582 : Storage classes - java api
  data-model/src/main/java/org/alfresco/repo/content/ContentContext.java
  data-model/src/main/java/org/alfresco/repo/content/ContentStore.java
  data-model/src/main/java/org/alfresco/repo/content/UnsupportedStorageClassException.java
  repository/src/main/java/org/alfresco/repo/content/AbstractRoutingContentStore.java
  repository/src/main/java/org/alfresco/repo/content/caching/CachingContentStore.java
  repository/src/main/java/org/alfresco/repo/content/filestore/FileContentStore.java
  repository/src/main/java/org/alfresco/repo/content/replication/AggregatingContentStore.java
  repository/src/main/java/org/alfresco/repo/tenant/AbstractTenantRoutingContentStore.java
  repository/src/main/java/org/alfresco/service/cmr/repository/ContentService.java
  repository/src/test/java/org/alfresco/repo/content/RoutingContentStoreTest.java
  repository/src/test/java/org/alfresco/repo/content/caching/CachingContentStoreTest.java
  repository/src/test/java/org/alfresco/repo/content/filestore/FileContentStoreTest.java
  repository/src/test/java/org/alfresco/repo/content/replication/AggregatingContentStoreTest.java
Labels: PR: unreviewed

#473 ACS-1600 : Error when running propTablesCleanupJob on an env with 100million records in alf_prop_value
  repository/src/main/java/org/alfresco/repo/domain/schema/script/DeleteNotExistsExecutor.java
  repository/src/main/java/org/alfresco/repo/domain/schema/script/MySQLDeleteNotExistsExecutor.java
Labels: PR: reviewed-approved

#485 [REPO-5592] Support for PostgreSQL and MySQL, batch size is now configurable
  repository/src/main/java/org/alfresco/repo/content/cleanup/ContentStoreCleaner.java
  repository/src/main/java/org/alfresco/repo/domain/contentdata/ContentUrlOrphanQuery.java
  repository/src/main/java/org/alfresco/repo/domain/contentdata/ibatis/ContentDataDAOImpl.java
  repository/src/main/resources/alfresco/content-services-context.xml
  repository/src/main/resources/alfresco/ibatis/org.alfresco.repo.domain.dialect.Dialect/content-select-SqlMap.xml
  repository/src/main/resources/alfresco/ibatis/org.alfresco.repo.domain.dialect.MySQLInnoDBDialect/content-select-SqlMap.xml
  repository/src/main/resources/alfresco/repository.properties
Labels: PR: unreviewed

#459 [MNT-20006] Obtaining the site as system in order to allow the activity record when an user is not member of a site
  repository/src/main/java/org/alfresco/opencmis/ActivityPosterImpl.java
  repository/src/main/resources/alfresco/opencmis-context.xml
  repository/src/test/java/org/alfresco/opencmis/CMISTest.java
Labels: PR: reviewed-approved

#462 [MNT-20006] Obtaining the site as system in order to allow the activity record when an user is not member of a site
  repository/src/main/java/org/alfresco/opencmis/ActivityPosterImpl.java
  repository/src/main/resources/alfresco/opencmis-context.xml
  repository/src/test/java/org/alfresco/opencmis/CMISTest.java
  scripts/travis/trigger_travis.sh
Labels: PR: reviewed-approved

#487 MNT-22316 - Access short path on AOS with Kerberos
  remote-api/src/main/java/org/alfresco/repo/webdav/auth/BaseSSOAuthenticationFilter.java
Labels: PR: reviewed-approved

#476 APPS-1372 Disable latest docker image push
  scripts/travis/build.sh
Labels: PR: reviewed-approved

#486 ACS-1604 : Update & tests for AggregatingContentStore
  repository/src/main/java/org/alfresco/repo/content/replication/AggregatingContentStore.java
  repository/src/test/java/org/alfresco/repo/content/replication/AggregatingContentStoreTest.java
Labels: PR: reviewed-approved

#475 ACS-1605 : Update & tests for CachingContentStore
  repository/src/main/java/org/alfresco/repo/content/caching/CachingContentStore.java
  repository/src/test/java/org/alfresco/repo/content/caching/CachingContentStoreTest.java
Labels: PR: partially-approved

#490 MNT-22316 - Added pathInfo length validation before attempting substr…
  remote-api/src/main/java/org/alfresco/repo/webdav/auth/BaseSSOAuthenticationFilter.java
Labels: PR: unreviewed

#491 MNT-22316 - Added pathInfo length validation before attempting substr…
  remote-api/src/main/java/org/alfresco/repo/webdav/auth/BaseSSOAuthenticationFilter.java
Labels: PR: unreviewed

#492 MNT-22316 - Added pathInfo length validation before attempting substr…
  remote-api/src/main/java/org/alfresco/repo/webdav/auth/BaseSSOAuthenticationFilter.java
Labels: PR: unreviewed

#488 ACS-1607 : Update & tests for ContentServiceImpl
  repository/src/main/java/org/alfresco/repo/content/ContentServiceImpl.java
  repository/src/test/java/org/alfresco/AllUnitTestsSuite.java
  repository/src/test/java/org/alfresco/repo/version/ContentServiceImplTest.java
  repository/src/test/java/org/alfresco/repo/version/ContentServiceImplWithMockedContentStoreTest.java
Labels: PR: partially-approved

#496 Fix/mnt 22425 overriding transformers not working
  .gitignore
  data-model/src/main/java/org/alfresco/util/ConfigScheduler.java
  pom.xml
  repository/src/main/java/org/alfresco/repo/content/transform/LocalCombinedConfig.java
  repository/src/main/java/org/alfresco/repo/content/transform/LocalTransformImpl.java
  repository/src/main/java/org/alfresco/repo/content/transform/LocalTransformServiceRegistry.java
  repository/src/main/java/org/alfresco/transform/client/registry/CombinedConfig.java
  repository/src/test/java/org/alfresco/transform/client/registry/LocalTransformServiceRegistryConfigTest.java
  repository/src/test/resources/alfresco/local-transform-service-config-dup-name-test.json
  repository/src/test/resources/alfresco/local-transform-service-config-no-base-url-test.json
  repository/src/test/resources/alfresco/local-transform-service-config-no-name-test.json
  repository/src/test/resources/alfresco/local-transform-service-config-override-test.json
  repository/src/test/resources/alfresco/local-transform-service-config-override-with-pipeline-test.json
  repository/src/test/resources/alfresco/local-transform-service-config-pipeline-and-failover-test.json
  repository/src/test/resources/alfresco/transform-service-config-failover-missing-step-test.json
  repository/src/test/resources/alfresco/transform-service-config-pipeline-missing-step-test.json
Labels: PR: reviewed-approved

#497 MNT-22425 : bump transform.model to 1.0.2.10
  pom.xml
Labels: PR: unreviewed

#499 REPO-5632 Investigate intermittent failing tests in AppContext05TestSuite
  repository/src/test/java/org/alfresco/repo/domain/permissions/FixedAclUpdaterTest.java
Labels: PR: reviewed-approved

#503 ACS-1603 : Update & tests for AbstractTenantRoutingContentStore
  repository/src/main/java/org/alfresco/repo/tenant/AbstractTenantRoutingContentStore.java
  repository/src/test/java/org/alfresco/repo/tenant/AbstractTenantRoutingContentStoreTest.java
Labels: PR: partially-approved

#472 REPO-5631 Investigate different types of results for optional patches difference detection
  repository/src/main/java/org/alfresco/repo/domain/schema/SchemaBootstrap.java
  repository/src/main/java/org/alfresco/util/schemacomp/Difference.java
  repository/src/main/java/org/alfresco/util/schemacomp/RedundantDbObject.java
  repository/src/main/java/org/alfresco/util/schemacomp/Result.java
  repository/src/main/java/org/alfresco/util/schemacomp/SchemaDifferenceHelper.java
  repository/src/main/java/org/alfresco/util/schemacomp/ValidationResult.java
  repository/src/test/java/org/alfresco/util/schemacomp/SchemaBootstrapTest.java
  repository/src/test/java/org/alfresco/util/schemacomp/SchemaDifferenceHelperUnitTest.java
Labels: PR: reviewed-approved

#504 MNT-22385 Cmis query GetTotalNumItems is returning wrong value
  repository/src/main/java/org/alfresco/repo/search/impl/querymodel/impl/db/DBQueryEngine.java
  repository/src/main/java/org/alfresco/repo/search/impl/querymodel/impl/db/NodePermissionAssessor.java
  repository/src/main/resources/alfresco/repository.properties
  repository/src/main/resources/alfresco/subsystems/Search/common-search-context.xml
  repository/src/test/java/org/alfresco/repo/search/impl/querymodel/impl/db/DBQueryEngineTest.java
Labels: PR: reviewed-approved
