Repository Alfresco/alfresco-community-repo, pull requests merged in 2022-10, with the labels that each got.

#1443 Feature/acs-3579
  amps/ags/rm-automation/rm-automation-community-rest-api/src/test/java/org/alfresco/rest/rm/community/records/DeleteRecordTests.java
  amps/ags/rm-automation/rm-automation-community-rest-api/src/test/java/org/alfresco/rest/rm/community/smoke/DispositionScheduleLinkedRecordsTest.java
Labels: PR: reviewed-approved

#1456 ACS-3376 GET rule order within rule set.
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/rules/ReorderRules.java
  pom.xml
  remote-api/src/main/java/org/alfresco/rest/api/impl/rules/RuleSetLoader.java
  remote-api/src/main/java/org/alfresco/rest/api/model/rules/RuleSet.java
  remote-api/src/main/resources/alfresco/public-rest-context.xml
  remote-api/src/test/java/org/alfresco/rest/api/impl/rules/RuleSetLoaderTest.java
Labels: PR: unreviewed

#1461 ACS-3601: Add unlink e2es
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/rules/RuleSetLinksTests.java
  pom.xml
Labels: PR: unreviewed

#1462 ACS-3377 Update rule order.
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/rules/ReorderRules.java
  remote-api/src/main/java/org/alfresco/rest/api/RuleSets.java
  remote-api/src/main/java/org/alfresco/rest/api/impl/rules/RuleSetLoader.java
  remote-api/src/main/java/org/alfresco/rest/api/impl/rules/RuleSetsImpl.java
  remote-api/src/main/java/org/alfresco/rest/api/nodes/NodeRuleSetsRelation.java
  remote-api/src/test/java/org/alfresco/rest/api/impl/rules/RuleSetsImplTest.java
Labels: PR: partially-approved

#1465 ACS-3605 Add limit to maximum size of optional linkedToBy field.
  remote-api/src/main/java/org/alfresco/rest/api/impl/rules/RuleSetLoader.java
  remote-api/src/test/java/org/alfresco/rest/api/impl/rules/RuleSetLoaderTest.java
  repository/src/main/java/org/alfresco/repo/rule/RuleServiceImpl.java
  repository/src/main/java/org/alfresco/service/cmr/rule/RuleService.java
  repository/src/test/java/org/alfresco/repo/rule/RuleServiceImplUnitTest.java
Labels: PR: partially-approved

#1458 ACS-3525: API for manual triggering rules on a folder
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/rules/CreateRulesTests.java
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/rules/ExecuteRulesTests.java
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/rules/GetRulesTests.java
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/rules/RulesTestsUtils.java
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/rules/UpdateRulesTests.java
  pom.xml
  remote-api/src/main/java/org/alfresco/rest/api/Rules.java
  remote-api/src/main/java/org/alfresco/rest/api/impl/rules/RulesImpl.java
  remote-api/src/main/java/org/alfresco/rest/api/model/rules/RuleExecution.java
  remote-api/src/main/java/org/alfresco/rest/api/nodes/NodeRuleExecutionsRelation.java
  remote-api/src/main/resources/alfresco/public-rest-context.xml
  remote-api/src/test/java/org/alfresco/rest/api/impl/rules/RulesImplTest.java
Labels: PR: unreviewed

#1467 ACS-3643 Add meaningful message in the Workflow Console when deployment fails
  repository/src/main/java/org/alfresco/repo/workflow/WorkflowInterpreter.java
Labels: PR: unreviewed

#1468 ACS-3291 Permission checks when linking and unlinking to rule sets.
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/rules/RuleSetLinksTests.java
  remote-api/src/main/java/org/alfresco/rest/api/impl/rules/RuleSetsImpl.java
  remote-api/src/test/java/org/alfresco/rest/api/impl/rules/RuleSetsImplTest.java
Labels: PR: partially-approved

#1474 ACS-3657 Allow returning partial list of rule sets.
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/rules/GetRuleSetsTests.java
  remote-api/src/main/java/org/alfresco/rest/api/impl/rules/RuleSetsImpl.java
  remote-api/src/test/java/org/alfresco/rest/api/impl/rules/RuleSetsImplTest.java
Labels: PR: partially-approved

#1471 ACS-3620: E2Es - API for manual triggering rules on a folder
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/rules/ExecuteRulesTests.java
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/rules/RulesTestsUtils.java
Labels: PR: unreviewed

#1476 ACS-3687: Execute rules API: Remove field "isEachInheritedRuleExecuted"
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/rules/ExecuteRulesTests.java
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/rules/RulesTestsUtils.java
  pom.xml
  remote-api/src/main/java/org/alfresco/rest/api/Rules.java
  remote-api/src/main/java/org/alfresco/rest/api/impl/rules/RulesImpl.java
  remote-api/src/main/java/org/alfresco/rest/api/model/rules/RuleExecution.java
  remote-api/src/main/java/org/alfresco/rest/api/nodes/NodeRuleExecutionsRelation.java
  remote-api/src/test/java/org/alfresco/rest/api/impl/rules/RulesImplTest.java
Labels: PR: partially-approved

#1472 Fix/acs 2699 mandatory modifier
  data-model/src/main/java/org/alfresco/repo/search/impl/parsers/FTSQueryParser.java
  data-model/src/main/java/org/alfresco/repo/search/impl/querymodel/impl/lucene/LuceneDisjunction.java
Labels: PR: unreviewed

#1481 ACS-3649, ACS-3650 Action validation mechanism + validations against Action Definitions
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/rules/CreateRulesTests.java
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/rules/ExecuteRulesTests.java
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/rules/RulesTestsUtils.java
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/rules/UpdateRulesTests.java
  remote-api/src/main/java/org/alfresco/rest/api/actions/ActionConstraintsEntityResource.java
  remote-api/src/main/java/org/alfresco/rest/api/actions/ActionValidator.java
  remote-api/src/main/java/org/alfresco/rest/api/impl/ActionsImpl.java
  remote-api/src/main/java/org/alfresco/rest/api/impl/mapper/rules/RestRuleActionModelMapper.java
  remote-api/src/main/java/org/alfresco/rest/api/impl/validator/actions/ActionParameterDefinitionValidator.java
  remote-api/src/main/resources/alfresco/public-rest-context.xml
  remote-api/src/test/java/org/alfresco/rest/api/actions/ActionConstraintsEntityResourceTest.java
  remote-api/src/test/java/org/alfresco/rest/api/impl/mapper/rules/RestRuleActionModelMapperTest.java
  remote-api/src/test/java/org/alfresco/rest/api/impl/validator/actions/ActionParameterDefinitionValidatorTest.java
Labels: PR: unreviewed

#1457 ACS-3616: fix exception type for missing node id
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/rules/CreateRulesTests.java
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/rules/RuleSetLinksTests.java
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/rules/SetInheritanceTests.java
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/rules/UpdateRulesTests.java
  remote-api/src/main/java/org/alfresco/rest/api/impl/NodesImpl.java
  remote-api/src/main/java/org/alfresco/rest/api/impl/rules/NodeValidator.java
  remote-api/src/main/java/org/alfresco/rest/framework/core/exceptions/EntityNotFoundException.java
  remote-api/src/main/java/org/alfresco/rest/framework/core/exceptions/NotFoundException.java
Labels: PR: partially-approved

#1484 Update transform-core to 3.0.0-A4, transform-service to 2.0.0-A4, rem…
  pom.xml
Labels: PR: unreviewed

#1483 PRODSEC-6550 Fix CSRF on WebScripts Refresh
  packaging/war/src/main/resources/alfresco/web-client-security-config.xml
  packaging/war/src/main/webapp/WEB-INF/web.xml
  remote-api/src/main/resources/alfresco/templates/webscripts/org/springframework/extensions/webscripts/index.get.html.ftl
Labels: PR: reviewed-approved

#1488 ACS-3635 Alfresco WebDAV CSRF - allowInsecurePOSTMethod flag
  remote-api/src/main/java/org/alfresco/repo/webdav/WebDAVServlet.java
  remote-api/src/main/resources/alfresco/remote-api-context.xml
  remote-api/src/test/java/org/alfresco/AppContextExtraTestSuite.java
  remote-api/src/test/java/org/alfresco/repo/webdav/WebDAVInsecurePostMethodTest.java
  repository/src/main/resources/alfresco/repository.properties
Labels: PR: partially-approved

#1487 ACS-3651 Use Serializable for values in action parameters.
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/actions/access/AccessRestrictionUtil.java
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/actions/access/FormProcAdminAccessRestrictionTest.java
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/actions/access/pojo/Action.java
  pom.xml
Labels: PR: partially-approved

#1482 ACS-3620: E2Es - API for manual triggering rules on a folder
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/rules/ExecuteRulesTests.java
Labels: PR: partially-approved

#1489 [ACS-3678] updated InsightEngine version to 2.0.5-A2
  amps/ags/rm-community/rm-community-repo/.env
  packaging/tests/environment/.env
Labels: PR: reviewed-approved

#1491 Freemarker investigation
  repository/pom.xml
Labels: PR: reviewed-approved

#1486 Handle XSS
  amps/share-services/src/main/resources/alfresco/templates/webscripts/org/alfresco/slingshot/search/search.get.js
Labels: PR: reviewed-approved

#1492 ACS-2579 Bump freemarker to 2.3.31-alfresco-patched
  repository/pom.xml
Labels: PR: reviewed-approved

#1496 ACS-3651 Convert RulesTestsUtils to a service bean.
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/RestTest.java
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/rules/CreateRulesTests.java
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/rules/DeleteRulesTests.java
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/rules/ExecuteRulesTests.java
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/rules/GetInheritedRulesTests.java
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/rules/GetRuleSetsTests.java
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/rules/GetRulesTests.java
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/rules/ReorderRules.java
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/rules/RuleSetLinksTests.java
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/rules/RulesTestsUtils.java
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/rules/UpdateRulesTests.java
Labels: PR: unreviewed

#1497 ACS-3651 Validate node pameters.
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/rules/CreateRulesTests.java
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/rules/RulesTestsUtils.java
  remote-api/src/main/java/org/alfresco/rest/api/impl/rules/ActionParameterConverter.java
  remote-api/src/main/java/org/alfresco/rest/framework/core/exceptions/EntityNotFoundException.java
  remote-api/src/main/resources/alfresco/public-rest-context.xml
  remote-api/src/test/java/org/alfresco/rest/api/impl/rules/ActionParameterConverterTest.java
Labels: PR: unreviewed

#1498 ACS-3695 - Fix OOXML Schemas compatibility
  pom.xml
  repository/pom.xml
Labels: PR: partially-approved

#1500 Fix/test aos
  pom.xml
Labels: PR: unreviewed

#1511 Upgrade to latest ATS components
  pom.xml
Labels: PR: reviewed-approved

#1512 Revert "ACS-1600 : Error when running propTablesCleanupJob on an env …
  repository/src/main/java/org/alfresco/repo/domain/schema/script/DeleteNotExistsExecutor.java
  repository/src/main/java/org/alfresco/repo/domain/schema/script/MySQLDeleteNotExistsExecutor.java
Labels: PR: unreviewed

#1507 ACS-3652 Script node validation.
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/rules/CreateRulesTests.java
Labels: PR: unreviewed

#1514 InsightEngine version updated to 2.0.5 (ACS-3679)
  amps/ags/rm-community/rm-community-repo/.env
  packaging/tests/environment/.env
Labels: PR: reviewed-approved

#1513 ACS-3793 Permissions tests for creating rules.
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/rules/CreateRulesTests.java
Labels: PR: unreviewed

#1452 MNT-22790: exclude rules to be included in ZIP file when downloading …
  repository/src/main/java/org/alfresco/repo/download/CreateDownloadArchiveAction.java
  repository/src/test/java/org/alfresco/repo/download/DownloadServiceIntegrationTest.java
Labels: PR: reviewed-approved

#1506 ACS-3699: Add test with broken copy action
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/rules/ExecuteRulesTests.java
Labels: PR: partially-approved

#1470 feature/APPS-1672
  amps/ags/rm-automation/rm-automation-community-rest-api/src/main/java/org/alfresco/rest/v0/RMAuditAPI.java
  amps/ags/rm-automation/rm-automation-community-rest-api/src/main/java/org/alfresco/rest/v0/RecordFoldersAPI.java
  amps/ags/rm-automation/rm-automation-community-rest-api/src/main/java/org/alfresco/rest/v0/RecordsAPI.java
  amps/ags/rm-automation/rm-automation-community-rest-api/src/test/java/org/alfresco/rest/rm/community/audit/AuditHoldsTest.java
  amps/ags/rm-automation/rm-automation-community-rest-api/src/test/java/org/alfresco/rest/rm/community/audit/ElectronicRecordAuditLogTest.java
  amps/ags/rm-automation/rm-automation-community-rest-api/src/test/java/org/alfresco/rest/rm/community/audit/NonElectronicRecordAuditLogTest.java
  amps/ags/rm-automation/rm-automation-community-rest-api/src/test/java/org/alfresco/rest/rm/community/audit/RecordCategoryAuditLogTest.java
  amps/ags/rm-automation/rm-automation-community-rest-api/src/test/java/org/alfresco/rest/rm/community/audit/RecordFolderAuditLogTest.java
Labels: PR: unreviewed
