Repository Alfresco/alfresco-community-repo, pull requests merged in 2022-01, with the labels that each got.

#870 MNT-22668: missing encoded characters for some characters like ‘(’ and ‘)’
  remote-api/src/main/java/org/alfresco/repo/web/scripts/content/ContentStreamer.java
Labels: PR: reviewed-approved

#864 ACS-2245 Attempt to fix intermittent failure in FixedAclUpdaterTest
  repository/src/test/java/org/alfresco/repo/domain/permissions/FixedAclUpdaterTest.java
Labels: PR: reviewed-approved

#863 ACS-2391: StorageObjectProps - add version content specific endpoints
  remote-api/src/main/java/org/alfresco/rest/api/ContentStorageInformation.java
  remote-api/src/main/java/org/alfresco/rest/api/impl/ContentStorageInformationImpl.java
  remote-api/src/main/java/org/alfresco/rest/api/impl/RenditionsImpl.java
  remote-api/src/main/java/org/alfresco/rest/api/nodes/NodeStorageInfoRelation.java
  remote-api/src/main/java/org/alfresco/rest/api/nodes/NodeVersionsRelation.java
  remote-api/src/main/java/org/alfresco/rest/api/nodes/NodeVersionsStorageInfoRelation.java
  remote-api/src/main/java/org/alfresco/rest/api/search/impl/ResultMapper.java
  remote-api/src/main/java/org/alfresco/rest/framework/webscripts/ResourceWebScriptPost.java
  remote-api/src/main/resources/alfresco/public-rest-context.xml
  remote-api/src/test/java/org/alfresco/rest/api/impl/ContentStorageInformationImplTest.java
  remote-api/src/test/java/org/alfresco/rest/api/nodes/NodeStorageInfoRelationTest.java
  repository/src/test/java/org/alfresco/repo/version/VersionServiceImplTest.java
Labels: PR: unreviewed

#872 ACS-2242 Attempt to fix Initialization of SecureRandom in EncryptionTest
  repository/src/test/java/org/alfresco/encryption/EncryptionTests.java
Labels: PR: reviewed-approved

#834 ACS-2365 license plugin
  core/pom.xml
  data-model/pom.xml
  packaging/distribution/src/main/resources/licenses/3rd-party/BSDlike-HdrHistogram.txt
  packaging/distribution/src/main/resources/licenses/3rd-party/BSDlike-JDOM.txt
  packaging/distribution/src/main/resources/licenses/3rd-party/BSDlike-LatencyUtils.txt
  packaging/distribution/src/main/resources/licenses/3rd-party/BSDlike-ST4.txt
  packaging/distribution/src/main/resources/licenses/3rd-party/BSDlike-curvesapi.txt
  packaging/distribution/src/main/resources/licenses/3rd-party/BSDlike-jaiimageiocore.txt
  packaging/distribution/src/main/resources/licenses/3rd-party/BSDlike-jmatio.txt
  packaging/distribution/src/main/resources/licenses/3rd-party/BSDlike-protobuf.txt
  packaging/distribution/src/main/resources/licenses/3rd-party/BSDlike-unitapi.txt
  packaging/distribution/src/main/resources/licenses/3rd-party/CC-BY-2.5-jcipannotations.txt
  packaging/distribution/src/main/resources/licenses/3rd-party/EDL-1.0.txt
  packaging/distribution/src/main/resources/licenses/3rd-party/EPL-1.0.txt
  packaging/distribution/src/main/resources/licenses/3rd-party/EPL-2.0.txt
  packaging/distribution/src/main/resources/licenses/3rd-party/MIT-Brotli.txt
  packaging/distribution/src/main/resources/licenses/3rd-party/MIT-bouncycastle.txt
  packaging/distribution/src/main/resources/licenses/3rd-party/MIT-checkerqual.txt
  packaging/distribution/src/main/resources/licenses/3rd-party/MIT-ddplist.txt
  packaging/distribution/src/main/resources/licenses/3rd-party/MIT-jbzip2.txt
  packaging/distribution/src/main/resources/licenses/3rd-party/MIT-joptsimple.txt
  packaging/distribution/src/main/resources/licenses/3rd-party/MIT-jsoup.txt
  packaging/distribution/src/main/resources/licenses/3rd-party/OGC-License.txt
  packaging/distribution/src/main/resources/licenses/3rd-party/unrar.txt
  packaging/war/pom.xml
  pom.xml
  repository/pom.xml
Labels: PR: partially-approved

#867 ACS-2002 Enhance T-Router debug
  pom.xml
  repository/src/main/java/org/alfresco/repo/content/transform/AbstractLocalTransform.java
  repository/src/main/java/org/alfresco/repo/content/transform/TransformerDebug.java
  repository/src/test/java/org/alfresco/AllUnitTestsSuite.java
  repository/src/test/java/org/alfresco/repo/content/transform/TransformerDebugTest.java
Labels: PR: unreviewed

#874 Start counting transforms from 1 rather than 0, like the t-router
  repository/src/main/java/org/alfresco/repo/content/transform/TransformerDebug.java
Labels: PR: unreviewed

#878 ACS-2412 Log files flooded with transformation option messages when config is misconfigured
  repository/src/main/java/org/alfresco/transform/client/registry/CombinedConfig.java
  repository/src/main/resources/alfresco/repository.properties
Labels: PR: unreviewed

#881 ACS-2391: ACS-2391: StorageObjectProps - add version content specific endpoints
  remote-api/src/main/java/org/alfresco/rest/api/nodes/NodeVersionsStorageInfoRelation.java
Labels: PR: partially-approved

#883 ACS-2180 solr shared secret
  remote-api/src/main/java/org/alfresco/web/app/servlet/AlfrescoX509ServletFilter.java
Labels: PR: reviewed-approved

#884 ACS-2377 rest-api-explorer 7.1.1-A1 release
  pom.xml
Labels: PR: reviewed-approved

#859 ACS-2334 improve ArchivedIOException logging
  remote-api/src/main/java/org/alfresco/repo/web/scripts/RepositoryContainer.java
Labels: PR: partially-approved

#885 MNT-22563: bumped jdom2 version to 2.0.6.1
  pom.xml
Labels: PR: partially-approved

#889 ACS-2377 Upgrade rest-api-explorer to 7.1.1-A2
  pom.xml
Labels: PR: reviewed-approved

#888 ACS-2407 Upgrade rest-api-explorer to 7.2.0-A2
  pom.xml
Labels: PR: reviewed-approved

#890 Content-services - Veracode Scan Detected Vulnerabilities in Component Netty/Codec in Application ACS_EXT_MASTER
  pom.xml
Labels: PR: partially-approved

#880 MNT-22696 Replace Rendition REST API
  remote-api/src/main/java/org/alfresco/rest/api/Renditions.java
  remote-api/src/main/java/org/alfresco/rest/api/impl/RenditionsImpl.java
  remote-api/src/main/java/org/alfresco/rest/api/nodes/NodeRenditionsRelation.java
  remote-api/src/main/java/org/alfresco/rest/api/nodes/NodeVersionRenditionsRelation.java
  remote-api/src/main/java/org/alfresco/rest/framework/resource/parameters/Params.java
  remote-api/src/main/java/org/alfresco/rest/framework/webscripts/ResourceWebScriptDelete.java
  remote-api/src/test/java/org/alfresco/rest/api/tests/AbstractBaseApiTest.java
  remote-api/src/test/java/org/alfresco/rest/api/tests/NodeApiTest.java
  repository/src/main/java/org/alfresco/repo/rendition2/RenditionService2.java
  repository/src/main/java/org/alfresco/repo/rendition2/RenditionService2Impl.java
  repository/src/test/java/org/alfresco/repo/rendition2/RenditionService2IntegrationTest.java
Labels: PR: partially-approved

#895 Pick up T-Engine 2.5.5-A3
  .travis.yml
  amps/ags/rm-community/rm-community-repo/.env
  packaging/tests/environment/.env
  pom.xml
  remote-api/src/test/java/org/alfresco/rest/api/tests/SharedLinkApiTest.java
  repository/src/test/java/org/alfresco/repo/action/ActionServiceImpl2Test.java
  repository/src/test/java/org/alfresco/repo/action/executer/ContentMetadataExtracterTest.java
  repository/src/test/java/org/alfresco/repo/content/metadata/AbstractMetadataExtracterTest.java
Labels: PR: unreviewed

#896 MNT-22563: bumped jdom2 version to 2.0.6.1 (#885)
  pom.xml
Labels: PR: unreviewed

#873 MNT-22758 - Bump surf webscripts to 8.27
  pom.xml
Labels: PR: unreviewed

#899 ACS-2365 Include license report in AGS amp.
  amps/ags/rm-community/rm-community-repo/pom.xml
Labels: PR: reviewed-approved

#879 PRODSEC-5799 Upgrade mybatis
  repository/pom.xml
  repository/src/main/java/org/alfresco/ibatis/SqlSessionMetricsWrapper.java
  repository/src/main/resources/alfresco/ibatis/org.alfresco.repo.domain.dialect.Dialect/tenants-common-SqlMap.xml
  repository/src/main/resources/alfresco/ibatis/org.alfresco.repo.domain.dialect.MySQLInnoDBDialect/node-select-children-SqlMap.xml
Labels: PR: reviewed-approved

#906 ACS-2303 Gytheio is a first party library.
  pom.xml
Labels: PR: reviewed-approved

#907 ACS-2303 Include license report in share-services amp.
  amps/share-services/pom.xml
Labels: PR: reviewed-approved

#908 ACS-2104: Changing apache.camel and netty-codec-http dependency versions
  pom.xml
Labels: PR: partially-approved

#917 ACS-2104: Remove Camel exclusion from DependABot
  .github/dependabot.yml
Labels: PR: partially-approved
