Repository Alfresco/alfresco-community-repo, pull requests merged in 2022-05, with the labels that each got.

#1096 MNT-22968 - Bump Freemarker
  repository/pom.xml
Labels: PR: unreviewed

#1095 MNT-22968 - Bump Freemarker
  repository/pom.xml
Labels: PR: unreviewed

#1097 MNT-22968 - Bump Freemarker
  repository/pom.xml
Labels: PR: unreviewed

#1094 MNT-22968 - Bump Freemarker
  repository/pom.xml
Labels: PR: unreviewed

#1093 MNT-22968 - Bump Freemarker
  repository/pom.xml
Labels: PR: unreviewed

#1108 [ACS-2747] Prevent private action execution from the V1 HTTP API
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/actions/ActionsTests.java
  remote-api/src/main/java/org/alfresco/rest/api/impl/ActionsImpl.java
  remote-api/src/main/resources/alfresco/public-rest-context.xml
Labels: PR: reviewed-approved

#1107 Mnt 22905/case sensitive query fix
  remote-api/src/main/resources/alfresco/templates/webscripts/org/alfresco/repository/person/people.get.js
  remote-api/src/main/resources/alfresco/templates/webscripts/org/alfresco/repository/site/membership/potentialmembers.get.js
  remote-api/src/test/java/org/alfresco/repo/web/scripts/person/PersonServiceTest.java
Labels: PR: unreviewed

#1089 ACS-2925: Elasticsearch - refactor DB switching to not use Solr-specific properties / debug log
  repository/src/main/java/org/alfresco/repo/content/transform/LocalPipelineTransform.java
  repository/src/main/java/org/alfresco/repo/search/impl/DbCmisQueryLanguage.java
  repository/src/main/java/org/alfresco/repo/search/impl/DbOrIndexSwitchingQueryLanguage.java
  repository/src/main/java/org/alfresco/repo/search/impl/DisabledFeatureException.java
  repository/src/main/java/org/alfresco/repo/search/impl/OpenCMISQueryServiceImpl.java
  repository/src/main/resources/alfresco/subsystems/Search/common-opencmis-context.xml
  repository/src/main/resources/alfresco/subsystems/Search/common-search-context.xml
  repository/src/main/resources/alfresco/subsystems/Search/noindex/common-search.properties
  repository/src/main/resources/alfresco/subsystems/Search/noindex/noindex-search-context.xml
  repository/src/main/resources/alfresco/subsystems/Search/noindex/opencmis-context.xml
  repository/src/main/resources/alfresco/subsystems/Search/solr/common-search.properties
  repository/src/main/resources/alfresco/subsystems/Search/solr/opencmis-context.xml
  repository/src/main/resources/alfresco/subsystems/Search/solr/solr-search-context.xml
  repository/src/main/resources/alfresco/subsystems/Search/solr4/common-search.properties
  repository/src/main/resources/alfresco/subsystems/Search/solr4/opencmis-context.xml
  repository/src/main/resources/alfresco/subsystems/Search/solr4/solr-search-context.xml
  repository/src/main/resources/alfresco/subsystems/Search/solr6/common-search.properties
  repository/src/main/resources/alfresco/subsystems/Search/solr6/opencmis-context.xml
  repository/src/main/resources/alfresco/subsystems/Search/solr6/solr-search-context.xml
  repository/src/test/java/org/alfresco/repo/search/SearchServiceTest.java
  repository/src/test/java/org/alfresco/repo/search/impl/solr/DbOrIndexSwitchingQueryLanguageTest.java
Labels: PR: unreviewed

#1130 ACS-2800: Replace throwing NPE to CmisInvalidArgumentException
  data-model/src/main/java/org/alfresco/opencmis/mapping/ObjectTypeIdLuceneBuilder.java
Labels: PR: partially-approved

#1125 ACS-2827: Add Search Tests To CMIS-TAS
  packaging/tests/tas-cmis/src/test/java/org/alfresco/cmis/search/AbstractCmisE2ETest.java
  packaging/tests/tas-cmis/src/test/java/org/alfresco/cmis/search/AbstractE2EFunctionalTest.java
  packaging/tests/tas-cmis/src/test/java/org/alfresco/cmis/search/SearchInFolderTests.java
  packaging/tests/tas-cmis/src/test/resources/default.properties
  packaging/tests/tas-cmis/src/test/resources/search-in-folder.xml
Labels: PR: partially-approved

#1135 ACS-2888 - add usage of bean with security interceptor.
  repository/src/main/resources/alfresco/action-services-context.xml
Labels: PR: reviewed-approved

#1139 [ACS-3006] Revert changes made to implement a validation logic
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/actions/ActionsTests.java
  remote-api/src/main/java/org/alfresco/rest/api/impl/ActionsImpl.java
  remote-api/src/main/resources/alfresco/public-rest-context.xml
  repository/src/main/java/org/alfresco/repo/action/ActionExecutionContext.java
  repository/src/main/java/org/alfresco/repo/action/ActionServiceImpl.java
  repository/src/main/java/org/alfresco/repo/action/RuntimeActionService.java
  repository/src/main/resources/alfresco/action-services-context.xml
  repository/src/test/java/org/alfresco/AllUnitTestsSuite.java
  repository/src/test/java/org/alfresco/repo/action/ActionServiceImplTest.java
  repository/src/test/java/org/alfresco/repo/action/PrivateActionValidationTest.java
  repository/src/test/resources/org/alfresco/repo/action/test-action-services-context.xml
Labels: PR: partially-approved

#1141 ACS-3013: Uppercasing services used to allow security proxy
  repository/src/main/resources/alfresco/action-services-context.xml
Labels: PR: reviewed-approved
