Repository Alfresco/alfresco-community-repo, pull requests merged in 2022-11, with the labels that each got.

#1534 MNT-23276 - Protect from null facet names
  repository/src/main/java/org/alfresco/repo/search/impl/solr/SolrJSONResultSet.java
Labels: PR: reviewed-approved

#1538 ACS-3855: Add validation for rule condition comparator.
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/rules/CreateRulesTests.java
  remote-api/src/main/java/org/alfresco/rest/api/impl/mapper/rules/RestRuleSimpleConditionModelMapper.java
  remote-api/src/test/java/org/alfresco/rest/api/impl/mapper/rules/RestRuleSimpleConditionModelMapperTest.java
Labels: PR: partially-approved

#1536 MNT-23276 - Protect from null facet names
  amps/ags/rm-automation/rm-automation-community-rest-api/src/test/java/org/alfresco/rest/rm/community/records/DeleteRecordTests.java
  repository/src/main/java/org/alfresco/repo/search/impl/solr/SolrJSONResultSet.java
Labels: PR: unreviewed

#1537 MNT-23276 - Protect from null facet names (#1534)
  amps/ags/rm-automation/rm-automation-community-rest-api/src/test/java/org/alfresco/rest/rm/community/records/DeleteRecordTests.java
  repository/src/main/java/org/alfresco/repo/search/impl/solr/SolrJSONResultSet.java
Labels: PR: unreviewed

#1533 Feature/acs-3644 Allow multiple docker-copose files
  packaging/tests/scripts/start-compose.sh
Labels: PR: partially-approved

#1532 [MNT-22353]- Removed Hold cases to be processed in DispositionLifecycleJob
  amps/ags/rm-community/rm-community-repo/source/java/org/alfresco/module/org_alfresco_module_rm/job/DispositionLifecycleJobExecuter.java
  amps/ags/rm-community/rm-community-repo/unit-test/java/org/alfresco/module/org_alfresco_module_rm/job/DispositionLifecycleJobExecuterUnitTest.java
Labels: PR: reviewed-approved

#1540 MNT-23276 - The null facet name should be considered
  repository/src/main/java/org/alfresco/repo/search/impl/solr/SolrJSONResultSet.java
Labels: PR: reviewed-approved

#1544 MNT-23276 - The null facet name should be considered (#1540)
  repository/src/main/java/org/alfresco/repo/search/impl/solr/SolrJSONResultSet.java
Labels: PR: unreviewed

#1535 MNT-22485: audit query with createdAt criteria returns correct totalI…
  remote-api/src/main/java/org/alfresco/rest/api/impl/AuditImpl.java
  remote-api/src/test/java/org/alfresco/rest/api/tests/AuditAppTest.java
  repository/src/main/java/org/alfresco/repo/audit/AuditComponent.java
  repository/src/main/java/org/alfresco/repo/audit/AuditComponentImpl.java
  repository/src/main/java/org/alfresco/repo/audit/AuditServiceImpl.java
  repository/src/main/java/org/alfresco/repo/domain/audit/AbstractAuditDAOImpl.java
  repository/src/main/java/org/alfresco/repo/domain/audit/AuditDAO.java
  repository/src/main/java/org/alfresco/repo/domain/audit/ibatis/AuditDAOImpl.java
  repository/src/main/java/org/alfresco/service/cmr/audit/AuditService.java
  repository/src/main/resources/alfresco/ibatis/org.alfresco.repo.domain.dialect.Dialect/audit-common-SqlMap.xml
Labels: PR: partially-approved

#1547 MNT-22485: added missing tables to query
  repository/src/main/resources/alfresco/ibatis/org.alfresco.repo.domain.dialect.Dialect/audit-common-SqlMap.xml
Labels: PR: partially-approved

#1545 MNT-22485: audit query with createdAt criteria returns correct totalI…
  remote-api/src/main/java/org/alfresco/rest/api/impl/AuditImpl.java
  remote-api/src/test/java/org/alfresco/rest/api/tests/AuditAppTest.java
  repository/src/main/java/org/alfresco/repo/audit/AuditComponent.java
  repository/src/main/java/org/alfresco/repo/audit/AuditComponentImpl.java
  repository/src/main/java/org/alfresco/repo/audit/AuditServiceImpl.java
  repository/src/main/java/org/alfresco/repo/domain/audit/AbstractAuditDAOImpl.java
  repository/src/main/java/org/alfresco/repo/domain/audit/AuditDAO.java
  repository/src/main/java/org/alfresco/repo/domain/audit/ibatis/AuditDAOImpl.java
  repository/src/main/java/org/alfresco/service/cmr/audit/AuditService.java
  repository/src/main/resources/alfresco/ibatis/org.alfresco.repo.domain.dialect.Dialect/audit-common-SqlMap.xml
Labels: PR: unreviewed

#1519 [MNT-23158] Scripts limits configuration and optimization
  repository/src/main/java/org/alfresco/repo/jscript/AlfrescoContextFactory.java
  repository/src/main/java/org/alfresco/repo/jscript/AlfrescoScriptContext.java
  repository/src/main/java/org/alfresco/repo/jscript/AlfrescoScriptThreadMxBeanWrapper.java
  repository/src/main/java/org/alfresco/repo/jscript/RhinoScriptProcessor.java
  repository/src/main/resources/alfresco/repository.properties
  repository/src/main/resources/alfresco/script-services-context.xml
  repository/src/test/java/org/alfresco/repo/jscript/RhinoScriptTest.java
Labels: PR: unreviewed

#1551 [MNT-23158] Scripts limits configuration and optimization (#1519)
  repository/src/main/java/org/alfresco/repo/jscript/AlfrescoContextFactory.java
  repository/src/main/java/org/alfresco/repo/jscript/AlfrescoScriptContext.java
  repository/src/main/java/org/alfresco/repo/jscript/AlfrescoScriptThreadMxBeanWrapper.java
  repository/src/main/java/org/alfresco/repo/jscript/RhinoScriptProcessor.java
  repository/src/main/resources/alfresco/repository.properties
  repository/src/main/resources/alfresco/script-services-context.xml
  repository/src/test/java/org/alfresco/repo/jscript/RhinoScriptTest.java
Labels: PR: unreviewed

#1552 [MNT-23158] Scripts limits configuration and optimization (#1519)
  repository/src/main/java/org/alfresco/repo/jscript/AlfrescoContextFactory.java
  repository/src/main/java/org/alfresco/repo/jscript/AlfrescoScriptContext.java
  repository/src/main/java/org/alfresco/repo/jscript/AlfrescoScriptThreadMxBeanWrapper.java
  repository/src/main/java/org/alfresco/repo/jscript/RhinoScriptProcessor.java
  repository/src/main/resources/alfresco/repository.properties
  repository/src/main/resources/alfresco/script-services-context.xml
  repository/src/test/java/org/alfresco/repo/jscript/RhinoScriptTest.java
Labels: PR: unreviewed

#1550 MNT-23276 - The null facet name should be considered (#1540)
  repository/src/main/java/org/alfresco/repo/search/impl/solr/SolrJSONResultSet.java
Labels: PR: unreviewed

#1553 [MNT-23158] Scripts limits configuration and optimization (#1519)
  repository/src/main/java/org/alfresco/repo/jscript/AlfrescoContextFactory.java
  repository/src/main/java/org/alfresco/repo/jscript/AlfrescoScriptContext.java
  repository/src/main/java/org/alfresco/repo/jscript/AlfrescoScriptThreadMxBeanWrapper.java
  repository/src/main/java/org/alfresco/repo/jscript/RhinoScriptProcessor.java
  repository/src/main/resources/alfresco/repository.properties
  repository/src/main/resources/alfresco/script-services-context.xml
  repository/src/test/java/org/alfresco/repo/jscript/RhinoScriptTest.java
Labels: PR: unreviewed

#1548 [MNT-23158] Scripts limits configuration and optimization (#1519)
  repository/src/main/java/org/alfresco/repo/jscript/AlfrescoContextFactory.java
  repository/src/main/java/org/alfresco/repo/jscript/AlfrescoScriptContext.java
  repository/src/main/java/org/alfresco/repo/jscript/AlfrescoScriptThreadMxBeanWrapper.java
  repository/src/main/java/org/alfresco/repo/jscript/RhinoScriptProcessor.java
  repository/src/main/resources/alfresco/repository.properties
  repository/src/main/resources/alfresco/script-services-context.xml
  repository/src/test/java/org/alfresco/repo/jscript/RhinoScriptTest.java
Labels: PR: unreviewed

#1549 [MNT-23158] Scripts limits configuration and optimization (#1519)
  repository/src/main/java/org/alfresco/repo/jscript/AlfrescoContextFactory.java
  repository/src/main/java/org/alfresco/repo/jscript/AlfrescoScriptContext.java
  repository/src/main/java/org/alfresco/repo/jscript/AlfrescoScriptThreadMxBeanWrapper.java
  repository/src/main/java/org/alfresco/repo/jscript/RhinoScriptProcessor.java
  repository/src/main/resources/alfresco/repository.properties
  repository/src/main/resources/alfresco/script-services-context.xml
  repository/src/test/java/org/alfresco/repo/jscript/RhinoScriptTest.java
Labels: PR: unreviewed

#1555 [MNT-23158] Scripts limits configuration and optimization (#1519)
  .travis.yml
  repository/src/main/java/org/alfresco/repo/jscript/AlfrescoContextFactory.java
  repository/src/main/java/org/alfresco/repo/jscript/AlfrescoScriptContext.java
  repository/src/main/java/org/alfresco/repo/jscript/AlfrescoScriptThreadMxBeanWrapper.java
  repository/src/main/java/org/alfresco/repo/jscript/RhinoScriptProcessor.java
  repository/src/main/resources/alfresco/repository.properties
  repository/src/main/resources/alfresco/script-services-context.xml
  repository/src/test/java/org/alfresco/repo/jscript/RhinoScriptTest.java
Labels: PR: unreviewed

#1559 MNT-23108 - Manage contentStream resource closure
  repository/src/main/java/org/alfresco/repo/content/transform/RemoteTransformerClient.java
Labels: PR: reviewed-approved

#1558 MNT-23204: Group Search
  remote-api/src/main/resources/alfresco/templates/webscripts/org/alfresco/repository/site/membership/potentialmembers.get.js
Labels: PR: reviewed-approved

#1567 MNT-23330 - Downloading a document replaces filename having space wit…
  remote-api/src/main/java/org/alfresco/repo/web/scripts/content/ContentStreamer.java
  remote-api/src/test/java/org/alfresco/rest/api/tests/NodeApiTest.java
  remote-api/src/test/resources/publicapi/upload/Test Download (1).txt
Labels: PR: unreviewed

#1566 MNT-23330 - Downloading a document replaces filename having space wit…
  remote-api/src/main/java/org/alfresco/repo/web/scripts/content/ContentStreamer.java
  remote-api/src/test/java/org/alfresco/rest/api/tests/NodeApiTest.java
  remote-api/src/test/resources/publicapi/upload/Test Download (1).txt
Labels: PR: unreviewed

#1531 Feature/apps 1722
  amps/ags/rm-automation/rm-automation-community-rest-api/src/test/java/org/alfresco/rest/rm/community/rules/CopyToRuleOnFoldersTest.java
  amps/ags/rm-automation/rm-automation-community-rest-api/src/test/java/org/alfresco/rest/rm/community/rules/FileAsRecordRuleTests.java
  amps/ags/rm-automation/rm-automation-community-rest-api/src/test/java/org/alfresco/rest/rm/community/rules/FileVersionAsRecordRuleTest.java
  amps/ags/rm-automation/rm-automation-community-rest-api/src/test/java/org/alfresco/rest/rm/community/rules/MoveToRuleOnFoldersTest.java
Labels: PR: reviewed-approved

#1569 Fix/mnt 22686 allow complex rest action params
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/actions/email/EmailTemplateTest.java
  packaging/tests/tas-restapi/src/test/resources/shared-resources/testdata/simpleEmailTemplate.ftl
  remote-api/src/main/java/org/alfresco/rest/api/impl/ActionsImpl.java
  remote-api/src/main/java/org/alfresco/rest/api/model/Action.java
  remote-api/src/test/java/org/alfresco/rest/api/tests/client/data/Action.java
Labels: PR: reviewed-approved

#1565 ACS-3964: fix for non-inheritable rules still appearing in inherited rule sets
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/rules/GetInheritedRulesTests.java
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/rules/RulesTestsUtils.java
  remote-api/src/main/java/org/alfresco/rest/api/impl/rules/RulesImpl.java
  remote-api/src/main/resources/alfresco/public-rest-context.xml
  remote-api/src/test/java/org/alfresco/rest/api/impl/rules/RulesImplTest.java
Labels: PR: partially-approved

#1576 MNT-22686 Load template from the classpath
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/actions/email/EmailTemplateTest.java
Labels: PR: partially-approved

#1577 ACS-4064: fix for linking from a folder with inherited rules
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/rules/RuleSetLinksTests.java
  remote-api/src/main/java/org/alfresco/rest/api/impl/rules/RuleSetsImpl.java
  remote-api/src/test/java/org/alfresco/rest/api/impl/rules/RuleSetsImplTest.java
  repository/src/main/java/org/alfresco/repo/rule/RuleServiceImpl.java
  repository/src/main/java/org/alfresco/service/cmr/rule/RuleService.java
Labels: PR: unreviewed

#1578 [ACS-4053] updated INSIGHT_ENGINE_TAG and SOLR tag to 2.0.5.1
  amps/ags/rm-community/rm-community-repo/.env
  packaging/tests/environment/.env
Labels: PR: reviewed-approved

#1572 Feature/RM-7178 Event apis swagger
  amps/ags/rm-community/rm-community-rest-api-explorer/src/main/webapp/definitions/gs-core-api.yaml
Labels: PR: unreviewed

#1564 MNT-23108 - Manage contentStream resource closure in RemoteTransforme…
  repository/src/main/java/org/alfresco/repo/content/transform/RemoteTransformerClient.java
Labels: PR: unreviewed

#1587 MNT-23204: Group Search (#1558)
  remote-api/src/main/resources/alfresco/templates/webscripts/org/alfresco/repository/site/membership/potentialmembers.get.js
Labels: PR: unreviewed
