Repository Alfresco/alfresco-community-repo, pull requests merged in 2022-09, with the labels that each got.

#1358 MNT-23176 - Revert "ACS-1600 : Error when running propTablesCleanupJob on an env …
  repository/src/main/java/org/alfresco/repo/domain/schema/script/DeleteNotExistsExecutor.java
  repository/src/main/java/org/alfresco/repo/domain/schema/script/MySQLDeleteNotExistsExecutor.java
Labels: PR: reviewed-approved

#1363 Revert "ACS-1600 : Error when running propTablesCleanupJob on an env …
  repository/src/main/java/org/alfresco/repo/domain/schema/script/DeleteNotExistsExecutor.java
  repository/src/main/java/org/alfresco/repo/domain/schema/script/MySQLDeleteNotExistsExecutor.java
Labels: PR: unreviewed

#1365 Fix/mnt 23190 queries to find users not returning results
  amps/share-services/src/main/resources/alfresco/templates/webscripts/org/alfresco/slingshot/search/live-search-people.get.js
  remote-api/src/main/resources/alfresco/templates/webscripts/org/alfresco/repository/forms/pickerchildren.get.js
Labels: PR: partially-approved

#1323 ACS-3280 Get inherited rule sets. [tas]
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/rules/GetRuleSetsTests.java
  remote-api/src/main/java/org/alfresco/rest/api/impl/rules/RuleSetsImpl.java
  remote-api/src/test/java/org/alfresco/rest/api/impl/rules/RuleSetsImplTest.java
  repository/src/main/java/org/alfresco/repo/rule/RuleServiceImpl.java
  repository/src/main/java/org/alfresco/service/cmr/rule/RuleService.java
  repository/src/test/java/org/alfresco/repo/rule/RuleServiceImplUnitTest.java
Labels: PR: unreviewed

#1372 ACS-3485: Change naming for rule sets
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/rules/RuleSetLinksTests.java
  remote-api/src/main/java/org/alfresco/rest/api/impl/rules/RuleSetsImpl.java
  remote-api/src/main/java/org/alfresco/rest/api/model/rules/RuleSetLink.java
Labels: PR: partially-approved

#1369 [MNT-21377] Prevent LDAP checks from running multiple times
  repository/src/main/java/org/alfresco/repo/security/authentication/ldap/LDAPInitialDirContextFactoryImpl.java
  repository/src/main/resources/alfresco/cache-context.xml
  repository/src/main/resources/alfresco/caches.properties
  repository/src/main/resources/alfresco/subsystems/Authentication/common-ldap-context.xml
  repository/src/main/resources/alfresco/subsystems/Authentication/ldap-ad/ldap-ad-authentication.properties
  repository/src/main/resources/alfresco/subsystems/Authentication/ldap/ldap-authentication.properties
Labels: PR: unreviewed

#1374 ACS-3533 Disabling scan on PR builds.
  .travis.yml
Labels: PR: unreviewed

#1322 ACS-3402: Camel upgrade
  pom.xml
Labels: PR: unreviewed

#1356 ACS-3430: POST support for conditions
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/rules/CreateRulesTests.java
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/rules/RulesTestsUtils.java
  remote-api/src/main/java/org/alfresco/rest/api/impl/rules/NodeValidator.java
  remote-api/src/main/java/org/alfresco/rest/api/impl/rules/RuleLoader.java
  remote-api/src/main/java/org/alfresco/rest/api/impl/rules/RulesImpl.java
  remote-api/src/main/java/org/alfresco/rest/api/model/rules/CompositeCondition.java
  remote-api/src/main/java/org/alfresco/rest/api/model/rules/Rule.java
  remote-api/src/main/java/org/alfresco/rest/api/model/rules/SimpleCondition.java
  remote-api/src/main/java/org/alfresco/rest/api/nodes/NodeRulesRelation.java
  remote-api/src/main/resources/alfresco/public-rest-context.xml
  remote-api/src/test/java/org/alfresco/rest/api/impl/rules/RulesImplTest.java
  remote-api/src/test/java/org/alfresco/rest/api/model/rules/CompositeConditionTest.java
  remote-api/src/test/java/org/alfresco/rest/api/model/rules/RuleTest.java
  remote-api/src/test/java/org/alfresco/rest/api/model/rules/SimpleConditionTest.java
  repository/src/main/java/org/alfresco/repo/action/ParameterizedItemImpl.java
  repository/src/main/java/org/alfresco/service/cmr/rule/RuleService.java
Labels: PR: partially-approved

#1383 ACS-3536 Omit actionContext for rules.
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/rules/CreateRulesTests.java
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/rules/GetRulesTests.java
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/rules/RulesTestsUtils.java
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/rules/UpdateRulesTests.java
  remote-api/src/main/java/org/alfresco/rest/api/model/rules/Action.java
Labels: PR: unreviewed

#1384 ACS-3402: Add actual dependency, not just dependencyManagement
  repository/pom.xml
Labels: PR: reviewed-approved

#1321 HXENG-64 refactor ATS prior to fork
  pom.xml
  remote-api/src/main/java/org/alfresco/repo/web/scripts/content/MimetypesGet.java
  repository/src/main/java/org/alfresco/repo/content/metadata/AsynchronousExtractor.java
  repository/src/main/java/org/alfresco/repo/content/transform/AbstractLocalTransform.java
  repository/src/main/java/org/alfresco/repo/content/transform/AdminUiTransformerDebug.java
  repository/src/main/java/org/alfresco/repo/content/transform/DummyTransformServiceRegistry.java
  repository/src/main/java/org/alfresco/repo/content/transform/LocalFailoverTransform.java
  repository/src/main/java/org/alfresco/repo/content/transform/LocalPassThroughTransform.java
  repository/src/main/java/org/alfresco/repo/content/transform/LocalPipelineTransform.java
  repository/src/main/java/org/alfresco/repo/content/transform/LocalTransformImpl.java
  repository/src/main/java/org/alfresco/repo/content/transform/LocalTransformServiceRegistry.java
  repository/src/main/java/org/alfresco/repo/rendition2/LocalSynchronousTransformClient.java
  repository/src/main/java/org/alfresco/repo/rendition2/LocalTransformClient.java
  repository/src/main/java/org/alfresco/repo/rendition2/RenditionDefinitionRegistry2Impl.java
  repository/src/main/java/org/alfresco/repo/rendition2/SwitchingTransformServiceRegistry.java
  repository/src/main/java/org/alfresco/repo/thumbnail/ThumbnailRegistry.java
  repository/src/main/java/org/alfresco/transform/registry/CombinedConfig.java
  repository/src/main/java/org/alfresco/transform/registry/TransformServiceRegistryImpl.java
  repository/src/test/java/org/alfresco/AppContext06TestSuite.java
  repository/src/test/java/org/alfresco/repo/action/executer/AsynchronousExtractorTest.java
  repository/src/test/java/org/alfresco/repo/rendition2/AbstractRenditionIntegrationTest.java
  repository/src/test/java/org/alfresco/repo/rendition2/AbstractRenditionTest.java
  repository/src/test/java/org/alfresco/repo/rendition2/LocalRenditionTest.java
  repository/src/test/java/org/alfresco/repo/rendition2/LocalSynchronousTransformClientIntegrationTest.java
  repository/src/test/java/org/alfresco/repo/rendition2/LocalTransformServiceRegistryIntegrationTest.java
  repository/src/test/java/org/alfresco/repo/rendition2/RenditionService2Test.java
  repository/src/test/java/org/alfresco/repo/rendition2/TestTransformServiceRegistry.java
  repository/src/test/java/org/alfresco/transform/registry/LocalTransformServiceRegistryConfigTest.java
  repository/src/test/resources/alfresco/local-transform-service-config-pipeline-test.json
  repository/src/test/resources/alfresco/transforms/0999-testPipeline.json
Labels: PR: unreviewed

#1284 Feature/apps 1613
  amps/ags/rm-automation/rm-automation-community-rest-api/src/main/java/org/alfresco/rest/v0/LinksAPI.java
  amps/ags/rm-automation/rm-automation-community-rest-api/src/main/java/org/alfresco/rest/v0/RecordCategoriesAPI.java
  amps/ags/rm-automation/rm-automation-community-rest-api/src/test/java/org/alfresco/rest/rm/community/records/DeclareInPlaceRecordsTestLevel2.java
  amps/ags/rm-automation/rm-automation-community-rest-api/src/test/java/org/alfresco/rest/rm/community/records/DeleteRecordTests.java
  amps/ags/rm-automation/rm-automation-community-rest-api/src/test/java/org/alfresco/rest/rm/community/records/ShareRecordsTest.java
  amps/ags/rm-automation/rm-automation-community-rest-api/src/test/java/org/alfresco/rest/rm/community/smoke/DestroyRecordFolderActionsTest.java
  amps/ags/rm-automation/rm-automation-community-rest-api/src/test/java/org/alfresco/rest/rm/community/smoke/DispositionScheduleLinkedRecordsTest.java
  amps/ags/rm-automation/rm-automation-community-rest-api/src/test/java/org/alfresco/rest/rm/community/smoke/FileVersionAsRecordTests.java
  amps/ags/rm-automation/rm-automation-community-rest-api/src/test/java/org/alfresco/rest/rm/community/smoke/RecordRetentionAsOfDateTest.java
Labels: PR: reviewed-approved

#1376 ACS-3429: Better fitting exceptions on POST rule with actions
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/rules/CreateRulesTests.java
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/rules/UpdateRulesTests.java
  remote-api/src/main/java/org/alfresco/rest/api/impl/rules/ActionParameterConverter.java
  remote-api/src/main/java/org/alfresco/rest/api/impl/rules/RulesImpl.java
  remote-api/src/test/java/org/alfresco/rest/api/impl/rules/ActionParameterConverterTest.java
  remote-api/src/test/java/org/alfresco/rest/api/impl/rules/RulesImplTest.java
Labels: PR: unreviewed

#1389 ACS-3354: Adding TAS test for update rule (other) fields.
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/rules/CreateRulesTests.java
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/rules/RulesTestsUtils.java
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/rules/UpdateRulesTests.java
Labels: PR: partially-approved

#1396 ACS-3363 Output TAS logs for failed tests.
  .travis.yml
  packaging/tests/scripts/output_logs_for_failures.sh
Labels: PR: partially-approved

#1397 Update Javadoc to clarify variable use
  remote-api/src/main/java/org/alfresco/rest/api/model/rules/RuleSetLink.java
Labels: PR: partially-approved

#1388 ACS-3354 Rule mappers pt1 (simple condition mapper)
  remote-api/src/main/java/org/alfresco/rest/api/impl/mapper/rules/RestRuleSimpleConditionModelMapper.java
  remote-api/src/main/java/org/alfresco/rest/api/impl/rules/RuleLoader.java
  remote-api/src/main/java/org/alfresco/rest/api/impl/rules/RulesImpl.java
  remote-api/src/main/java/org/alfresco/rest/api/model/mapper/RestModelMapper.java
  remote-api/src/main/java/org/alfresco/rest/api/model/rules/CompositeCondition.java
  remote-api/src/main/java/org/alfresco/rest/api/model/rules/Rule.java
  remote-api/src/main/java/org/alfresco/rest/api/model/rules/SimpleCondition.java
  remote-api/src/main/resources/alfresco/public-rest-context.xml
  remote-api/src/test/java/org/alfresco/rest/api/RulesUnitTests.java
  remote-api/src/test/java/org/alfresco/rest/api/impl/mapper/rules/RestRuleSimpleConditionModelMapperTest.java
  remote-api/src/test/java/org/alfresco/rest/api/impl/rules/RulesImplTest.java
  remote-api/src/test/java/org/alfresco/rest/api/model/rules/CompositeConditionTest.java
  remote-api/src/test/java/org/alfresco/rest/api/model/rules/RuleTest.java
  remote-api/src/test/java/org/alfresco/rest/api/model/rules/SimpleConditionTest.java
Labels: PR: partially-approved

#1402 ACS-3364 Add support for linkedToBy field in GET rule sets.
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/rules/GetRuleSetsTests.java
  pom.xml
  remote-api/src/main/java/org/alfresco/rest/api/impl/rules/RuleSetLoader.java
  remote-api/src/main/java/org/alfresco/rest/api/model/rules/RuleSet.java
  remote-api/src/test/java/org/alfresco/rest/api/impl/rules/RuleSetLoaderTest.java
Labels: PR: partially-approved

#1416 Revert "Bump dependency.poi.version from 5.2.2 to 5.2.3"
  pom.xml
Labels: PR: unreviewed

#1415 ACS-3365 Add support for GET rule sets isInherited.
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/rules/GetRuleSetsTests.java
  remote-api/src/main/java/org/alfresco/rest/api/impl/rules/RuleSetLoader.java
  remote-api/src/main/java/org/alfresco/rest/api/model/rules/RuleSet.java
  remote-api/src/test/java/org/alfresco/rest/api/impl/rules/RuleSetLoaderTest.java
Labels: PR: unreviewed

#1409 Encoding to handle XSS
  amps/share-services/src/main/resources/alfresco/templates/webscripts/org/alfresco/slingshot/search/search.get.js
Labels: PR: reviewed-approved

#1411 ACS-3509: Adding E2E TAS REST tests for update rule conditions.
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/rules/UpdateRulesTests.java
Labels: PR: partially-approved

#1425 ACS-3364 Add permission handling to linkedToBy.
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/rules/GetRuleSetsTests.java
  remote-api/src/main/java/org/alfresco/rest/api/impl/rules/RuleSetLoader.java
  repository/src/main/java/org/alfresco/repo/rule/RuleServiceImpl.java
  repository/src/main/java/org/alfresco/service/cmr/rule/RuleService.java
  repository/src/test/java/org/alfresco/repo/rule/RuleServiceImplUnitTest.java
Labels: PR: partially-approved

#1428 ACS-3509 Rule mappers refactor pt2
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/rules/CreateRulesTests.java
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/rules/GetRulesTests.java
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/rules/UpdateRulesTests.java
  remote-api/src/main/java/org/alfresco/rest/api/impl/mapper/rules/RestRuleCompositeConditionModelMapper.java
  remote-api/src/main/java/org/alfresco/rest/api/impl/mapper/rules/RestRuleSimpleConditionModelMapper.java
  remote-api/src/main/java/org/alfresco/rest/api/impl/rules/RuleLoader.java
  remote-api/src/main/java/org/alfresco/rest/api/impl/rules/RulesImpl.java
  remote-api/src/main/java/org/alfresco/rest/api/model/mapper/RestModelMapper.java
  remote-api/src/main/java/org/alfresco/rest/api/model/rules/CompositeCondition.java
  remote-api/src/main/java/org/alfresco/rest/api/model/rules/Rule.java
  remote-api/src/main/java/org/alfresco/rest/api/model/rules/SimpleCondition.java
  remote-api/src/main/resources/alfresco/public-rest-context.xml
  remote-api/src/test/java/org/alfresco/rest/api/RulesUnitTests.java
  remote-api/src/test/java/org/alfresco/rest/api/impl/mapper/rules/RestRuleCompositeConditionModelMapperTest.java
  remote-api/src/test/java/org/alfresco/rest/api/impl/mapper/rules/RestRuleSimpleConditionModelMapperTest.java
  remote-api/src/test/java/org/alfresco/rest/api/impl/rules/RulesImplTest.java
  remote-api/src/test/java/org/alfresco/rest/api/model/rules/CompositeConditionTest.java
  remote-api/src/test/java/org/alfresco/rest/api/model/rules/RuleTest.java
  remote-api/src/test/java/org/alfresco/rest/api/model/rules/SimpleConditionTest.java
Labels: PR: partially-approved

#1420 Feature/acs 3555 add custom embedded workflow license code
  repository/src/main/java/org/alfresco/repo/descriptor/DescriptorStartupLog.java
  repository/src/main/java/org/alfresco/service/license/LicenseDescriptor.java
Labels: PR: reviewed-approved

#1424 MNT-22233 resolved error while loading subcategory with cutoff.
  amps/ags/rm-community/rm-community-repo/source/java/org/alfresco/module/org_alfresco_module_rm/jscript/app/JSONConversionComponent.java
Labels: PR: unreviewed

#1210 [MNT-21638] Script task execution
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/workflow/deployments/GetDeploymentsSanityTests.java
  remote-api/src/test/java/org/alfresco/rest/workflow/api/tests/DeploymentWorkflowApiTest.java
  repository/src/main/java/org/alfresco/repo/jscript/RhinoScriptProcessor.java
  repository/src/main/java/org/alfresco/repo/processor/ScriptServiceImpl.java
  repository/src/main/java/org/alfresco/repo/workflow/WorkflowComponent.java
  repository/src/main/java/org/alfresco/repo/workflow/WorkflowDeployer.java
  repository/src/main/java/org/alfresco/repo/workflow/WorkflowServiceImpl.java
  repository/src/main/java/org/alfresco/repo/workflow/activiti/ActivitiWorkflowEngine.java
  repository/src/main/java/org/alfresco/repo/workflow/activiti/script/ActivitiScriptBase.java
  repository/src/main/java/org/alfresco/service/cmr/repository/ScriptProcessor.java
  repository/src/main/java/org/alfresco/service/cmr/repository/ScriptService.java
  repository/src/main/java/org/alfresco/service/cmr/workflow/WorkflowService.java
  repository/src/test/java/org/alfresco/repo/jscript/RhinoScriptTest.java
  repository/src/test/java/org/alfresco/repo/workflow/AbstractWorkflowServiceIntegrationTest.java
  repository/src/test/java/org/alfresco/repo/workflow/activiti/ActivitiWorkflowServiceIntegrationTest.java
  repository/src/test/resources/activiti/test-MNT21638-1.bpmn20.xml
  repository/src/test/resources/activiti/test-MNT21638-2.bpmn20.xml
Labels: PR: unreviewed

#1429 Revert "Feature/acs 3560 discovery api for custom embedded workflow license"
  remote-api/src/main/java/org/alfresco/rest/api/model/RepositoryInfo.java
  remote-api/src/test/java/org/alfresco/rest/api/tests/DiscoveryApiTest.java
Labels: PR: unreviewed

#1432 Feature/acs 3555 add custom embedded workflow license code
  remote-api/src/main/java/org/alfresco/rest/api/model/RepositoryInfo.java
  remote-api/src/test/java/org/alfresco/rest/api/tests/DiscoveryApiTest.java
  repository/src/main/java/org/alfresco/service/license/LicenseDescriptor.java
Labels: PR: unreviewed

#1330 MNT-23043 - Property Tables Cleaner Job V3
  repository/src/main/java/org/alfresco/repo/attributes/PropTablesCleaner.java
  repository/src/main/java/org/alfresco/repo/domain/propval/PropertyValueDAO.java
  repository/src/main/java/org/alfresco/repo/domain/propval/ibatis/PropertyValueDAOImpl.java
  repository/src/main/java/org/alfresco/repo/domain/schema/script/DeleteNotExistsExecutor.java
  repository/src/main/java/org/alfresco/repo/domain/schema/script/DeleteNotExistsV3Executor.java
  repository/src/main/java/org/alfresco/repo/domain/schema/script/MySQLDeleteNotExistsExecutor.java
  repository/src/main/java/org/alfresco/repo/domain/schema/script/ScriptExecutorImpl.java
  repository/src/main/resources/alfresco/dbscripts/utility/org.alfresco.repo.domain.dialect.MySQLInnoDBDialect/CleanAlfPropTablesV3.sql
  repository/src/main/resources/alfresco/dbscripts/utility/org.alfresco.repo.domain.dialect.PostgreSQLDialect/CleanAlfPropTablesV3.sql
  repository/src/main/resources/alfresco/repository.properties
  repository/src/test/java/org/alfresco/AllDBTestsTestSuite.java
  repository/src/test/java/org/alfresco/repo/domain/schema/script/DeleteNotExistsV3ExecutorTest.java
Labels: PR: unreviewed

#1436 ACS-3359 Rename boolean rule fields.
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/rules/GetRulesTests.java
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/rules/RulesTestsUtils.java
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/rules/UpdateRulesTests.java
  pom.xml
  remote-api/src/main/java/org/alfresco/rest/api/model/rules/Rule.java
  remote-api/src/test/java/org/alfresco/rest/api/impl/rules/RuleLoaderTest.java
  remote-api/src/test/java/org/alfresco/rest/api/model/rules/RuleTest.java
Labels: PR: unreviewed

#1437 Update transform-core to 3.0.0-A3. Update transform-servce to 2.0.0-A3
  pom.xml
Labels: PR: unreviewed

#1426 [MNT-23118] Allow import with long paths
  repository/src/main/java/org/alfresco/repo/importer/ImporterComponent.java
Labels: PR: reviewed-approved

#1434 MNT-23174 - RM upgrade from 3.4.1.1 to 11.153 fails
  amps/ags/rm-community/rm-community-repo/config/alfresco/module/org_alfresco_module_rm/alfresco-global.properties
  amps/ags/rm-community/rm-community-repo/config/alfresco/module/org_alfresco_module_rm/patch/rm-patch-v35-context.xml
  amps/ags/rm-community/rm-community-repo/source/java/org/alfresco/module/org_alfresco_module_rm/patch/v35/RMv35HoldNewChildAssocPatch.java
  amps/ags/rm-community/rm-community-repo/unit-test/java/org/alfresco/module/org_alfresco_module_rm/patch/v35/RMv35HoldNewChildAssocPatchUnitTest.java
Labels: PR: unreviewed

#1435 ACS-3589 Merge TAS CMIS into community repo.
  packaging/tests/tas-cmis/README.md
  packaging/tests/tas-cmis/docs/CHANGELOG.md
  packaging/tests/tas-cmis/docs/pics/html-report-sample.JPG
  packaging/tests/tas-cmis/docs/pics/html-report-sample.png
  packaging/tests/tas-cmis/docs/pics/xml-steps-report.JPG
  packaging/tests/tas-cmis/pom.xml
  packaging/tests/tas-cmis/src/main/java/org/alfresco/cmis/AuthParameterProviderFactory.java
  packaging/tests/tas-cmis/src/main/java/org/alfresco/cmis/CmisProperties.java
  packaging/tests/tas-cmis/src/main/java/org/alfresco/cmis/CmisWrapper.java
  packaging/tests/tas-cmis/src/main/java/org/alfresco/cmis/dsl/BaseObjectType.java
  packaging/tests/tas-cmis/src/main/java/org/alfresco/cmis/dsl/CheckIn.java
  packaging/tests/tas-cmis/src/main/java/org/alfresco/cmis/dsl/CmisAssertion.java
  packaging/tests/tas-cmis/src/main/java/org/alfresco/cmis/dsl/CmisUtil.java
  packaging/tests/tas-cmis/src/main/java/org/alfresco/cmis/dsl/DocumentVersioning.java
  packaging/tests/tas-cmis/src/main/java/org/alfresco/cmis/dsl/JmxUtil.java
  packaging/tests/tas-cmis/src/main/java/org/alfresco/cmis/dsl/QueryExecutor.java
  packaging/tests/tas-cmis/src/main/java/org/alfresco/cmis/exception/InvalidCmisObjectException.java
  packaging/tests/tas-cmis/src/main/java/org/alfresco/cmis/exception/UnrecognizedBinding.java
  packaging/tests/tas-cmis/src/main/resources/alfresco-cmis-context.xml
  packaging/tests/tas-cmis/src/main/resources/default.properties
  packaging/tests/tas-cmis/src/main/resources/log4j.properties
Labels: PR: partially-approved

#1438 ACS-3510 Rule mappers refactor pt3
  remote-api/src/main/java/org/alfresco/rest/api/impl/mapper/rules/RestRuleActionModelMapper.java
  remote-api/src/main/java/org/alfresco/rest/api/impl/mapper/rules/RestRuleCompositeConditionModelMapper.java
  remote-api/src/main/java/org/alfresco/rest/api/impl/mapper/rules/RestRuleModelMapper.java
  remote-api/src/main/java/org/alfresco/rest/api/impl/rules/ActionParameterConverter.java
  remote-api/src/main/java/org/alfresco/rest/api/impl/rules/RuleLoader.java
  remote-api/src/main/java/org/alfresco/rest/api/impl/rules/RulesImpl.java
  remote-api/src/main/java/org/alfresco/rest/api/model/mapper/RestModelMapper.java
  remote-api/src/main/java/org/alfresco/rest/api/model/rules/Action.java
  remote-api/src/main/java/org/alfresco/rest/api/model/rules/Rule.java
  remote-api/src/main/resources/alfresco/public-rest-context.xml
  remote-api/src/test/java/org/alfresco/rest/api/RulesUnitTests.java
  remote-api/src/test/java/org/alfresco/rest/api/impl/mapper/rules/RestRuleActionModelMapperTest.java
  remote-api/src/test/java/org/alfresco/rest/api/impl/mapper/rules/RestRuleCompositeConditionModelMapperTest.java
  remote-api/src/test/java/org/alfresco/rest/api/impl/mapper/rules/RestRuleModelMapperTest.java
  remote-api/src/test/java/org/alfresco/rest/api/impl/mapper/rules/RestRuleSimpleConditionModelMapperTest.java
  remote-api/src/test/java/org/alfresco/rest/api/impl/rules/RuleLoaderTest.java
  remote-api/src/test/java/org/alfresco/rest/api/impl/rules/RulesImplTest.java
  remote-api/src/test/java/org/alfresco/rest/api/model/rules/ActionTest.java
  remote-api/src/test/java/org/alfresco/rest/api/model/rules/RuleTest.java
Labels: PR: unreviewed

#1421 ACS-3291: Support for unlinking rule sets
  remote-api/src/main/java/org/alfresco/rest/api/RuleSets.java
  remote-api/src/main/java/org/alfresco/rest/api/impl/rules/RuleSetsImpl.java
  remote-api/src/main/java/org/alfresco/rest/api/nodes/NodeRuleSetLinksRelation.java
  remote-api/src/test/java/org/alfresco/rest/api/impl/rules/RuleSetsImplTest.java
  remote-api/src/test/java/org/alfresco/rest/api/nodes/NodeRuleSetsRelationTest.java
Labels: PR: partially-approved

#1444 Fix/mnt 23174 r mv35 hold new child assoc patch 711 hf
  amps/ags/rm-automation/rm-automation-community-rest-api/src/test/java/org/alfresco/rest/rm/community/records/DeleteRecordTests.java
  amps/ags/rm-community/rm-community-repo/config/alfresco/module/org_alfresco_module_rm/alfresco-global.properties
  amps/ags/rm-community/rm-community-repo/config/alfresco/module/org_alfresco_module_rm/patch/rm-patch-v35-context.xml
  amps/ags/rm-community/rm-community-repo/source/java/org/alfresco/module/org_alfresco_module_rm/patch/v35/RMv35HoldNewChildAssocPatch.java
  amps/ags/rm-community/rm-community-repo/unit-test/java/org/alfresco/module/org_alfresco_module_rm/patch/v35/RMv35HoldNewChildAssocPatchUnitTest.java
Labels: PR: unreviewed

#1445 ACS-3594 Add mechanism to deprecate modules within the Repo
  repository/src/main/java/org/alfresco/repo/module/DeprecatedModulesValidator.java
  repository/src/main/resources/alfresco/messages/module-messages.properties
  repository/src/main/resources/alfresco/module-context.xml
  repository/src/test/java/org/alfresco/AllUnitTestsSuite.java
  repository/src/test/java/org/alfresco/repo/module/DeprecatedModulesValidatorTest.java
Labels: PR: partially-approved

#1446 ACS-3488 Remove xml data provider.
  packaging/tests/tas-cmis/pom.xml
  packaging/tests/tas-cmis/src/main/java/org/alfresco/cmis/dsl/QueryExecutor.java
  packaging/tests/tas-cmis/src/test/java/org/alfresco/cmis/search/AbstractCmisE2ETest.java
  packaging/tests/tas-cmis/src/test/java/org/alfresco/cmis/search/SearchInFolderTests.java
Labels: PR: reviewed-approved

#1422 ACS-3563 Workflow Licence Check
  repository/src/main/java/org/alfresco/repo/workflow/WorkflowDeployer.java
  repository/src/main/java/org/alfresco/repo/workflow/activiti/ActivitiWorkflowManagerFactory.java
  repository/src/main/java/org/alfresco/service/cmr/workflow/FailedWorkflowDeployment.java
  repository/src/main/resources/alfresco/bootstrap-context.xml
Labels: PR: reviewed-approved

#1450 MNT-23174 - RM upgrade from 3.4.1.1 to 11.153 fails (#1434)
  amps/ags/rm-automation/rm-automation-community-rest-api/src/test/java/org/alfresco/rest/rm/community/records/DeleteRecordTests.java
  amps/ags/rm-community/rm-community-repo/config/alfresco/module/org_alfresco_module_rm/alfresco-global.properties
  amps/ags/rm-community/rm-community-repo/config/alfresco/module/org_alfresco_module_rm/patch/rm-patch-v35-context.xml
  amps/ags/rm-community/rm-community-repo/source/java/org/alfresco/module/org_alfresco_module_rm/patch/v35/RMv35HoldNewChildAssocPatch.java
  amps/ags/rm-community/rm-community-repo/unit-test/java/org/alfresco/module/org_alfresco_module_rm/patch/v35/RMv35HoldNewChildAssocPatchUnitTest.java
Labels: PR: unreviewed

#1451 ACS-3427: Add GET e2es for actions and conditions
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/rules/CreateRulesTests.java
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/rules/GetRulesTests.java
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/rules/RulesTestsUtils.java
Labels: PR: reviewed-approved

#1454 [MNT-23241] Prevent duplicated default headers if key/value pair is already in the request, otherwise, header is added
  core/src/main/java/org/alfresco/httpclient/RequestHeadersHttpClient.java
Labels: PR: reviewed-approved

#1460 Feature/acs 3623 descriptor startup log
  pom.xml
  repository/src/main/java/org/alfresco/repo/descriptor/DescriptorStartupLog.java
Labels: PR: reviewed-approved
