Repository Alfresco/alfresco-community-repo, pull requests merged in 2022-03, with the labels that each got.

#983 ATS-983 Downgrade reload4j
  core/pom.xml
  repository/src/test/java/org/alfresco/AllUnitTestsSuite.java
  repository/src/test/java/org/alfresco/repo/management/CheckRequiredClassesForLoggingConsoleUnitTest.java
Labels: PR: partially-approved

#988 ACS-2493/ACS-2494 Repo Transform requests using a DAU
  pom.xml
  repository/src/main/java/org/alfresco/repo/content/transform/LocalPipelineTransform.java
  repository/src/main/java/org/alfresco/repo/content/transform/LocalTransformServiceRegistry.java
  repository/src/main/java/org/alfresco/repo/rendition2/LocalSynchronousTransformClient.java
  repository/src/main/java/org/alfresco/repo/rendition2/LocalTransformClient.java
  repository/src/main/resources/alfresco/rendition-services2-context.xml
  repository/src/main/resources/alfresco/repository.properties
Labels: PR: unreviewed

#995 Bump dependency.tas-restapi from 1.71 to 1.77
  pom.xml
Labels: PR: unreviewed

#996 Revert "Bump dependency.tas-restapi from 1.71 to 1.77"
  pom.xml
Labels: PR: unreviewed

#993 cm:versionable mandatory aspect cause the node creation REST API to create 2 versions instead of one
  remote-api/src/main/java/org/alfresco/rest/api/impl/NodesImpl.java
  remote-api/src/test/java/org/alfresco/AppContext02TestSuite.java
  remote-api/src/test/java/org/alfresco/rest/api/tests/NodeApiVersioningJsonParameterizedTest.java
  remote-api/src/test/java/org/alfresco/rest/api/tests/NodeApiVersioningMultipartParameterizedTest.java
  remote-api/src/test/resources/models/custom-model.xml
Labels: PR: reviewed-approved

#999 [MNT-22462] 7.2.0-A4 rest-api-explorer version bump
  pom.xml
Labels: PR: reviewed-approved

#1000 ACS-2627 Upgrade base docker images
  packaging/docker-alfresco/Dockerfile
Labels: PR: reviewed-approved

#994 Feature/acs 2562 disallow secure comms none
  amps/ags/rm-community/rm-community-repo/.env
  amps/ags/rm-community/rm-community-repo/docker-compose.yml
  amps/ags/rm-community/rm-community-repo/src/test/properties/local/alfresco-global.properties
  packaging/tests/environment/.env
  packaging/tests/environment/docker-compose-minimal+transforms.yml
  packaging/tests/environment/docker-compose-minimal.yml
  remote-api/src/main/java/org/alfresco/web/app/servlet/AlfrescoX509ServletFilter.java
  remote-api/src/test/java/org/alfresco/AppContextExtraTestSuite.java
  remote-api/src/test/java/org/alfresco/web/app/servlet/AlfrescoX509ServletFilterTest.java
Labels: PR: unreviewed

#1001 ACS-2631 Upgrade AOS module
  pom.xml
Labels: PR: partially-approved

#1008 ACS-2614 Upgrade REST-API-explorer to 7.2.0
  pom.xml
Labels: PR: partially-approved

#1007 ACS-2318 Upgrade base docker images
  packaging/docker-alfresco/Dockerfile
Labels: PR: partially-approved

#1009 ACS-1987 Bump dependency tas-restapi from 1.78 to 1.79
  pom.xml
Labels: PR: unreviewed

#1012 ACS-2318 Upgrade tomcat base docker images
  packaging/docker-alfresco/Dockerfile
Labels: PR: partially-approved

#1013 ACS-2307 Update SS/IE to 2.0.3-RC4
  amps/ags/rm-community/rm-community-repo/.env
  packaging/tests/environment/.env
Labels: PR: partially-approved

#649 Feature/acs 1601 Node cleanup job improvements for Postgres
  core/pom.xml
  core/src/main/java/org/alfresco/util/transaction/ConnectionPoolException.java
  pom.xml
  repository/pom.xml
  repository/src/main/java/org/alfresco/heartbeat/ConfigurationDataCollector.java
  repository/src/main/java/org/alfresco/heartbeat/SystemUsageDataCollector.java
  repository/src/main/java/org/alfresco/repo/domain/node/AbstractNodeDAOImpl.java
  repository/src/main/java/org/alfresco/repo/domain/node/NodeDAO.java
  repository/src/main/java/org/alfresco/repo/domain/node/ibatis/NodeDAOImpl.java
  repository/src/main/java/org/alfresco/repo/node/db/DeletedNodeCleanupWorker.java
  repository/src/main/java/org/alfresco/repo/tenant/TenantBasicDataSource.java
  repository/src/main/java/org/alfresco/repo/tenant/TenantRoutingDataSource.java
  repository/src/main/resources/alfresco/activiti-context.xml
  repository/src/main/resources/alfresco/core-services-context.xml
  repository/src/main/resources/alfresco/ibatis/alfresco-SqlMapConfig.xml
  repository/src/main/resources/alfresco/ibatis/org.alfresco.repo.domain.dialect.Dialect/node-common-SqlMap.xml
  repository/src/main/resources/alfresco/ibatis/org.alfresco.repo.domain.dialect.Dialect/node-delete-SqlMap.xml
  repository/src/main/resources/alfresco/ibatis/org.alfresco.repo.domain.dialect.Dialect/node-select-SqlMap.xml
  repository/src/main/resources/alfresco/ibatis/org.alfresco.repo.domain.dialect.MySQLInnoDBDialect/node-delete-SqlMap.xml
  repository/src/main/resources/alfresco/ibatis/org.alfresco.repo.domain.dialect.MySQLInnoDBDialect/node-select-SqlMap.xml
  repository/src/main/resources/alfresco/node-services-context.xml
  repository/src/main/resources/alfresco/repository.properties
  repository/src/test/java/org/alfresco/AllDBTestsTestSuite.java
  repository/src/test/java/org/alfresco/AppContext03TestSuite.java
  repository/src/test/java/org/alfresco/heartbeat/ConfigurationDataCollectorTest.java
  repository/src/test/java/org/alfresco/heartbeat/SystemUsageDataCollectorTest.java
  repository/src/test/java/org/alfresco/repo/node/cleanup/DeletedNodeBatchCleanupTest.java
  repository/src/test/java/org/alfresco/repo/node/cleanup/TransactionCleanupTest.java
  repository/src/test/resources/ibatis/hierarchy-test/hierarchy-test-context.xml
  repository/src/test/resources/test-database-context.xml
  repository/src/test/resources/test/alfresco/test-database-context.xml
Labels: PR: partially-approved

#1014 ACS-2307 Update IE/SS to 2.0.3-RC5
  amps/ags/rm-community/rm-community-repo/.env
  packaging/tests/environment/.env
Labels: PR: partially-approved

#1016 ACS-2658 Fix missing metadata extraction while uploading new version
  remote-api/src/main/resources/alfresco/templates/webscripts/org/alfresco/repository/upload/upload.post.js
Labels: PR: reviewed-approved

#1020 ACS-2307 Update IE/SS to 2.0.3
  amps/ags/rm-community/rm-community-repo/.env
  packaging/tests/environment/.env
Labels: PR: partially-approved

#992 ACS-2608 Support force directive.
  .travis.yml
  scripts/travis/update_downstream.sh
Labels: PR: partially-approved

#1019 [ACS-962] - Attempt to fix concurrency failing in test.
  repository/src/test/java/org/alfresco/opencmis/OpenCmisLocalTest.java
  repository/src/test/java/org/alfresco/repo/lock/JobLockServiceTest.java
  repository/src/test/java/org/alfresco/util/TestHelper.java
Labels: PR: unreviewed
