Repository Alfresco/alfresco-community-repo, pull requests merged in 2022-04, with the labels that each got.

#1055 Fix/mnt 22946 spring rce databind jdk9 72 n
  pom.xml
Labels: PR: unreviewed

#1051 ACS-2744 Private action validation logic
  repository/src/main/java/org/alfresco/repo/action/ActionExecutionContext.java
  repository/src/main/java/org/alfresco/repo/action/ActionServiceImpl.java
  repository/src/main/java/org/alfresco/repo/action/RuntimeActionService.java
  repository/src/main/resources/alfresco/action-services-context.xml
  repository/src/test/java/org/alfresco/AllUnitTestsSuite.java
  repository/src/test/java/org/alfresco/repo/action/ActionServiceImplTest.java
  repository/src/test/java/org/alfresco/repo/action/PrivateActionValidationTest.java
  repository/src/test/resources/org/alfresco/repo/action/test-action-services-context.xml
Labels: PR: unreviewed

#1056 Fix/mnt 22946 spring rce databind jdk9 71 n
  pom.xml
Labels: PR: unreviewed

#1065 ACS-1970 Switch to the alfresco/alfresco-base-tomcat:9.0.52-java-11-c…
  packaging/docker-alfresco/Dockerfile
Labels: PR: reviewed-approved

#1058 Fix/mnt 22946 spring rce databind jdk9 70 n
  pom.xml
  repository/src/main/java/org/alfresco/repo/management/SafeApplicationEventMulticaster.java
Labels: PR: partially-approved

#1073 ACS-2674 - fix/ACS-2674_delete_existing_rendition
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/renditions/RenditionIntegrationTests.java
  pom.xml
Labels: PR: partially-approved

#1074 Fix/acs 2851 intermittent integration full tests bulk 2
  packaging/tests/tas-integration/src/test/java/org/alfresco/tas/integration/IntegrationFullTestsBulk2.java
Labels: PR: reviewed-approved

#1067 ACS-2768 Automate update of t-router and t-engine references in repositories
  .travis.yml
  amps/ags/rm-community/rm-community-repo/.env
  packaging/tests/environment/.env
  pom.xml
  repository/pom.xml
Labels: PR: unreviewed

#1077 Bump freemarker
  repository/pom.xml
Labels: PR: unreviewed

#1080 Bump freemarker
  repository/pom.xml
Labels: PR: unreviewed

#1078 Bump freemarker
  repository/pom.xml
Labels: PR: unreviewed

#1081 ACS-2768 Fix of Automate update of t-router and t-engine references in repositories
  amps/ags/rm-community/rm-community-repo/.env
  packaging/tests/environment/.env
  packaging/tests/scripts/start-compose.sh
Labels: PR: unreviewed
