Repository Alfresco/alfresco-community-repo, pull requests merged in 2022-08, with the labels that each got.

#1253 ACS-3347 Upgrade to Java 17
  .travis.yml
  amps/ags/pom.xml
  packaging/docker-alfresco/Dockerfile
  packaging/tests/tas-integration/pom.xml
  packaging/tests/tas-restapi/pom.xml
  repository/src/test/java/org/alfresco/repo/action/executer/AbstractMailActionExecuterTest.java
  repository/src/test/java/org/alfresco/repo/content/transform/LocalTransformServiceRegistryTest.java
  repository/src/test/java/org/alfresco/repo/imap/ImapMessageTest.java
  repository/src/test/java/org/alfresco/repo/model/ml/tools/ContentFilterLanguagesMapTest.java
Labels: PR: partially-approved

#1245 ACS-3229: Rules v1 REST API - Get rule definition - mapping of actions
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/rules/CreateRulesTests.java
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/rules/DeleteRulesTests.java
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/rules/GetRulesTests.java
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/rules/RulesTestsUtils.java
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/rules/UpdateRulesTests.java
  remote-api/src/main/java/org/alfresco/rest/api/model/rules/Action.java
  remote-api/src/main/java/org/alfresco/rest/api/model/rules/Rule.java
  remote-api/src/test/java/org/alfresco/rest/api/RulesUnitTests.java
  remote-api/src/test/java/org/alfresco/rest/api/model/rules/ActionTest.java
  remote-api/src/test/java/org/alfresco/rest/api/model/rules/RuleTest.java
  repository/src/main/java/org/alfresco/repo/rule/RuleServiceImpl.java
  repository/src/test/java/org/alfresco/repo/rule/RuleServiceImplUnitTest.java
Labels: PR: unreviewed

#1262 ACS-3227: REST API TAS test for create rule with consumer role.
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/rules/CreateRulesTests.java
Labels: PR: partially-approved

#1263 ACS-3360 GET APIs for rule sets.
  remote-api/src/main/java/org/alfresco/rest/api/RuleSets.java
  remote-api/src/main/java/org/alfresco/rest/api/impl/rules/NodeValidator.java
  remote-api/src/main/java/org/alfresco/rest/api/impl/rules/RuleSetsImpl.java
  remote-api/src/main/java/org/alfresco/rest/api/impl/rules/RulesImpl.java
  remote-api/src/main/java/org/alfresco/rest/api/model/rules/RuleSet.java
  remote-api/src/main/java/org/alfresco/rest/api/nodes/NodeRuleSetsRelation.java
  remote-api/src/main/resources/alfresco/public-rest-context.xml
  remote-api/src/test/java/org/alfresco/rest/api/RulesUnitTests.java
  remote-api/src/test/java/org/alfresco/rest/api/impl/RulesImplTest.java
  remote-api/src/test/java/org/alfresco/rest/api/impl/rules/NodeValidatorTest.java
  remote-api/src/test/java/org/alfresco/rest/api/impl/rules/RuleSetsImplTest.java
  remote-api/src/test/java/org/alfresco/rest/api/impl/rules/RulesImplTest.java
Labels: PR: partially-approved

#1272 ACS-3381: Implement Rule Permission e2es
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/rules/CreateRulesTests.java
Labels: PR: reviewed-approved

#1266 ACS-3316 Fix HTML sanitisation bypass
  amps/share-services/src/test/java/org/alfresco/slingshot/web/scripts/SlingshotContentGetTest.java
  remote-api/src/main/java/org/alfresco/repo/web/scripts/MimeTypeUtil.java
  remote-api/src/main/java/org/alfresco/repo/web/scripts/content/ContentGet.java
  remote-api/src/main/java/org/alfresco/repo/web/scripts/content/ContentInfo.java
  remote-api/src/main/java/org/alfresco/repo/web/scripts/content/ContentStreamer.java
  remote-api/src/main/resources/alfresco/web-scripts-application-context.xml
  remote-api/src/test/java/org/alfresco/repo/web/scripts/content/ContentGetTest.java
Labels: PR: partially-approved

#1212 Feature/apps 1550
  amps/ags/rm-automation/rm-automation-community-rest-api/src/main/java/org/alfresco/rest/v0/RecordFoldersAPI.java
  amps/ags/rm-automation/rm-automation-community-rest-api/src/test/java/org/alfresco/rest/rm/community/base/BaseRMRestTest.java
  amps/ags/rm-automation/rm-automation-community-rest-api/src/test/java/org/alfresco/rest/rm/community/smoke/AuditAccessTests.java
  amps/ags/rm-automation/rm-automation-community-rest-api/src/test/java/org/alfresco/rest/rm/community/smoke/BasicRulesIntegrationTests.java
  amps/ags/rm-automation/rm-automation-community-rest-api/src/test/java/org/alfresco/rest/rm/community/smoke/CreateCategoriesTests.java
  amps/ags/rm-automation/rm-automation-community-rest-api/src/test/java/org/alfresco/rest/rm/community/smoke/CreateFoldersTests.java
  amps/ags/rm-automation/rm-automation-community-rest-api/src/test/java/org/alfresco/rest/rm/community/smoke/DeclareDocsAsRecordsOnUpdateRuleNewVersionTests.java
  amps/ags/rm-automation/rm-automation-community-rest-api/src/test/java/org/alfresco/rest/rm/community/smoke/FileAsRecordTests.java
  amps/ags/rm-automation/rm-automation-community-rest-api/src/test/java/org/alfresco/rest/rm/community/smoke/FoldersDispositionScheduleTests.java
  amps/ags/rm-automation/rm-automation-community-rest-api/src/test/java/org/alfresco/rest/rm/community/smoke/FoldersDispositionScheduleWithoutGhostRecordTests.java
  amps/ags/rm-automation/rm-automation-community-rest-api/src/test/java/org/alfresco/rest/rm/community/smoke/RecordsDispositionScheduleTests.java
  amps/ags/rm-automation/rm-automation-community-rest-api/src/test/java/org/alfresco/rest/rm/community/smoke/RecordsDispositionScheduleWithGhostingTests.java
  amps/ags/rm-automation/rm-automation-community-rest-api/src/test/java/org/alfresco/rest/rm/community/smoke/UnfiledRecordsRuleTests.java
Labels: PR: partially-approved

#1280 ACS_3362 GET rule set can include optional owningFolder field.
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/rules/GetRuleSetsTests.java
  pom.xml
  remote-api/src/main/java/org/alfresco/rest/api/impl/rules/NodeValidator.java
  remote-api/src/main/java/org/alfresco/rest/api/impl/rules/RuleSetLoader.java
  remote-api/src/main/java/org/alfresco/rest/api/impl/rules/RuleSetsImpl.java
  remote-api/src/main/java/org/alfresco/rest/api/model/rules/RuleSet.java
  remote-api/src/main/resources/alfresco/public-rest-context.xml
  remote-api/src/test/java/org/alfresco/rest/api/impl/rules/RuleSetLoaderTest.java
  remote-api/src/test/java/org/alfresco/rest/api/impl/rules/RuleSetsImplTest.java
Labels: PR: partially-approved

#1285 Update rest-assured version to 5.1.1, link to newer tas-restapi arti…
  pom.xml
Labels: PR: unreviewed

#1286 ACS-3361 Support for inclusionType.
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/rules/GetRuleSetsTests.java
  pom.xml
  remote-api/src/main/java/org/alfresco/rest/api/impl/rules/RuleSetLoader.java
  remote-api/src/main/java/org/alfresco/rest/api/impl/rules/RuleSetsImpl.java
  remote-api/src/main/java/org/alfresco/rest/api/model/rules/InclusionType.java
  remote-api/src/main/java/org/alfresco/rest/api/model/rules/RuleSet.java
  remote-api/src/test/java/org/alfresco/rest/api/impl/rules/RuleSetLoaderTest.java
  remote-api/src/test/java/org/alfresco/rest/api/impl/rules/RuleSetsImplTest.java
Labels: PR: partially-approved

#1301 ACS-3358 Support isShared field.
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/rules/CreateRulesTests.java
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/rules/GetRuleSetsTests.java
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/rules/GetRulesTests.java
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/rules/UpdateRulesTests.java
  pom.xml
  remote-api/src/main/java/org/alfresco/rest/api/Rules.java
  remote-api/src/main/java/org/alfresco/rest/api/impl/rules/RuleLoader.java
  remote-api/src/main/java/org/alfresco/rest/api/impl/rules/RuleSetLoader.java
  remote-api/src/main/java/org/alfresco/rest/api/impl/rules/RulesImpl.java
  remote-api/src/main/java/org/alfresco/rest/api/model/rules/Rule.java
  remote-api/src/main/java/org/alfresco/rest/api/nodes/NodeRulesRelation.java
  remote-api/src/main/resources/alfresco/public-rest-context.xml
  remote-api/src/test/java/org/alfresco/rest/api/impl/rules/RuleLoaderTest.java
  remote-api/src/test/java/org/alfresco/rest/api/impl/rules/RulesImplTest.java
  remote-api/src/test/java/org/alfresco/rest/api/model/rules/RuleTest.java
  remote-api/src/test/java/org/alfresco/rest/api/nodes/NodeRulesRelationTest.java
  remote-api/src/test/java/org/alfresco/rest/framework/tests/core/ParamsExtender.java
Labels: PR: unreviewed

#1269 ACS-3290: V1 REST API endpoint for linking to ruleset
  remote-api/src/main/java/org/alfresco/rest/api/RuleSets.java
  remote-api/src/main/java/org/alfresco/rest/api/impl/rules/RuleSetsImpl.java
  remote-api/src/main/java/org/alfresco/rest/api/model/rules/RuleSetLink.java
  remote-api/src/main/java/org/alfresco/rest/api/nodes/NodeRuleSetLinksRelation.java
  remote-api/src/main/resources/alfresco/public-rest-context.xml
  remote-api/src/test/java/org/alfresco/rest/api/impl/rules/RuleSetsImplTest.java
  remote-api/src/test/java/org/alfresco/rest/api/nodes/NodeRuleSetsRelationTest.java
Labels: PR: unreviewed

#1316 Change exception type for failing tests
  remote-api/src/test/java/org/alfresco/rest/api/impl/rules/RuleSetsImplTest.java
Labels: PR: reviewed-approved

#1304 ACS-3316 Fix custom models downloading and XSS
  amps/share-services/src/test/java/org/alfresco/slingshot/web/scripts/SlingshotContentGetTest.java
  remote-api/src/main/java/org/alfresco/repo/web/scripts/MimeTypeUtil.java
  remote-api/src/main/java/org/alfresco/repo/web/scripts/content/ContentGet.java
  remote-api/src/main/java/org/alfresco/repo/web/scripts/content/ContentInfo.java
  remote-api/src/main/java/org/alfresco/repo/web/scripts/content/ContentStreamer.java
  remote-api/src/main/java/org/alfresco/rest/api/impl/CustomModelsImpl.java
  remote-api/src/main/resources/alfresco/web-scripts-application-context.xml
  remote-api/src/test/java/org/alfresco/repo/web/scripts/content/ContentGetTest.java
Labels: PR: partially-approved

#1317 ACS-3280 Is inheritance enabled rule settings.
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/rules/SetInheritanceTests.java
  pom.xml
  remote-api/src/main/java/org/alfresco/rest/api/RuleSettings.java
  remote-api/src/main/java/org/alfresco/rest/api/impl/rules/RuleSettingsImpl.java
  remote-api/src/main/java/org/alfresco/rest/api/model/rules/RuleSet.java
  remote-api/src/main/java/org/alfresco/rest/api/model/rules/RuleSetting.java
  remote-api/src/main/java/org/alfresco/rest/api/nodes/NodeRuleSettingsRelation.java
  remote-api/src/main/resources/alfresco/public-rest-context.xml
  remote-api/src/test/java/org/alfresco/rest/api/impl/rules/RuleSetsImplTest.java
  remote-api/src/test/java/org/alfresco/rest/api/impl/rules/RuleSettingsImplTest.java
Labels: PR: partially-approved

#1287 ACS-3353: POST support for "other fields"
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/rules/CreateRulesTests.java
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/rules/RulesTestsUtils.java
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/rules/UpdateRulesTests.java
  remote-api/src/main/java/org/alfresco/rest/api/model/rules/Rule.java
  remote-api/src/main/java/org/alfresco/rest/api/model/rules/RuleTrigger.java
  remote-api/src/test/java/org/alfresco/rest/api/RulesUnitTests.java
  remote-api/src/test/java/org/alfresco/rest/api/model/rules/RuleTest.java
Labels: PR: unreviewed

#1305 ACS-3429 post support for actions
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/rules/CreateRulesTests.java
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/rules/RulesTestsUtils.java
  remote-api/src/main/java/org/alfresco/repo/web/scripts/rule/AbstractRuleWebScript.java
  remote-api/src/main/java/org/alfresco/rest/api/impl/rules/ActionParameterConverter.java
  remote-api/src/main/java/org/alfresco/rest/api/impl/rules/ActionPermissionValidator.java
  remote-api/src/main/java/org/alfresco/rest/api/impl/rules/RulesImpl.java
  remote-api/src/main/java/org/alfresco/rest/api/model/rules/Action.java
  remote-api/src/main/resources/alfresco/public-rest-context.xml
  remote-api/src/test/java/org/alfresco/rest/api/impl/rules/ActionParameterConverterTest.java
  remote-api/src/test/java/org/alfresco/rest/api/impl/rules/ActionPermissionValidatorTest.java
  remote-api/src/test/java/org/alfresco/rest/api/impl/rules/RulesImplTest.java
Labels: PR: unreviewed

#1320 ACS-3316 Fix custom models downloading and XSS Backport
  amps/share-services/src/test/java/org/alfresco/slingshot/web/scripts/SlingshotContentGetTest.java
  remote-api/src/main/java/org/alfresco/repo/web/scripts/MimeTypeUtil.java
  remote-api/src/main/java/org/alfresco/repo/web/scripts/content/ContentGet.java
  remote-api/src/main/java/org/alfresco/repo/web/scripts/content/ContentInfo.java
  remote-api/src/main/java/org/alfresco/repo/web/scripts/content/ContentStreamer.java
  remote-api/src/main/java/org/alfresco/rest/api/impl/CustomModelsImpl.java
  remote-api/src/main/resources/alfresco/web-scripts-application-context.xml
  remote-api/src/test/java/org/alfresco/repo/web/scripts/content/ContentGetTest.java
Labels: PR: partially-approved

#1319 ACS-3316 Fix custom models downloading and XSS Backport
  amps/share-services/src/test/java/org/alfresco/slingshot/web/scripts/SlingshotContentGetTest.java
  remote-api/src/main/java/org/alfresco/repo/web/scripts/MimeTypeUtil.java
  remote-api/src/main/java/org/alfresco/repo/web/scripts/content/ContentGet.java
  remote-api/src/main/java/org/alfresco/repo/web/scripts/content/ContentInfo.java
  remote-api/src/main/java/org/alfresco/repo/web/scripts/content/ContentStreamer.java
  remote-api/src/main/java/org/alfresco/rest/api/impl/CustomModelsImpl.java
  remote-api/src/main/resources/alfresco/web-scripts-application-context.xml
  remote-api/src/test/java/org/alfresco/repo/web/scripts/content/ContentGetTest.java
Labels: PR: partially-approved

#1328 ACS-3316 Fix custom models downloading and XSS Backport
  remote-api/src/main/java/org/alfresco/repo/web/scripts/MimeTypeUtil.java
  remote-api/src/main/java/org/alfresco/repo/web/scripts/content/ContentGet.java
  remote-api/src/main/java/org/alfresco/repo/web/scripts/content/ContentInfo.java
  remote-api/src/main/java/org/alfresco/repo/web/scripts/content/ContentStreamer.java
  remote-api/src/main/java/org/alfresco/rest/api/impl/CustomModelsImpl.java
  remote-api/src/main/resources/alfresco/web-scripts-application-context.xml
  remote-api/src/test/java/org/alfresco/repo/web/scripts/content/ContentGetTest.java
  repository/src/main/resources/alfresco/repository.properties
Labels: PR: partially-approved

#1334 ACS-3351 Bump Alfresco JLAN to 7.2
  pom.xml
Labels: PR: partially-approved

#1324 Support for linking to a single rule set
  remote-api/src/main/java/org/alfresco/rest/api/impl/rules/NodeValidator.java
  remote-api/src/main/java/org/alfresco/rest/api/impl/rules/RuleSetsImpl.java
  remote-api/src/main/resources/alfresco/public-rest-context.xml
  remote-api/src/test/java/org/alfresco/rest/api/impl/rules/NodeValidatorTest.java
  remote-api/src/test/java/org/alfresco/rest/api/impl/rules/RuleSetsImplTest.java
Labels: PR: partially-approved

#1327 MNT-23103 - Downloading a document replaces filename having space with + character
  remote-api/src/main/java/org/alfresco/repo/web/scripts/content/ContentStreamer.java
  remote-api/src/test/java/org/alfresco/rest/api/tests/NodeApiTest.java
  remote-api/src/test/resources/publicapi/upload/Test Download (1).txt
Labels: PR: partially-approved

#1332 ACS-3429, ACS-3336: Rule action mappings (create), validations (update) - part 2
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/rules/CreateRulesTests.java
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/rules/RulesTestsUtils.java
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/rules/UpdateRulesTests.java
  remote-api/src/main/java/org/alfresco/rest/api/impl/rules/ActionParameterConverter.java
  remote-api/src/main/java/org/alfresco/rest/api/impl/rules/RulesImpl.java
  remote-api/src/test/java/org/alfresco/rest/api/impl/rules/ActionParameterConverterTest.java
  remote-api/src/test/java/org/alfresco/rest/api/impl/rules/ActionPermissionValidatorTest.java
  remote-api/src/test/java/org/alfresco/rest/api/impl/rules/RulesImplTest.java
Labels: PR: unreviewed

#1333 Fix/mnt 23087 export of records failing
  repository/src/main/java/org/alfresco/repo/exporter/ExporterComponent.java
  repository/src/main/java/org/alfresco/service/cmr/view/ExporterContext.java
  repository/src/main/java/org/alfresco/service/cmr/view/ExporterService.java
  repository/src/main/resources/alfresco/import-export-context.xml
  repository/src/test/java/org/alfresco/repo/exporter/ExporterComponentTest.java
Labels: PR: partially-approved

#1341 Fix/mnt 23087 export of records failing (#1333)
  repository/src/main/java/org/alfresco/repo/exporter/ExporterComponent.java
  repository/src/main/java/org/alfresco/service/cmr/view/ExporterContext.java
  repository/src/main/java/org/alfresco/service/cmr/view/ExporterService.java
  repository/src/main/resources/alfresco/import-export-context.xml
  repository/src/test/java/org/alfresco/repo/exporter/ExporterComponentTest.java
Labels: PR: unreviewed

#1335 ACS-3352 GET e2es for newly mapped other fields
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/rules/CreateRulesTests.java
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/rules/GetRulesTests.java
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/rules/RulesTestsUtils.java
Labels: PR: reviewed-approved

#1348 ACS-3463: Updating AIS and ATC versions
  pom.xml
Labels: PR: reviewed-approved

#1342 ACS-3431 rule set links TAS REST tests
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/rules/RuleSetLinksTests.java
  pom.xml
Labels: PR: partially-approved
