Repository Alfresco/alfresco-community-repo, pull requests merged in 2022-12, with the labels that each got.

#1591 ACS-4028 Get category by id
  packaging/tests/tas-restapi/src/main/java/org/alfresco/rest/model/RestCategoryBodyModel.java
  packaging/tests/tas-restapi/src/main/java/org/alfresco/rest/model/RestCategoryLinkBodyModel.java
  packaging/tests/tas-restapi/src/main/java/org/alfresco/rest/model/RestCategoryModel.java
  packaging/tests/tas-restapi/src/main/java/org/alfresco/rest/requests/Categories.java
  packaging/tests/tas-restapi/src/main/java/org/alfresco/rest/requests/coreAPI/RestCoreAPI.java
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/RestTest.java
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/categories/GetCategoriesTests.java
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/rules/CreateRulesTests.java
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/rules/DeleteRulesTests.java
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/rules/ExecuteRulesTests.java
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/rules/GetInheritedRulesTests.java
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/rules/GetRuleSetsTests.java
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/rules/GetRulesTests.java
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/rules/ReorderRules.java
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/rules/RuleSetLinksTests.java
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/rules/RulesRestTest.java
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/rules/SetInheritanceTests.java
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/rules/UpdateRulesTests.java
  packaging/tests/tas-restapi/src/test/resources/test-suites/part3-suite.xml
  remote-api/src/main/java/org/alfresco/rest/api/Categories.java
  remote-api/src/main/java/org/alfresco/rest/api/categories/CategoriesEntityResource.java
  remote-api/src/main/java/org/alfresco/rest/api/categories/package-info.java
  remote-api/src/main/java/org/alfresco/rest/api/impl/CategoriesImpl.java
  remote-api/src/main/java/org/alfresco/rest/api/model/Category.java
  remote-api/src/main/resources/alfresco/public-rest-context.xml
  remote-api/src/test/java/org/alfresco/rest/api/categories/CategoriesEntityResourceTest.java
  remote-api/src/test/java/org/alfresco/rest/api/impl/CategoriesImplTest.java
  repository/src/main/java/org/alfresco/repo/search/impl/AbstractCategoryServiceImpl.java
  repository/src/main/java/org/alfresco/service/cmr/search/CategoryService.java
  repository/src/main/java/org/alfresco/service/cmr/search/CategoryServiceException.java
  repository/src/test/java/org/alfresco/repo/search/SearchTestSuite.java
  repository/src/test/java/org/alfresco/repo/search/impl/solr/SolrCategoryServiceImplTest.java
Labels: PR: partially-approved

#1480 [MNT-22437] Remove ACS version from landing page
  packaging/war/src/main/webapp/index.jsp
  pom.xml
Labels: PR: unreviewed

#1605 [MNT-22437] Remove ACS version from landing page (#1480)
  packaging/war/src/main/webapp/index.jsp
  pom.xml
Labels: PR: unreviewed

#1607 ACS-4142 Update AOS version
  pom.xml
Labels: PR: partially-approved

#1610 ACS-4032 create category (multiple categories pagination fix)
  packaging/tests/tas-restapi/src/main/java/org/alfresco/rest/requests/Categories.java
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/categories/CreateCategoriesTests.java
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/rules/CreateRulesTests.java
  remote-api/src/main/java/org/alfresco/rest/api/impl/CategoriesImpl.java
  remote-api/src/main/java/org/alfresco/rest/framework/webscripts/ResourceWebScriptPost.java
Labels: PR: partially-approved

#1618 ACS-4030: Delete category endpoint
  packaging/tests/tas-restapi/src/main/java/org/alfresco/rest/requests/Categories.java
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/categories/DeleteCategoriesTests.java
  remote-api/src/main/java/org/alfresco/rest/api/Categories.java
  remote-api/src/main/java/org/alfresco/rest/api/categories/CategoriesEntityResource.java
  remote-api/src/main/java/org/alfresco/rest/api/impl/CategoriesImpl.java
  remote-api/src/test/java/org/alfresco/rest/api/impl/CategoriesImplTest.java
Labels: PR: reviewed-approved

#1628 bumped IE version to 2.0.6 (ACS-4054)
  amps/ags/rm-community/rm-community-repo/.env
  packaging/tests/environment/.env
Labels: PR: reviewed-approved

#1629 ACS-3841 Add missing logs for WebDAV TAS tests
  packaging/tests/scripts/output_tests_run.sh
  packaging/tests/tas-webdav/src/test/java/org/alfresco/webdav/WebDavTest.java
Labels: PR: partially-approved

#1621 ACS-4029: Update a category name - PUT /categories/{categoryId}
  packaging/tests/tas-restapi/src/main/java/org/alfresco/rest/model/RestCategoryModel.java
  packaging/tests/tas-restapi/src/main/java/org/alfresco/rest/requests/Categories.java
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/categories/CategoriesRestTest.java
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/categories/CreateCategoriesTests.java
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/categories/DeleteCategoriesTests.java
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/categories/GetCategoriesTests.java
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/categories/UpdateCategoriesTests.java
  remote-api/src/main/java/org/alfresco/rest/api/Categories.java
  remote-api/src/main/java/org/alfresco/rest/api/categories/CategoriesEntityResource.java
  remote-api/src/main/java/org/alfresco/rest/api/categories/SubcategoriesRelation.java
  remote-api/src/main/java/org/alfresco/rest/api/impl/CategoriesImpl.java
  remote-api/src/main/java/org/alfresco/rest/api/model/Category.java
  remote-api/src/test/java/org/alfresco/rest/api/categories/CategoriesEntityResourceTest.java
  remote-api/src/test/java/org/alfresco/rest/api/impl/CategoriesImplTest.java
Labels: PR: partially-approved

#1637 Fix/mnt 23290 slow group membership
  amps/ags/rm-community/rm-community-repo/config/alfresco/module/org_alfresco_module_rm/security/rm-method-security.properties
  data-model/src/main/java/org/alfresco/service/cmr/repository/NodeService.java
  repository/src/main/java/org/alfresco/repo/domain/node/NodeDAO.java
  repository/src/main/java/org/alfresco/repo/domain/node/ibatis/NodeDAOImpl.java
  repository/src/main/java/org/alfresco/repo/node/db/DbNodeServiceImpl.java
  repository/src/main/java/org/alfresco/repo/security/authority/AuthorityDAOImpl.java
  repository/src/main/java/org/alfresco/repo/version/NodeServiceImpl.java
  repository/src/main/java/org/alfresco/repo/virtual/bundle/VirtualNodeServiceExtension.java
  repository/src/main/resources/alfresco/ibatis/org.alfresco.repo.domain.dialect.Dialect/node-common-SqlMap.xml
  repository/src/main/resources/alfresco/public-services-security-context.xml
Labels: PR: partially-approved

#1644 Fix/mnt 23290 slow group membership (#1637)
  amps/ags/rm-community/rm-community-repo/config/alfresco/module/org_alfresco_module_rm/security/rm-method-security.properties
  data-model/src/main/java/org/alfresco/service/cmr/repository/NodeService.java
  repository/src/main/java/org/alfresco/repo/domain/node/NodeDAO.java
  repository/src/main/java/org/alfresco/repo/domain/node/ibatis/NodeDAOImpl.java
  repository/src/main/java/org/alfresco/repo/node/db/DbNodeServiceImpl.java
  repository/src/main/java/org/alfresco/repo/security/authority/AuthorityDAOImpl.java
  repository/src/main/java/org/alfresco/repo/version/NodeServiceImpl.java
  repository/src/main/java/org/alfresco/repo/virtual/bundle/VirtualNodeServiceExtension.java
  repository/src/main/resources/alfresco/ibatis/org.alfresco.repo.domain.dialect.Dialect/node-common-SqlMap.xml
  repository/src/main/resources/alfresco/public-services-security-context.xml
Labels: PR: unreviewed

#1643 Fix/mnt 23290 slow group membership (#1637)
  amps/ags/rm-community/rm-community-repo/config/alfresco/module/org_alfresco_module_rm/security/rm-method-security.properties
  data-model/src/main/java/org/alfresco/service/cmr/repository/NodeService.java
  repository/src/main/java/org/alfresco/repo/domain/node/NodeDAO.java
  repository/src/main/java/org/alfresco/repo/domain/node/ibatis/NodeDAOImpl.java
  repository/src/main/java/org/alfresco/repo/node/db/DbNodeServiceImpl.java
  repository/src/main/java/org/alfresco/repo/security/authority/AuthorityDAOImpl.java
  repository/src/main/java/org/alfresco/repo/version/NodeServiceImpl.java
  repository/src/main/java/org/alfresco/repo/virtual/bundle/VirtualNodeServiceExtension.java
  repository/src/main/resources/alfresco/ibatis/org.alfresco.repo.domain.dialect.Dialect/node-common-SqlMap.xml
  repository/src/main/resources/alfresco/public-services-security-context.xml
Labels: PR: unreviewed
