Repository Alfresco/alfresco-community-repo, pull requests merged in 2022-07, with the labels that each got.

#1191 [MNT-22085] Change default email domain
  repository/src/main/resources/alfresco/subsystems/email/InboundSMTP/inboundSMTP.properties
Labels: PR: reviewed-approved

#1189 Feature/acs 3169 implement security mechanism for mail action
  amps/ags/rm-community/rm-community-repo/test/resources/test-context.xml
  remote-api/src/main/java/org/alfresco/repo/web/scripts/action/AbstractExecuteActionWebscript.java
  remote-api/src/main/java/org/alfresco/repo/web/scripts/rule/AbstractRuleWebScript.java
  remote-api/src/main/java/org/alfresco/repo/web/scripts/rule/ActionQueuePost.java
  remote-api/src/main/java/org/alfresco/rest/api/impl/ActionsImpl.java
  remote-api/src/main/resources/alfresco/web-scripts-application-context.xml
  repository/src/main/java/org/alfresco/repo/action/ActionServiceImpl.java
  repository/src/main/java/org/alfresco/repo/action/RuntimeActionService.java
  repository/src/main/java/org/alfresco/repo/action/access/ActionAccessException.java
  repository/src/main/java/org/alfresco/repo/action/access/ActionAccessRestriction.java
  repository/src/main/java/org/alfresco/repo/action/access/ActionAccessRestrictionAbstractBase.java
  repository/src/main/java/org/alfresco/repo/action/access/AdminActionAccessRestriction.java
  repository/src/main/java/org/alfresco/repo/action/executer/ActionExecuter.java
  repository/src/main/java/org/alfresco/repo/action/executer/ActionExecuterAbstractBase.java
  repository/src/main/java/org/alfresco/repo/action/executer/CompositeActionExecuter.java
  repository/src/main/java/org/alfresco/repo/forms/processor/action/ActionFormProcessor.java
  repository/src/main/java/org/alfresco/repo/rule/RuleServiceImpl.java
  repository/src/main/java/org/alfresco/service/cmr/action/ActionService.java
  repository/src/main/resources/alfresco/action-services-context.xml
  repository/src/main/resources/alfresco/subsystems/email/OutboundSMTP/outboundSMTP-context.xml
  repository/src/test/resources/alfresco/extension/subsystems/email/OutboundSMTP/outbound/outboundSMTP-test-context.xml
Labels: PR: unreviewed

#1199 PRODSEC-6115: Updating Surf Webscript Version to 8.31
  pom.xml
Labels: PR: reviewed-approved

#1193 ACS-3198: Folder rules v1 REST API - List rules for node
  core/src/main/java/org/alfresco/query/ListBackedPagingResults.java
  pom.xml
  remote-api/pom.xml
  remote-api/src/main/java/org/alfresco/rest/api/Rules.java
  remote-api/src/main/java/org/alfresco/rest/api/impl/RulesImpl.java
  remote-api/src/main/java/org/alfresco/rest/api/model/Rule.java
  remote-api/src/main/java/org/alfresco/rest/api/nodes/NodeRuleSetsRelation.java
  remote-api/src/main/java/org/alfresco/rest/api/nodes/NodeRulesRelation.java
  remote-api/src/main/java/org/alfresco/rest/framework/resource/parameters/ArrayListPage.java
  remote-api/src/main/java/org/alfresco/rest/framework/resource/parameters/CollectionWithPagingInfo.java
  remote-api/src/main/java/org/alfresco/rest/framework/resource/parameters/ListPage.java
  remote-api/src/main/resources/alfresco/public-rest-context.xml
  remote-api/src/test/java/org/alfresco/AppContextExtraTestSuite.java
  remote-api/src/test/java/org/alfresco/rest/api/impl/RulesImplTest.java
  remote-api/src/test/java/org/alfresco/rest/api/nodes/NodeRulesRelationTest.java
  remote-api/src/test/java/org/alfresco/rest/framework/resource/parameters/ArrayListPageTest.java
  repository/src/main/java/org/alfresco/repo/rule/RuleServiceImpl.java
  repository/src/main/java/org/alfresco/service/cmr/rule/Rule.java
  repository/src/main/java/org/alfresco/service/cmr/rule/RuleService.java
  repository/src/test/java/org/alfresco/repo/rule/RuleLinkTest.java
Labels: PR: unreviewed

#1206 PRODSEC-6261 Fix workflow api bola - Backporting
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/workflow/processes/GetProcessSanityTests.java
  remote-api/src/main/java/org/alfresco/rest/workflow/api/impl/ProcessesImpl.java
Labels: PR: partially-approved

#1207 PRODSEC-6115: Bump Surf webscript Version to 8.31 and removing set exception
  amps/share-services/src/main/java/org/alfresco/slingshot/web/scripts/NodeBrowserScript.java
  pom.xml
Labels: PR: reviewed-approved

#1211 ACS-3150 Upgrade jackson and gson libraries - Backporting
  pom.xml
Labels: PR: partially-approved

#1209 Update MySQL 5.7.23 tests to 5.7.28 version
  .travis.yml
Labels: PR: partially-approved

#1215 [ACS-3271] Update MySQL 5.7.23 tests to 5.7.28 version (#1209)
  .travis.yml
Labels: PR: unreviewed

#1217 [ACS-3271] Update MySQL 5.7.23 tests to 5.7.28 version (#1209)
  .travis.yml
Labels: PR: unreviewed

#1218 [ACS-3271] Update MySQL 5.7.23 tests to 5.7.28 version (#1209)
  .travis.yml
Labels: PR: unreviewed

#1220 [ACS-3271] Update MySQL 5.7.23 tests to 5.7.28 version (#1209)
  .travis.yml
Labels: PR: unreviewed

#1219 [ACS-3271] Update MySQL 5.7.23 tests to 5.7.28 version (#1209)
  .travis.yml
Labels: PR: unreviewed

#1213 ACS-3170 Implement Tests For Mail Actions
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/actions/access/AccessRestrictionUtil.java
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/actions/access/FormProcAdminAccessRestrictionTest.java
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/actions/access/RuleAdminAccessRestrictionTest.java
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/actions/access/V0AdminAccessRestrictionTest.java
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/actions/access/V1AdminAccessRestrictionTest.java
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/actions/access/pojo/Action.java
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/actions/access/pojo/ActionCondition.java
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/actions/access/pojo/Rule.java
  repository/src/main/java/org/alfresco/repo/action/access/ActionAccessRestrictionAbstractBase.java
  repository/src/test/java/org/alfresco/AppContext01TestSuite.java
  repository/src/test/java/org/alfresco/repo/action/access/ActionAccessRestrictionAbstractBaseTest.java
  repository/src/test/java/org/alfresco/repo/action/access/ActionAccessRestrictionTest.java
  repository/src/test/java/org/alfresco/repo/action/access/AdminActionAccessRestrictionTest.java
Labels: PR: unreviewed

#1226 Updating googledrive version
  pom.xml
Labels: PR: reviewed-approved

#1227 ACS-3225 Include TAS changes for rules.
  amps/ags/rm-automation/rm-automation-community-rest-api/src/test/java/org/alfresco/rest/rm/community/base/BaseRMRestTest.java
  pom.xml
Labels: PR: reviewed-approved

#1228 ACS-3225 Get rules REST tests.
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/rules/GetRulesTests.java
  packaging/tests/tas-restapi/src/test/resources/test-suites/part1-suite.xml
  pom.xml
Labels: PR: unreviewed

#1216 ACS-3225 REST API to create one or more rules.
  amps/ags/rm-community/rm-community-repo/source/java/org/alfresco/repo/rule/ExtendedRuleServiceImpl.java
  remote-api/src/main/java/org/alfresco/rest/api/Rules.java
  remote-api/src/main/java/org/alfresco/rest/api/impl/RulesImpl.java
  remote-api/src/main/java/org/alfresco/rest/api/model/rules/Rule.java
  remote-api/src/main/java/org/alfresco/rest/api/model/rules/RuleSet.java
  remote-api/src/main/java/org/alfresco/rest/api/nodes/NodeRulesRelation.java
  remote-api/src/test/java/org/alfresco/rest/api/impl/RulesImplTest.java
  repository/src/main/java/org/alfresco/repo/rule/RuleServiceImpl.java
  repository/src/main/java/org/alfresco/service/cmr/rule/RuleService.java
Labels: PR: partially-approved

#1232 ACS-3220 Folder rules delete rule v1 API
  remote-api/src/main/java/org/alfresco/rest/api/Rules.java
  remote-api/src/main/java/org/alfresco/rest/api/impl/RulesImpl.java
  remote-api/src/main/java/org/alfresco/rest/api/nodes/NodeRulesRelation.java
  remote-api/src/test/java/org/alfresco/rest/api/impl/RulesImplTest.java
  remote-api/src/test/java/org/alfresco/rest/api/nodes/NodeRulesRelationTest.java
  repository/src/main/java/org/alfresco/repo/rule/RuleServiceImpl.java
Labels: PR: reviewed-approved

#1235 ACS-3227 POST Rule Fixes.
  remote-api/src/main/java/org/alfresco/rest/api/impl/RulesImpl.java
  remote-api/src/main/java/org/alfresco/rest/api/model/rules/Rule.java
  remote-api/src/test/java/org/alfresco/rest/api/impl/RulesImplTest.java
Labels: PR: partially-approved

#1236 ACS-3227 Simple rules tests.
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/rules/CreateRulesTests.java
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/rules/GetRulesTests.java
  pom.xml
  remote-api/src/main/java/org/alfresco/rest/api/model/rules/Rule.java
Labels: PR: unreviewed

#1239 ACS-3227 Add some more comprehensive REST tests for creating rules.
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/rules/CreateRulesTests.java
Labels: PR: unreviewed

#1240 ACS-3227 Ensure the rule name is set. [tas]
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/rules/CreateRulesTests.java
  repository/pom.xml
  repository/src/main/java/org/alfresco/repo/rule/RuleServiceImpl.java
  repository/src/test/java/org/alfresco/AllUnitTestsSuite.java
  repository/src/test/java/org/alfresco/repo/copy/CopyServiceImplTest.java
  repository/src/test/java/org/alfresco/repo/rule/RuleServiceCoverageTest.java
  repository/src/test/java/org/alfresco/repo/rule/RuleServiceImplUnitTest.java
  repository/src/test/java/org/alfresco/repo/thumbnail/ThumbnailServiceImplTest.java
Labels: PR: unreviewed

#1242 ACS-3227 Permissions tests for GET rules. [tas]
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/rules/GetRulesTests.java
Labels: PR: partially-approved

#1243 ACS-3342 Test with PostgreSQL 14.4 and 13.7
  .travis.yml
  amps/ags/rm-community/rm-community-repo/.env
  packaging/tests/environment/.env
Labels: PR: partially-approved

#1251 ACS-3346 Require CHANGE permission for POST/DELETE rules.
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/rules/CreateRulesTests.java
  remote-api/src/main/java/org/alfresco/rest/api/impl/RulesImpl.java
  remote-api/src/test/java/org/alfresco/rest/api/impl/RulesImplTest.java
Labels: PR: partially-approved

#1241 ACS-3306 Upgrade activemq to 5.17.1-jre11-rockylinux8
  .travis.yml
  amps/ags/rm-community/rm-community-repo/.env
  amps/ags/rm-community/rm-community-repo/pom.xml
  packaging/tests/environment/.env
  pom.xml
Labels: PR: unreviewed

#1244 Rules v1 REST API - Get rule definition - mapping of "other fields"
  remote-api/src/main/java/org/alfresco/rest/api/impl/RulesImpl.java
  remote-api/src/main/java/org/alfresco/rest/api/model/rules/Rule.java
  remote-api/src/main/java/org/alfresco/rest/api/model/rules/RuleSet.java
  remote-api/src/main/java/org/alfresco/rest/api/model/rules/RuleTrigger.java
  remote-api/src/test/java/org/alfresco/AppContextExtraTestSuite.java
  remote-api/src/test/java/org/alfresco/rest/api/RulesUnitTests.java
  remote-api/src/test/java/org/alfresco/rest/api/impl/RulesImplTest.java
  remote-api/src/test/java/org/alfresco/rest/api/model/rules/RuleTest.java
  repository/src/main/java/org/alfresco/repo/rule/RuleServiceImpl.java
  repository/src/main/java/org/alfresco/service/cmr/rule/RuleService.java
  repository/src/test/java/org/alfresco/repo/rule/RuleLinkTest.java
Labels: PR: unreviewed

#1257 ACS-3214 Unit tests for update rule API.
  remote-api/src/main/java/org/alfresco/rest/api/impl/RulesImpl.java
  remote-api/src/test/java/org/alfresco/rest/api/impl/RulesImplTest.java
Labels: PR: partially-approved

#1255 Feature/acs 3122 update tomcat to rocky linux8
  .github/dependabot.yml
  packaging/docker-alfresco/Dockerfile
Labels: PR: partially-approved

#1258 Feature/acs 3122 update tomcat to rocky linux8
  .github/dependabot.yml
Labels: PR: reviewed-approved

#1259 ACS-2827: Fix Resources and Property Exceptions
  remote-api/src/main/java/org/alfresco/rest/framework/core/ResourceLookupDictionary.java
Labels: PR: reviewed-approved

#1260 ACS-2064 DAU: Fix response content type always PDF (#754)
  data-model/src/main/java/org/alfresco/repo/content/ContentStore.java
  repository/src/main/java/org/alfresco/repo/content/ContentServiceImpl.java
  repository/src/main/java/org/alfresco/repo/content/caching/CachingContentStore.java
  repository/src/main/java/org/alfresco/repo/content/replication/AggregatingContentStore.java
  repository/src/test/java/org/alfresco/repo/content/ContentServiceImplUnitTest.java
  repository/src/test/java/org/alfresco/repo/content/caching/CachingContentStoreTest.java
  repository/src/test/java/org/alfresco/repo/content/replication/AggregatingContentStoreTest.java
Labels: PR: partially-approved

#1256 ACS-3345 e2e REST API TAS tests delete rule
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/rules/DeleteRulesTests.java
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/rules/GetRulesTests.java
  remote-api/src/main/java/org/alfresco/rest/api/impl/RulesImpl.java
  remote-api/src/test/java/org/alfresco/rest/api/impl/RulesImplTest.java
Labels: PR: unreviewed

#1231 MNT-22979: removed unused commons-dbcp artefact from activiti
  pom.xml
Labels: PR: reviewed-approved
