Repository Alfresco/alfresco-community-repo, pull requests merged in 2022-06, with the labels that each got.

#1127 Feature/apps 2755 UI conversion
  amps/ags/rm-automation/rm-automation-community-rest-api/src/main/java/org/alfresco/rest/v0/CustomDefinitionsAPI.java
  amps/ags/rm-automation/rm-automation-community-rest-api/src/test/java/org/alfresco/rest/rm/community/records/AddRelationshipTests.java
  amps/ags/rm-automation/rm-automation-community-rest-api/src/test/java/org/alfresco/rest/rm/community/records/CreateElectronicRecordsTests.java
  amps/ags/rm-automation/rm-automation-community-rest-api/src/test/java/org/alfresco/rest/rm/community/records/DeclareInPlaceRecordTests.java
  amps/ags/rm-automation/rm-automation-community-rest-api/src/test/java/org/alfresco/rest/rm/community/records/FileUnfiledRecordsTests.java
  amps/ags/rm-automation/rm-automation-community-rest-api/src/test/java/org/alfresco/rest/rm/community/records/InplaceRecordSearchTests.java
  amps/ags/rm-automation/rm-automation-community-rest-api/src/test/java/org/alfresco/rest/rm/community/records/SearchRecordsTests.java
Labels: PR: unreviewed

#1103 ATS-988 Intermittent test failure: End-to-End Tests - AI-Renditions
  repository/src/main/java/org/alfresco/repo/rendition2/RenditionDefinitionRegistry2Impl.java
Labels: PR: reviewed-approved

#1148 Revert "ATS-988 Intermittent test failure: End-to-End Tests - AI-Renditions"
  repository/src/main/java/org/alfresco/repo/rendition2/RenditionDefinitionRegistry2Impl.java
Labels: PR: reviewed-approved

#1151 ACS-3150 Upgrade jackson and gson libraries
  pom.xml
Labels: PR: unreviewed

#1158 Revert "Revert "ATS-988 Intermittent test failure: End-to-End Tests - AI-Renditions""
  repository/src/main/java/org/alfresco/repo/rendition2/RenditionDefinitionRegistry2Impl.java
Labels: PR: reviewed-approved

#1159 ACS-2322 Don't compare audit properties for CMIS TCK RootFolderTest
  remote-api/src/test/java/org/alfresco/rest/api/tests/AbstractEnterpriseOpenCMIS11TCKTest.java
  remote-api/src/test/java/org/alfresco/rest/api/tests/AlfrescoCMISBasicsTestGroup.java
  remote-api/src/test/java/org/alfresco/rest/api/tests/TestEnterpriseAtomPubTCK.java
  remote-api/src/test/java/org/alfresco/rest/api/tests/TestPublicApiAtomPub10TCK.java
Labels: PR: unreviewed

#1165 Downgrade mysql-connector-java from 8.0.29 to 8.0.27
  pom.xml
Labels: PR: partially-approved

#1171 PRODSEC-6115: Removing Exception Stack
  amps/share-services/src/main/java/org/alfresco/slingshot/web/scripts/NodeBrowserScript.java
Labels: PR: reviewed-approved

#1179 ACS-3181 Skip MySQL 5 tests on master
  .travis.yml
Labels: PR: partially-approved
