Repository Alfresco/alfresco-community-repo, pull requests merged in 2022-02, with the labels that each got.

#916 ACS-2245: Mitigate intermittent failure of FixedAclUpdaterTest
  repository/src/test/java/org/alfresco/AllUnitTestsSuite.java
  repository/src/test/java/org/alfresco/repo/domain/permissions/FixedAclUpdaterTest.java
  repository/src/test/java/org/alfresco/repo/security/SecurityTestSuite.java
  repository/src/test/java/org/alfresco/util/test/junitrules/RetryAtMostRule.java
  repository/src/test/java/org/alfresco/util/test/junitrules/RetryAtMostRuleTest.java
Labels: PR: partially-approved

#929 Should be using TRAVIS_ACCESS_TOKEN rather than TRAVIS_ACCESS_TOKEN_T…
  scripts/travis/trigger_travis.sh
Labels: PR: unreviewed

#930 build fix branches
  .travis.yml
Labels: PR: unreviewed

#925 MNT-22807: improve sitesTest test
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/sites/GetSitesTests.java
Labels: PR: unreviewed

#932 REST API Explorer -Ax release
  pom.xml
Labels: PR: reviewed-approved

#923 MNT-22388 Upgrade to org.apache.pdfbox:pdfbox:2.0.23
  pom.xml
Labels: PR: unreviewed

#944 MNT-22710 - ContentURLs with CRC collision
  repository/src/main/java/org/alfresco/repo/domain/contentdata/AbstractContentDataDAOImpl.java
  repository/src/test/java/org/alfresco/repo/node/NodeServiceTest.java
Labels: PR: reviewed-approved

#949 PRODSEC-6083 migrate to reload4j
  amps/ags/rm-automation/rm-automation-community-rest-api/pom.xml
  core/pom.xml
  pom.xml
  repository/pom.xml
Labels: PR: partially-approved

#937 ACS-2498 Add coreVersion to T-Engine config
  pom.xml
  repository/src/main/java/org/alfresco/repo/content/transform/AbstractLocalTransform.java
  repository/src/main/java/org/alfresco/repo/content/transform/DummyTransformServiceRegistry.java
  repository/src/main/java/org/alfresco/repo/content/transform/LocalTransform.java
  repository/src/main/java/org/alfresco/repo/content/transform/LocalTransformServiceRegistry.java
  repository/src/main/java/org/alfresco/repo/rendition2/SwitchingTransformServiceRegistry.java
  repository/src/main/java/org/alfresco/transform/client/registry/CombinedConfig.java
  repository/src/test/java/org/alfresco/repo/rendition2/TestTransformServiceRegistry.java
Labels: PR: unreviewed, PR: partially-approved

#951 MNT-22807: improve sitesTest test (#925)
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/sites/GetSitesTests.java
Labels: PR: reviewed-approved

#936 ACS-2276: Add missing indexControl on hidden nodes to avoid ElasticSearch indexing
  repository/src/main/resources/alfresco/bootstrap/sitesSpace.xml
  repository/src/test/java/org/alfresco/repo/importer/ImporterComponentTest.java
  repository/src/test/resources/org/alfresco/repo/importer/import_not_indexed_subfolder.xml
Labels: PR: partially-approved

#931 ACS-1988 Implement DAU Version Renditions code
  remote-api/src/main/java/org/alfresco/rest/api/nodes/NodeVersionRenditionsRelation.java
  remote-api/src/main/resources/alfresco/public-rest-context.xml
  remote-api/src/test/java/org/alfresco/AppContext02TestSuite.java
  remote-api/src/test/java/org/alfresco/rest/api/tests/AbstractBaseApiTest.java
  remote-api/src/test/java/org/alfresco/rest/api/tests/NodeVersionRenditionsApiTest.java
Labels: PR: reviewed-approved

#959 Revert "ACS-2476 Bump Camel version to 3.8.0"
  pom.xml
Labels: PR: partially-approved

#964 ACS-1988 Enable system-wide DAUs
  remote-api/src/test/java/org/alfresco/rest/api/tests/AbstractBaseApiTest.java
Labels: PR: reviewed-approved

#945 Add further tests for ReST integration tests
  remote-api/src/test/java/org/alfresco/rest/api/tests/AbstractBaseApiTest.java
  remote-api/src/test/java/org/alfresco/rest/api/tests/NodeApiTest.java
Labels: PR: reviewed-approved

#912 OPSEXP-1194: remove usage of jar command
  amps/ags/rm-community/rm-community-repo/Dockerfile
Labels: PR: reviewed-approved, do not merge

#966 Fix Existing Issues in DAU ReST integration tests
  remote-api/src/test/java/org/alfresco/rest/api/tests/NodeApiTest.java
  remote-api/src/test/java/org/alfresco/rest/api/tests/NodeVersionsApiTest.java
  remote-api/src/test/java/org/alfresco/rest/api/tests/RenditionsTest.java
Labels: PR: reviewed-approved

#973 MNT-22710 - ContentURLs with CRC collision and same last 12 chars are…
  repository/src/main/java/org/alfresco/repo/domain/contentdata/AbstractContentDataDAOImpl.java
  repository/src/test/java/org/alfresco/repo/node/NodeServiceTest.java
Labels: PR: unreviewed

#981 ACS-2476: Update to Camel 3.15.0
  pom.xml
  repository/pom.xml
Labels: PR: partially-approved

#980 ACS-2348: Removing `@Experimental` annotation on Storage Properties
  data-model/src/main/java/org/alfresco/repo/content/ContentRestoreParams.java
  data-model/src/main/java/org/alfresco/repo/content/ContentStore.java
  data-model/src/main/java/org/alfresco/repo/content/ObjectStorageProps.java
  data-model/src/main/java/org/alfresco/service/cmr/repository/ArchivedIOException.java
  data-model/src/main/java/org/alfresco/service/cmr/repository/RestoreInProgressException.java
  remote-api/src/main/java/org/alfresco/rest/api/ContentStorageInformation.java
  remote-api/src/main/java/org/alfresco/rest/api/impl/ContentStorageInformationImpl.java
  remote-api/src/main/java/org/alfresco/rest/api/impl/DownloadsImpl.java
  remote-api/src/main/java/org/alfresco/rest/api/model/ArchiveContentRequest.java
  remote-api/src/main/java/org/alfresco/rest/api/model/RestoreArchivedContentRequest.java
  remote-api/src/main/java/org/alfresco/rest/api/nodes/NodeStorageInfoRelation.java
  remote-api/src/main/java/org/alfresco/rest/api/nodes/NodeVersionsStorageInfoRelation.java
  remote-api/src/main/java/org/alfresco/rest/framework/core/exceptions/ArchivedContentException.java
  remote-api/src/main/java/org/alfresco/rest/framework/core/exceptions/RestoreInProgressException.java
  repository/src/main/java/org/alfresco/repo/content/AbstractRoutingContentStore.java
  repository/src/main/java/org/alfresco/repo/content/ContentServiceImpl.java
  repository/src/main/java/org/alfresco/repo/content/caching/CachingContentStore.java
  repository/src/main/java/org/alfresco/repo/content/replication/AggregatingContentStore.java
  repository/src/main/java/org/alfresco/repo/tenant/AbstractTenantRoutingContentStore.java
  repository/src/main/java/org/alfresco/service/cmr/repository/ContentService.java
Labels: PR: partially-approved

#984 ACS-2072 Enable third party license enforcement.
  pom.xml
Labels: PR: partially-approved
