Repository Alfresco/alfresco-community-repo, pull requests merged in 2023-05, with the labels that each got.

#1898 [MNT-23550] Always disable behaviours to prevent unexpected modifier changes
  repository/src/main/java/org/alfresco/repo/rendition2/RenditionService2Impl.java
  repository/src/test/java/org/alfresco/repo/rendition2/RenditionService2IntegrationTest.java
Labels: PR: reviewed-approved

#1912 ACS-5157_Bump_api-explorer_to_7-4-0
  pom.xml
Labels: PR: reviewed-approved

#1913 [MNT-23550] Always disable behaviours to prevent unexpected modifier changes (#1898)
  repository/src/main/java/org/alfresco/repo/rendition2/RenditionService2Impl.java
  repository/src/test/java/org/alfresco/repo/rendition2/RenditionService2IntegrationTest.java
Labels: PR: unreviewed

#1916 ACS-5174 missing changes done after the release
  amps/ags/pom.xml
  amps/ags/rm-automation/pom.xml
  amps/ags/rm-automation/rm-automation-community-rest-api/pom.xml
  amps/ags/rm-community/pom.xml
  amps/ags/rm-community/rm-community-repo/pom.xml
  amps/ags/rm-community/rm-community-rest-api-explorer/pom.xml
  amps/pom.xml
  amps/share-services/pom.xml
  core/pom.xml
  data-model/pom.xml
  mmt/pom.xml
  packaging/distribution/pom.xml
  packaging/docker-alfresco/pom.xml
  packaging/pom.xml
  packaging/tests/pom.xml
  packaging/tests/tas-cmis/pom.xml
  packaging/tests/tas-email/pom.xml
  packaging/tests/tas-integration/pom.xml
  packaging/tests/tas-restapi/pom.xml
  packaging/tests/tas-webdav/pom.xml
  packaging/war/pom.xml
  pom.xml
  remote-api/pom.xml
  repository/pom.xml
Labels: PR: partially-approved

#1904 ACS-5087 Add more attempts to create a folder in RenditionIntegrationTests
  packaging/tests/tas-restapi/pom.xml
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/renditions/RenditionIntegrationTests.java
Labels: PR: partially-approved
