Repository Alfresco/alfresco-community-repo, pull requests merged in 2023-03, with the labels that each got.

#1787 ACS-4776 Finalize deprecation of BitlyUrlShortenerImpl
  repository/src/main/java/org/alfresco/repo/urlshortening/BitlyUrlShortenerImpl.java
  repository/src/main/resources/alfresco/repository.properties
  repository/src/test/java/org/alfresco/AllUnitTestsSuite.java
  repository/src/test/java/org/alfresco/repo/urlshortening/BitlyUrlShortenerTest.java
Labels: PR: partially-approved

#1785 ACS-3975 Fix Intermittent Test Failure
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/favorites/AddFavoritesTests.java
Labels: PR: partially-approved

#1656 ACS-4137 Produce Multi-Arch Docker images
  amps/ags/rm-community/rm-community-repo/Dockerfile
  amps/ags/rm-community/rm-community-repo/pom.xml
  packaging/docker-alfresco/pom.xml
  pom.xml
  scripts/prepare_buildx.sh
Labels: PR: partially-approved

#1796 Revert "ACS-4137 Produce Multi-Arch Docker images (#1656)"
  amps/ags/rm-community/rm-community-repo/Dockerfile
  amps/ags/rm-community/rm-community-repo/pom.xml
  packaging/docker-alfresco/pom.xml
  pom.xml
  scripts/prepare_buildx.sh
Labels: PR: partially-approved

#1799 ACS-4137 Change the 'build-multiarch-docker-image' profile phase to package
  amps/ags/rm-community/rm-community-repo/pom.xml
  packaging/docker-alfresco/pom.xml
Labels: PR: partially-approved

#1766 ACS-4023: Update GET /tags to support getting tags by name
  core/src/main/java/org/alfresco/query/ListBackedPagingResults.java
  packaging/tests/tas-restapi/src/main/java/org/alfresco/rest/core/assertion/ModelsCollectionAssertion.java
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/tags/GetTagsTests.java
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/tags/TagsDataPrep.java
  remote-api/src/main/java/org/alfresco/rest/api/impl/TagsImpl.java
  remote-api/src/main/java/org/alfresco/rest/api/model/Tag.java
  remote-api/src/main/java/org/alfresco/rest/api/tags/TagsEntityResource.java
  remote-api/src/main/java/org/alfresco/rest/framework/resource/parameters/where/BasicQueryWalker.java
  remote-api/src/main/java/org/alfresco/rest/framework/resource/parameters/where/QueryHelper.java
  remote-api/src/main/java/org/alfresco/rest/framework/resource/parameters/where/WhereProperty.java
  remote-api/src/main/java/org/alfresco/rest/workflow/api/impl/MapBasedQueryWalker.java
  remote-api/src/test/java/org/alfresco/rest/api/impl/TagsImplTest.java
  remote-api/src/test/java/org/alfresco/rest/framework/resource/parameters/where/QueryResolverTest.java
  repository/src/main/java/org/alfresco/repo/search/impl/AbstractCategoryServiceImpl.java
  repository/src/main/java/org/alfresco/repo/tagging/TaggingServiceImpl.java
  repository/src/main/java/org/alfresco/service/cmr/search/CategoryService.java
  repository/src/main/java/org/alfresco/service/cmr/tagging/TaggingService.java
Labels: PR: unreviewed

#1798 ACS-4751 Keycloak Migration - OAuth2 Client Role
  pom.xml
  repository/pom.xml
  repository/src/main/java/org/alfresco/repo/security/authentication/identityservice/AuthenticatorAuthzClientFactoryBean.java
  repository/src/main/java/org/alfresco/repo/security/authentication/identityservice/IdentityServiceAuthenticationComponent.java
  repository/src/main/java/org/alfresco/repo/security/authentication/identityservice/IdentityServiceConfig.java
  repository/src/main/java/org/alfresco/repo/security/authentication/identityservice/OAuth2ClientFactoryBean.java
  repository/src/main/resources/alfresco/subsystems/Authentication/identity-service/identity-service-authentication-context.xml
  repository/src/test/java/org/alfresco/AllUnitTestsSuite.java
  repository/src/test/java/org/alfresco/repo/security/authentication/identityservice/IdentityServiceAuthenticationComponentTest.java
  repository/src/test/java/org/alfresco/repo/security/authentication/identityservice/SpringOAuth2ClientUnitTest.java
Labels: PR: unreviewed

#1789 ACS-4759 Replace default password hashing algorithm.
  repository/src/main/resources/alfresco/repository.properties
  repository/src/test/java/org/alfresco/repo/security/authentication/AuthenticationTest.java
  repository/src/test/resources/alfresco-global.properties
Labels: PR: unreviewed

#1803 ACS-4844 Dependency alignment after Keycloak migration
  packaging/tests/tas-integration/pom.xml
  pom.xml
  repository/pom.xml
Labels: PR: reviewed-approved

#1805 ACS-4844 Use matching json-smart version
  pom.xml
Labels: PR: unreviewed

#1814 ACS-4842 Upgrade Camel and Netty stack
  pom.xml
Labels: PR: partially-approved

#1815 [ACS-3916][ACS-3917] Added TagId Validation for Get and Delete methods
  remote-api/src/main/java/org/alfresco/rest/api/impl/TagsImpl.java
  remote-api/src/main/resources/alfresco/public-rest-context.xml
  remote-api/src/test/java/org/alfresco/rest/api/impl/TagsImplTest.java
Labels: PR: unreviewed

#1810 ACS-4857: Lookup for root tag in DB and NOT using search engine
  amps/share-services/pom.xml
  repository/src/main/java/org/alfresco/repo/search/impl/AbstractCategoryServiceImpl.java
Labels: PR: partially-approved

#1791 ACS-4755: Bump snakeyaml to 2.0
  pom.xml
Labels: PR: partially-approved

#1818 ACS- 4752 keycloak migration - resource server role
  remote-api/src/test/java/org/alfresco/rest/api/tests/AuthenticationsTest.java
  repository/pom.xml
  repository/src/main/java/org/alfresco/repo/security/authentication/identityservice/AlfrescoBearerTokenRequestAuthenticator.java
  repository/src/main/java/org/alfresco/repo/security/authentication/identityservice/IdentityServiceAuthenticationComponent.java
  repository/src/main/java/org/alfresco/repo/security/authentication/identityservice/IdentityServiceDeploymentFactoryBean.java
  repository/src/main/java/org/alfresco/repo/security/authentication/identityservice/IdentityServiceFacade.java
  repository/src/main/java/org/alfresco/repo/security/authentication/identityservice/IdentityServiceFacadeFactoryBean.java
  repository/src/main/java/org/alfresco/repo/security/authentication/identityservice/IdentityServiceHttpFacade.java
  repository/src/main/java/org/alfresco/repo/security/authentication/identityservice/IdentityServiceRemoteUserMapper.java
  repository/src/main/java/org/alfresco/repo/security/authentication/identityservice/OAuth2ClientFactoryBean.java
  repository/src/main/resources/alfresco/subsystems/Authentication/identity-service/identity-service-authentication-context.xml
  repository/src/test/java/org/alfresco/AllUnitTestsSuite.java
  repository/src/test/java/org/alfresco/repo/security/authentication/identityservice/IdentityServiceAuthenticationComponentTest.java
  repository/src/test/java/org/alfresco/repo/security/authentication/identityservice/IdentityServiceRemoteUserMapperTest.java
  repository/src/test/java/org/alfresco/repo/security/authentication/identityservice/LazyInstantiatingIdentityServiceFacadeUnitTest.java
  repository/src/test/java/org/alfresco/repo/security/authentication/identityservice/SpringBasedIdentityServiceFacadeUnitTest.java
  repository/src/test/java/org/alfresco/repo/security/authentication/identityservice/SpringOAuth2ClientUnitTest.java
Labels: PR: partially-approved

#1822 ACS-4863 Allow referencing nodes by aliases for tag and category application.
  remote-api/src/main/java/org/alfresco/rest/api/impl/CategoriesImpl.java
  remote-api/src/main/java/org/alfresco/rest/api/impl/TagsImpl.java
  remote-api/src/test/java/org/alfresco/rest/api/impl/CategoriesImplTest.java
  remote-api/src/test/java/org/alfresco/rest/api/impl/TagsImplTest.java
Labels: PR: partially-approved

#1829 ACS-4863 Restore code to allow aliases in tag and category APIs.
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/tags/nodes/GetNodeTagsTests.java
  remote-api/src/main/java/org/alfresco/rest/api/impl/CategoriesImpl.java
  remote-api/src/main/java/org/alfresco/rest/api/impl/TagsImpl.java
  remote-api/src/test/java/org/alfresco/rest/api/impl/CategoriesImplTest.java
  remote-api/src/test/java/org/alfresco/rest/api/impl/TagsImplTest.java
Labels: PR: partially-approved

#1826 ACS-4863 Add method validateOrLookupNode without path.
  remote-api/src/main/java/org/alfresco/rest/api/Nodes.java
  remote-api/src/main/java/org/alfresco/rest/api/impl/CategoriesImpl.java
  remote-api/src/main/java/org/alfresco/rest/api/impl/NodesImpl.java
  remote-api/src/main/java/org/alfresco/rest/api/impl/QueriesImpl.java
  remote-api/src/main/java/org/alfresco/rest/api/impl/RenditionsImpl.java
  remote-api/src/main/java/org/alfresco/rest/api/impl/TagsImpl.java
  remote-api/src/main/java/org/alfresco/rest/api/impl/mapper/rules/RestRuleModelMapper.java
  remote-api/src/main/java/org/alfresco/rest/api/impl/mapper/rules/RestRuleSimpleConditionModelMapper.java
  remote-api/src/main/java/org/alfresco/rest/api/impl/rules/ActionParameterConverter.java
  remote-api/src/main/java/org/alfresco/rest/api/impl/rules/NodeValidator.java
  remote-api/src/main/java/org/alfresco/rest/api/nodes/NodeActionDefinitionsRelation.java
  remote-api/src/main/java/org/alfresco/rest/api/nodes/NodeParentsRelation.java
  remote-api/src/main/java/org/alfresco/rest/api/nodes/NodeSecondaryChildrenRelation.java
  remote-api/src/main/java/org/alfresco/rest/api/nodes/NodeSourcesRelation.java
  remote-api/src/main/java/org/alfresco/rest/api/nodes/NodeTargetsRelation.java
  remote-api/src/main/java/org/alfresco/rest/api/nodes/NodeVersionsRelation.java
  remote-api/src/test/java/org/alfresco/rest/api/impl/CategoriesImplTest.java
  remote-api/src/test/java/org/alfresco/rest/api/impl/TagsImplTest.java
  remote-api/src/test/java/org/alfresco/rest/api/impl/mapper/rules/RestRuleModelMapperTest.java
  remote-api/src/test/java/org/alfresco/rest/api/impl/mapper/rules/RestRuleSimpleConditionModelMapperTest.java
  remote-api/src/test/java/org/alfresco/rest/api/impl/rules/ActionParameterConverterTest.java
  remote-api/src/test/java/org/alfresco/rest/api/impl/rules/NodeValidatorTest.java
  remote-api/src/test/java/org/alfresco/rest/api/search/ResultMapperTests.java
Labels: PR: unreviewed

#1790 ACS-4779:Count field issue for GET call
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/tags/GetTagTests.java
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/tags/GetTagsTests.java
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/tags/TagsDataPrep.java
  remote-api/src/main/java/org/alfresco/rest/api/impl/TagsImpl.java
  remote-api/src/test/java/org/alfresco/rest/api/impl/TagsImplTest.java
  remote-api/src/test/java/org/alfresco/rest/api/tests/SharedLinkApiTest.java
Labels: PR: unreviewed

#1609 Feature/aca 4619 self service user password reset adw
  repository/src/main/java/org/alfresco/repo/security/authentication/ResetPasswordServiceImpl.java
  repository/src/main/java/org/alfresco/util/UrlUtil.java
  repository/src/main/resources/alfresco/client/config/repo-clients-apps.properties
  repository/src/main/resources/alfresco/templates/reset-password-email-templates/forgot-password-email-template.ftl
  repository/src/test/java/org/alfresco/repo/security/authentication/ResetPasswordServiceImplTest.java
Labels: PR: reviewed-approved

#1837 [ACS-4929][ACS-4927] transform-service and transform-core version bump
  pom.xml
Labels: PR: reviewed-approved

#1833 [ACS-4636] create tag count param support
  remote-api/src/main/java/org/alfresco/rest/api/Tags.java
  remote-api/src/main/java/org/alfresco/rest/api/impl/TagsImpl.java
  remote-api/src/main/java/org/alfresco/rest/api/nodes/NodeTagsRelation.java
  remote-api/src/test/java/org/alfresco/rest/api/impl/TagsImplTest.java
Labels: PR: partially-approved

#1836 ACS-4847 Expose authorization code and refresh token grant types for the AOS
  repository/src/main/java/org/alfresco/repo/security/authentication/identityservice/IdentityServiceAuthenticationComponent.java
  repository/src/main/java/org/alfresco/repo/security/authentication/identityservice/IdentityServiceFacade.java
  repository/src/main/java/org/alfresco/repo/security/authentication/identityservice/IdentityServiceFacadeFactoryBean.java
  repository/src/main/java/org/alfresco/repo/security/authentication/identityservice/IdentityServiceRemoteUserMapper.java
  repository/src/main/java/org/alfresco/repo/security/authentication/identityservice/SpringBasedIdentityServiceFacade.java
  repository/src/test/java/org/alfresco/repo/security/authentication/identityservice/IdentityServiceAuthenticationComponentTest.java
  repository/src/test/java/org/alfresco/repo/security/authentication/identityservice/IdentityServiceRemoteUserMapperTest.java
  repository/src/test/java/org/alfresco/repo/security/authentication/identityservice/LazyInstantiatingIdentityServiceFacadeUnitTest.java
  repository/src/test/java/org/alfresco/repo/security/authentication/identityservice/SpringBasedIdentityServiceFacadeUnitTest.java
Labels: PR: unreviewed

#1735 [ACS-4459] Investigate and extend/universalize current custom Solr mTLS implementation in Repository
  .github/workflows/ci.yml
  core/pom.xml
  core/src/main/java/org/alfresco/httpclient/HttpClient4Factory.java
  core/src/main/java/org/alfresco/httpclient/HttpClientConfig.java
  core/src/main/java/org/alfresco/httpclient/HttpClientException.java
  repository/src/main/java/org/alfresco/repo/content/transform/LocalTransformImpl.java
  repository/src/main/java/org/alfresco/repo/content/transform/LocalTransformServiceRegistry.java
  repository/src/main/java/org/alfresco/repo/content/transform/RemoteTransformerClient.java
  repository/src/main/java/org/alfresco/transform/registry/CombinedConfig.java
  repository/src/main/resources/alfresco/rendition-services2-context.xml
  repository/src/main/resources/alfresco/repository.properties
  repository/src/test/java/org/alfresco/MTLSTestSuite.java
  repository/src/test/java/org/alfresco/repo/content/transform/RemoteTransformerClientTest.java
  repository/src/test/java/org/alfresco/repo/security/mtls/LocalTransformClientWithMTLSIntegrationTest.java
  repository/src/test/java/org/alfresco/transform/registry/LocalTransformServiceRegistryConfigTest.java
  repository/src/test/resources/test/alfresco/test-renditions-context.xml
  scripts/ci/docker-compose/docker-compose.yaml
  scripts/ci/generate_keystores.sh
Labels: PR: unreviewed

#1846 ACS-4847 Bump AOS module
  pom.xml
Labels: PR: partially-approved
