Repository Alfresco/alfresco-community-repo, pull requests merged in 2023-04, with the labels that each got.

#1853 ACS-4893 ACS-4890 Restore connection/TLS/mTLS IDS configuration
  repository/src/main/java/org/alfresco/repo/security/authentication/identityservice/IdentityServiceConfig.java
  repository/src/main/java/org/alfresco/repo/security/authentication/identityservice/IdentityServiceFacadeFactoryBean.java
  repository/src/main/resources/alfresco/subsystems/Authentication/identity-service/identity-service-authentication-context.xml
Labels: PR: partially-approved

#1858 ACS-4891 Configurable Public Key Cache
  repository/src/main/java/org/alfresco/repo/security/authentication/identityservice/IdentityServiceConfig.java
  repository/src/main/java/org/alfresco/repo/security/authentication/identityservice/IdentityServiceFacadeFactoryBean.java
  repository/src/main/resources/alfresco/subsystems/Authentication/identity-service/identity-service-authentication-context.xml
Labels: PR: unreviewed

#1854 ACS-4970 Bump json-path to 2.8.0 and json-smart to 2.4.10
  pom.xml
Labels: PR: partially-approved

#1859 [ACS-4839] bump ATS versions
  pom.xml
Labels: PR: reviewed-approved

#1860 ACS-4971 Restore IDS public client configuration
  repository/src/main/java/org/alfresco/repo/security/authentication/identityservice/IdentityServiceConfig.java
  repository/src/main/java/org/alfresco/repo/security/authentication/identityservice/IdentityServiceFacadeFactoryBean.java
  repository/src/main/resources/alfresco/subsystems/Authentication/identity-service/identity-service-authentication-context.xml
  repository/src/main/resources/alfresco/subsystems/Authentication/identity-service/identity-service-authentication.properties
Labels: PR: unreviewed

#1861 Feature/acs 4462 mtls e2e test
  packaging/tests/tas-restapi/src/main/java/org/alfresco/rest/core/RestWrapper.java
  repository/src/main/java/org/alfresco/repo/content/transform/RemoteTransformerClient.java
Labels: PR: partially-approved

#1843 Feature/acs 4718 remove rmi email service
  repository/src/main/java/org/alfresco/email/server/EmailServer.java
  repository/src/main/java/org/alfresco/email/server/EmailServiceRemotable.java
  repository/src/main/java/org/alfresco/email/server/impl/subetha/SubethaEmailMessage.java
  repository/src/main/java/org/alfresco/email/server/impl/subetha/SubethaEmailMessagePart.java
  repository/src/main/java/org/alfresco/util/remote/RemotableInputStream.java
  repository/src/main/java/org/alfresco/util/remote/server/AbstractRemoteInputStreamServer.java
  repository/src/main/java/org/alfresco/util/remote/server/AlfrescoRMIServiceExporter.java
  repository/src/main/java/org/alfresco/util/remote/server/RemoteInputStreamServer.java
  repository/src/main/java/org/alfresco/util/remote/server/RmiRemoteInputStreamServer.java
  repository/src/main/resources/alfresco/extension/bm-remote-loader-context.xml.sample
Labels: PR: reviewed-approved

#1862 MNT-22888: Fix for WikiPages with Link
  repository/pom.xml
Labels: PR: reviewed-approved

#1863 Migrate to GitHub Actions
  .ci.settings.xml
  .github/workflows/ci.yml
  .github/workflows/master_release.yml
  .travis.yml
  README.md
  amps/ags/ci/scripts/getLogs.sh
  amps/ags/rm-automation/rm-automation-community-rest-api/src/test/java/org/alfresco/rest/rm/community/smoke/DispositionScheduleLinkedRecordsTest.java
  amps/ags/rm-automation/rm-automation-community-rest-api/src/test/java/org/alfresco/rest/rm/community/utils/AlphabeticalPriorityInterceptor.java
  amps/ags/rm-automation/rm-automation-community-rest-api/src/test/resources/testng.xml
  packaging/tests/scripts/output_tests_run.sh
  packaging/tests/scripts/start-compose.sh
  packaging/tests/tas-webdav/src/test/java/org/alfresco/webdav/WebDavTest.java
  repository/src/main/java/org/alfresco/repo/urlshortening/BitlyUrlShortenerImpl.java
  repository/src/main/resources/alfresco/repository.properties
  repository/src/test/java/org/alfresco/AllUnitTestsSuite.java
  repository/src/test/java/org/alfresco/repo/urlshortening/BitlyUrlShortenerTest.java
  scripts/ci/build.sh
  scripts/ci/build_functions.sh
  scripts/ci/cleanup_cache.sh
  scripts/ci/docker-compose/docker-compose-db.yaml
  scripts/ci/docker-compose/docker-compose.yaml
  scripts/ci/generate_keystores.sh
  scripts/ci/init.sh
  scripts/ci/maven_release.sh
  scripts/ci/prepare.sh
  scripts/ci/tests/AppContext05TestSuite-setup.sh
  scripts/ci/update_downstream.sh
  scripts/ci/verify_release_tag.sh
  scripts/prepare_buildx.sh
  scripts/travis/build.sh
  scripts/travis/source_clear.sh
Labels: PR: reviewed-approved

#1864 [ACS-4462] Add connection manager builder for httpClient4Factory
  core/src/main/java/org/alfresco/httpclient/HttpClient4Factory.java
Labels: PR: unreviewed

#1867 Fix/revert changes forgot password
  repository/src/main/java/org/alfresco/repo/security/authentication/ResetPasswordServiceImpl.java
  repository/src/main/java/org/alfresco/util/UrlUtil.java
  repository/src/main/resources/alfresco/client/config/repo-clients-apps.properties
  repository/src/main/resources/alfresco/templates/reset-password-email-templates/forgot-password-email-template.ftl
  repository/src/main/resources/alfresco/templates/reset-password-email-templates/images/adw_logo.png
  repository/src/main/resources/alfresco/templates/reset-password-email-templates/images/hyland_logo.png
  repository/src/test/java/org/alfresco/repo/security/authentication/ResetPasswordServiceImplTest.java
Labels: PR: reviewed-approved

#1855 ACS-4966 Add path to Category API
  packaging/tests/tas-restapi/src/main/java/org/alfresco/rest/model/RestCategoryModel.java
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/categories/CategoriesPathTests.java
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/categories/CategoriesRestTest.java
  remote-api/src/main/java/org/alfresco/rest/api/impl/CategoriesImpl.java
  remote-api/src/main/java/org/alfresco/rest/api/model/Category.java
  remote-api/src/test/java/org/alfresco/rest/api/impl/CategoriesImplTest.java
Labels: PR: unreviewed

#1875 Set property values to the ones being set for sharedFileStoreConnector
  repository/src/main/resources/alfresco/repository.properties
Labels: PR: unreviewed

#1880 ACS-4923 Add support for include=count on GET and PUT tag.
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/tags/GetTagTests.java
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/tags/UpdateTagTests.java
  remote-api/src/main/java/org/alfresco/rest/api/Tags.java
  remote-api/src/main/java/org/alfresco/rest/api/impl/TagsImpl.java
  remote-api/src/main/java/org/alfresco/rest/api/model/Tag.java
  remote-api/src/main/java/org/alfresco/rest/api/tags/TagsEntityResource.java
  remote-api/src/test/java/org/alfresco/rest/api/impl/TagsImplTest.java
  repository/src/main/java/org/alfresco/repo/tagging/TaggingServiceImpl.java
  repository/src/main/java/org/alfresco/service/cmr/tagging/TaggingService.java
Labels: PR: partially-approved

#1885 Revert "Bump docker-maven-plugin from 0.42.0 to 0.42.1 (#1866)"
  pom.xml
Labels: PR: partially-approved

#1886 Bump docker-maven-plugin from 0.42.0 to 0.42.1
  pom.xml
Labels: PR: partially-approved

#1806 ACS-4025: Support include count and orderBy count for GET /tags
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/tags/GetTagsTests.java
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/tags/TagsDataPrep.java
  remote-api/src/main/java/org/alfresco/rest/api/impl/TagsImpl.java
  remote-api/src/test/java/org/alfresco/rest/api/impl/TagsImplTest.java
  repository/src/main/java/org/alfresco/repo/jscript/Classification.java
  repository/src/main/java/org/alfresco/repo/search/impl/AbstractCategoryServiceImpl.java
  repository/src/main/java/org/alfresco/repo/tagging/TaggingServiceImpl.java
  repository/src/main/java/org/alfresco/service/cmr/search/CategoryService.java
  repository/src/main/java/org/alfresco/service/cmr/tagging/TaggingService.java
Labels: PR: unreviewed

#1888 ACS-5083 Bump Spring to 5.3.27
  pom.xml
Labels: PR: partially-approved

#1891 ACS-5068 Upgrade to SS 2.0.7-A5. [ags]
  amps/ags/rm-community/rm-community-repo/.env
  packaging/tests/environment/.env
Labels: PR: partially-approved

#1895 Update transform-service to 2.1.0-A9, transform-coreto 3.1.0-A12
  pom.xml
Labels: PR: unreviewed

#1897 ACS-5100 Include authorization uri in the ClientRegistration
  repository/src/main/java/org/alfresco/repo/security/authentication/identityservice/IdentityServiceFacadeFactoryBean.java
Labels: PR: partially-approved

#1906 ACS-5075 and ACS-4832 Bump t-core and t-service to 3.1.0 and 2.1.0
  pom.xml
Labels: PR: reviewed-approved
