Repository Alfresco/alfresco-community-repo, pull requests merged in 2023-01, with the labels that each got.

#1654 MNT-23263 Changes done for missing properties after moving record between categories
  amps/ags/rm-community/rm-community-repo/source/java/org/alfresco/module/org_alfresco_module_rm/model/behaviour/RecordsManagementSearchBehaviour.java
Labels: PR: unreviewed

#1658 ACS-2967: While LocalPipelineTransform was reported to cause a warnin…
  repository/src/main/java/org/alfresco/repo/content/transform/LocalFailoverTransform.java
Labels: PR: unreviewed

#1660 [MNT-22965] Updated RM permissions
  amps/ags/rm-community/rm-community-repo/config/alfresco/module/org_alfresco_module_rm/alfresco-global.properties
Labels: PR: partially-approved

#1657 [MNT-23379] Set site manager permission if node belongs to a site and inheritance flag is disabled
  remote-api/src/main/java/org/alfresco/rest/api/impl/NodesImpl.java
  remote-api/src/test/java/org/alfresco/rest/api/tests/NodeApiTest.java
Labels: PR: reviewed-approved

#1655 ACS-4034: Assign a piece of content to a category
  packaging/tests/tas-restapi/src/main/java/org/alfresco/rest/model/RestCategoryLinkBodyModel.java
  packaging/tests/tas-restapi/src/main/java/org/alfresco/rest/requests/Node.java
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/categories/LinkToCategoriesTests.java
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/categories/UpdateCategoriesTests.java
  remote-api/src/main/java/org/alfresco/rest/api/Categories.java
  remote-api/src/main/java/org/alfresco/rest/api/categories/NodesCategoryLinksRelation.java
  remote-api/src/main/java/org/alfresco/rest/api/impl/CategoriesImpl.java
  remote-api/src/main/java/org/alfresco/rest/api/model/Category.java
  remote-api/src/main/resources/alfresco/public-rest-context.xml
  remote-api/src/test/java/org/alfresco/rest/api/impl/CategoriesImplTest.java
Labels: PR: partially-approved

#1668 [MNT-23379] Added sleep between document creation and update to prevent test failures
  remote-api/src/test/java/org/alfresco/rest/api/tests/NodeApiTest.java
Labels: PR: unreviewed

#1667 [MNT-23379] Set site manager permission if node belongs to a site and inheritance flag is disabled (#1657)
  remote-api/src/main/java/org/alfresco/rest/api/impl/NodesImpl.java
  remote-api/src/test/java/org/alfresco/rest/api/tests/NodeApiTest.java
Labels: PR: unreviewed

#1631 ACS-3841 Migrate to GHA
  .github/.ci.settings.xml
  .github/workflows/ci.yml
  .github/workflows/master_release.yml
  .travis.yml
  README.md
  amps/ags/ci/scripts/getLogs.sh
  amps/ags/rm-automation/rm-automation-community-rest-api/src/test/java/org/alfresco/rest/rm/community/utils/AlphabeticalPriorityInterceptor.java
  amps/ags/rm-automation/rm-automation-community-rest-api/src/test/resources/testng.xml
  amps/pom.xml
  scripts/ci/build.sh
  scripts/ci/build_functions.sh
  scripts/ci/cleanup_cache.sh
  scripts/ci/docker-compose/docker-compose-db.yaml
  scripts/ci/docker-compose/docker-compose.yaml
  scripts/ci/init.sh
  scripts/ci/maven_release.sh
  scripts/ci/prepare.sh
  scripts/ci/tests/AppContext05TestSuite-setup.sh
  scripts/ci/update_downstream.sh
  scripts/ci/verify_release_tag.sh
  scripts/travis/source_clear.sh
Labels: PR: unreviewed

#1671 ACS-3841 Use AlphabeticalPriorityInterceptor from alfresco-tas-utility
  amps/ags/rm-automation/rm-automation-community-rest-api/src/test/java/org/alfresco/rest/rm/community/utils/AlphabeticalPriorityInterceptor.java
  amps/ags/rm-automation/rm-automation-community-rest-api/src/test/resources/testng.xml
  pom.xml
Labels: PR: partially-approved

#1674 ACS-4160: Fixing and making GetTopCategories more re-usable
  repository/src/main/java/org/alfresco/repo/search/impl/AbstractCategoryServiceImpl.java
  repository/src/main/java/org/alfresco/repo/search/impl/solr/SolrCategoryServiceImpl.java
  repository/src/test/java/org/alfresco/repo/search/impl/solr/SolrCategoryServiceImplTest.java
Labels: PR: unreviewed

#1672 ACS-4033: List linked categories for a particular node
  packaging/tests/tas-restapi/src/main/java/org/alfresco/rest/model/RestCategoryLinkBodyModel.java
  packaging/tests/tas-restapi/src/main/java/org/alfresco/rest/requests/Node.java
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/categories/CategoriesRestTest.java
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/categories/LinkToCategoriesTests.java
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/categories/ListCategoriesForNodeTests.java
  remote-api/src/main/java/org/alfresco/rest/api/Categories.java
  remote-api/src/main/java/org/alfresco/rest/api/categories/NodesCategoryLinksRelation.java
  remote-api/src/main/java/org/alfresco/rest/api/impl/CategoriesImpl.java
  remote-api/src/main/java/org/alfresco/rest/framework/resource/SerializablePagedCollection.java
  remote-api/src/main/java/org/alfresco/rest/framework/resource/parameters/ArrayListPage.java
  remote-api/src/main/java/org/alfresco/rest/framework/resource/parameters/ListPage.java
  remote-api/src/test/java/org/alfresco/rest/api/categories/NodesCategoryLinksRelationTest.java
  remote-api/src/test/java/org/alfresco/rest/api/impl/CategoriesImplTest.java
  remote-api/src/test/java/org/alfresco/rest/framework/resource/parameters/ArrayListPageTest.java
Labels: PR: unreviewed

#1592 [MNT-23396] [MNT-23391] Change call stack depth limit to be only applied to custom scripts / Clean scope only for custom scripts
  repository/src/main/java/org/alfresco/repo/jscript/AlfrescoContextFactory.java
  repository/src/main/java/org/alfresco/repo/jscript/AlfrescoScriptContext.java
  repository/src/main/java/org/alfresco/repo/jscript/AlfrescoScriptThreadMxBeanWrapper.java
  repository/src/main/java/org/alfresco/repo/jscript/RhinoScriptProcessor.java
  repository/src/main/resources/alfresco/repository.properties
Labels: PR: unreviewed

#1679 [MNT-23396] [MNT-23391] Change call stack depth limit to be only applied to custom scripts / Clean scope only for custom scripts (#1592)
  repository/src/main/java/org/alfresco/repo/jscript/AlfrescoContextFactory.java
  repository/src/main/java/org/alfresco/repo/jscript/AlfrescoScriptContext.java
  repository/src/main/java/org/alfresco/repo/jscript/AlfrescoScriptThreadMxBeanWrapper.java
  repository/src/main/java/org/alfresco/repo/jscript/RhinoScriptProcessor.java
  repository/src/main/resources/alfresco/repository.properties
Labels: PR: unreviewed

#1675 Acs 4400 multiple same categories can be linked from content or folder
  packaging/tests/tas-restapi/src/main/java/org/alfresco/rest/core/assertion/ModelAssertion.java
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/categories/LinkToCategoriesTests.java
  remote-api/src/main/java/org/alfresco/rest/api/impl/CategoriesImpl.java
  remote-api/src/test/java/org/alfresco/rest/api/impl/CategoriesImplTest.java
Labels: PR: unreviewed

#1685 Feature/acs 4089 backport test fix
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/actions/email/EmailTemplateTest.java
Labels: PR: unreviewed

#1690 PRODSEC-6989 Upgrade cxf and spring framework
  pom.xml
Labels: PR: reviewed-approved

#1692 ACS-4177 Improve rendition API tests retry logic
  packaging/tests/tas-restapi/src/main/java/org/alfresco/rest/requests/Node.java
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/renditions/RenditionIntegrationTests.java
Labels: PR: partially-approved

#1695 Upgrade Spring framework and CXF
  pom.xml
Labels: PR: partially-approved

#1698 ACS-4144 Add support for getting categories in ES by allowing access to the prefix helper method.
  repository/src/main/java/org/alfresco/repo/search/impl/AbstractCategoryServiceImpl.java
Labels: PR: partially-approved

#1670 ACS-4035: support for removing a piece of content from a category
  packaging/tests/tas-restapi/src/main/java/org/alfresco/rest/requests/Node.java
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/categories/LinkToCategoriesTests.java
  remote-api/src/main/java/org/alfresco/rest/api/Categories.java
  remote-api/src/main/java/org/alfresco/rest/api/categories/NodesCategoryLinksRelation.java
  remote-api/src/main/java/org/alfresco/rest/api/impl/CategoriesImpl.java
  remote-api/src/test/java/org/alfresco/rest/api/impl/CategoriesImplTest.java
Labels: PR: unreviewed

#1691 ACS-4362: Fix returned HTTP error status for invalid note type
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/categories/LinkToCategoriesTests.java
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/categories/ListCategoriesForNodeTests.java
  remote-api/src/main/java/org/alfresco/rest/api/impl/CategoriesImpl.java
  remote-api/src/main/java/org/alfresco/rest/framework/core/exceptions/InvalidNodeTypeException.java
  remote-api/src/main/resources/alfresco/messages/rest-framework-messages.properties
  remote-api/src/main/resources/alfresco/public-rest-context.xml
  remote-api/src/test/java/org/alfresco/rest/api/impl/CategoriesImplTest.java
  remote-api/src/test/resources/test-rest-context.xml
Labels: PR: unreviewed

#1702 ACS-3750 Update alfresco-build-tools to v1.32.0
  .github/workflows/ci.yml
  .github/workflows/master_release.yml
Labels: PR: partially-approved

#1696 [MNT-23424] Clean Rhino scope only for custom scripts
  repository/src/main/java/org/alfresco/repo/jscript/RhinoScriptProcessor.java
Labels: PR: unreviewed

#1703 MNT-23411 Option to disable events2
  repository/src/main/java/org/alfresco/repo/domain/permissions/FixedAclUpdater.java
  repository/src/main/java/org/alfresco/repo/event2/EventGenerator.java
  repository/src/main/resources/alfresco/events2-context.xml
  repository/src/main/resources/alfresco/repository.properties
  repository/src/test/java/org/alfresco/repo/event2/EventGeneratorDisabledTest.java
  repository/src/test/java/org/alfresco/repo/event2/RepoEvent2ITSuite.java
Labels: PR: reviewed-approved

#1688 [MNT-23414] Bulk import - convert empty values to null for certain types
  repository/src/main/java/org/alfresco/repo/bulkimport/metadataloaders/AbstractMapBasedMetadataLoader.java
Labels: PR: reviewed-approved

#1705 [ACS-4418] Align IE/SS versions
  amps/ags/rm-community/rm-community-repo/.env
  packaging/tests/environment/.env
Labels: PR: reviewed-approved

#1706 [MNT-23414] Bulk import - convert empty values to null for certain types (#1688)
  repository/src/main/java/org/alfresco/repo/bulkimport/metadataloaders/AbstractMapBasedMetadataLoader.java
Labels: PR: unreviewed

#1712 MNT-23411 Option to disable events2 (#1703)
  repository/src/main/java/org/alfresco/repo/domain/permissions/FixedAclUpdater.java
  repository/src/main/java/org/alfresco/repo/event2/EventGenerator.java
  repository/src/main/resources/alfresco/events2-context.xml
  repository/src/main/resources/alfresco/repository.properties
  repository/src/test/java/org/alfresco/repo/event2/EventGeneratorDisabledTest.java
  repository/src/test/java/org/alfresco/repo/event2/RepoEvent2ITSuite.java
Labels: PR: unreviewed

#1713 ACS-4455 Bump alfresco-build-tools to v1.33.0
  .ci.settings.xml
  .github/workflows/ci.yml
  .github/workflows/master_release.yml
  scripts/ci/init.sh
Labels: PR: partially-approved
