Repository Alfresco/alfresco-community-repo, pull requests merged in 2023-02, with the labels that each got.

#1720 ACS-4155 Update webscripts since we only index full category path in ES.
  amps/share-services/src/main/resources/alfresco/templates/webscripts/org/alfresco/slingshot/documentlibrary-v2/filters.lib.js
  amps/share-services/src/main/resources/alfresco/templates/webscripts/org/alfresco/slingshot/documentlibrary/filters.lib.js
  repository/src/main/resources/alfresco/bootstrap/webscripts/categorysearch.get.js
  repository/src/main/resources/alfresco/extension/scheduled-action-services-context.xml.sample
  repository/src/test/java/org/alfresco/repo/tenant/MultiTDemoTest.java
Labels: PR: partially-approved

#1714 ACS-4180 Add localized properties to the repo event
  data-model/src/main/java/org/alfresco/service/cmr/repository/MLText.java
  repository/src/main/java/org/alfresco/repo/event2/EventConsolidator.java
  repository/src/main/java/org/alfresco/repo/event2/NodeResourceHelper.java
  repository/src/test/java/org/alfresco/repo/event2/AbstractContextAwareRepoEvent.java
  repository/src/test/java/org/alfresco/repo/event2/CreateRepoEventIT.java
  repository/src/test/java/org/alfresco/repo/event2/DeleteRepoEventIT.java
  repository/src/test/java/org/alfresco/repo/event2/NodeResourceHelperUnitTest.java
  repository/src/test/java/org/alfresco/repo/event2/RepoEvent2UnitSuite.java
  repository/src/test/java/org/alfresco/repo/event2/UpdateRepoEventIT.java
Labels: PR: reviewed-approved

#1722 ACS-3750 Improve branch detection in if conditions
  .github/workflows/ci.yml
Labels: PR: partially-approved

#1723 MNT-23411 Option to disable events2 (#1703)
  repository/src/main/java/org/alfresco/repo/domain/permissions/FixedAclUpdater.java
  repository/src/main/java/org/alfresco/repo/event2/EventGenerator.java
  repository/src/main/resources/alfresco/events2-context.xml
  repository/src/main/resources/alfresco/repository.properties
  repository/src/test/java/org/alfresco/repo/event2/EventGeneratorDisabledTest.java
  repository/src/test/java/org/alfresco/repo/event2/RepoEvent2ITSuite.java
Labels: PR: unreviewed

#1724 ACS-4154: Add category count to relevant CRUD endpoints for categories
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/categories/CategoriesCountTests.java
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/categories/CategoriesRestTest.java
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/categories/CreateCategoriesTests.java
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/categories/UpdateCategoriesTests.java
  remote-api/src/main/java/org/alfresco/rest/api/Categories.java
  remote-api/src/main/java/org/alfresco/rest/api/categories/CategoriesEntityResource.java
  remote-api/src/main/java/org/alfresco/rest/api/categories/NodesCategoryLinksRelation.java
  remote-api/src/main/java/org/alfresco/rest/api/categories/SubcategoriesRelation.java
  remote-api/src/main/java/org/alfresco/rest/api/impl/CategoriesImpl.java
  remote-api/src/main/java/org/alfresco/rest/api/model/Category.java
  remote-api/src/test/java/org/alfresco/AppContextExtraTestSuite.java
  remote-api/src/test/java/org/alfresco/rest/api/CategoriesUnitTests.java
  remote-api/src/test/java/org/alfresco/rest/api/categories/CategoriesEntityResourceTest.java
  remote-api/src/test/java/org/alfresco/rest/api/categories/NodesCategoryLinksRelationTest.java
  remote-api/src/test/java/org/alfresco/rest/api/categories/SubcategoriesRelationTest.java
  remote-api/src/test/java/org/alfresco/rest/api/impl/CategoriesImplTest.java
  repository/src/main/java/org/alfresco/service/cmr/search/CategoryService.java
Labels: PR: unreviewed

#1736 ACS-3750 Use set Git token instead of cached one
  .github/workflows/master_release.yml
Labels: PR: partially-approved

#1709 ACS-4027: Introduce changes to support removing tag from all associated nodes
  packaging/tests/tas-restapi/src/main/java/org/alfresco/rest/requests/Tags.java
  remote-api/src/main/java/org/alfresco/rest/api/Tags.java
  remote-api/src/main/java/org/alfresco/rest/api/impl/TagsImpl.java
  remote-api/src/main/java/org/alfresco/rest/api/tags/TagsEntityResource.java
  remote-api/src/main/resources/alfresco/public-rest-context.xml
  remote-api/src/test/java/org/alfresco/rest/api/impl/TagsImplTest.java
Labels: PR: reviewed-approved

#1741 Changed line separation formatting to unix
  remote-api/src/main/java/org/alfresco/rest/api/impl/TagsImpl.java
Labels: PR: reviewed-approved

#1748 ACS-4026: Create orphaned tag with POST /tags
  packaging/tests/tas-restapi/src/main/java/org/alfresco/rest/model/RestTagModel.java
  packaging/tests/tas-restapi/src/main/java/org/alfresco/rest/requests/coreAPI/RestCoreAPI.java
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/tags/CreateTagsTests.java
  remote-api/src/main/java/org/alfresco/rest/api/Tags.java
  remote-api/src/main/java/org/alfresco/rest/api/impl/TagsImpl.java
  remote-api/src/main/java/org/alfresco/rest/api/model/Tag.java
  remote-api/src/main/java/org/alfresco/rest/api/tags/TagsEntityResource.java
  remote-api/src/test/java/org/alfresco/AppContextExtraTestSuite.java
  remote-api/src/test/java/org/alfresco/rest/api/TagsUnitTests.java
  remote-api/src/test/java/org/alfresco/rest/api/impl/CategoriesImplTest.java
  remote-api/src/test/java/org/alfresco/rest/api/impl/TagsImplTest.java
  remote-api/src/test/java/org/alfresco/rest/api/tags/TagsEntityResourceTest.java
  repository/src/main/java/org/alfresco/repo/tagging/TaggingServiceImpl.java
  repository/src/main/java/org/alfresco/service/cmr/tagging/TaggingService.java
  repository/src/test/java/org/alfresco/AllUnitTestsSuite.java
  repository/src/test/java/org/alfresco/repo/tagging/TaggingServiceImplUnitTest.java
Labels: PR: unreviewed

#1743 ACS-4027: add E2Es for DELETE /tags/{tagsId} endpoint
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/tags/DeleteTagsTests.java
  packaging/tests/tas-restapi/src/test/java/org/alfresco/rest/tags/TagsDataPrep.java
Labels: PR: reviewed-approved

#1717 [MNT-22633] Creation, Modification TimeStamp values setted for download as zip
  repository/src/main/java/org/alfresco/repo/download/ZipDownloadExporter.java
Labels: PR: partially-approved

#1755 [ACS-3960][ACS-4339] Count is only returned for a tag if it is greater than zero
  remote-api/src/main/java/org/alfresco/rest/api/impl/TagsImpl.java
  remote-api/src/test/java/org/alfresco/rest/api/impl/TagsImplTest.java
Labels: PR: unreviewed

#1761 ACS-4424 AGS Community tests for ES
  amps/ags/rm-automation/rm-automation-community-rest-api/src/test/java/org/alfresco/rest/rm/community/records/InplaceRecordSearchTests.java
  amps/ags/rm-automation/rm-automation-community-rest-api/src/test/java/org/alfresco/rest/rm/community/search/SearchDocumentsV1Test.java
  amps/ags/rm-automation/rm-automation-community-rest-api/src/test/java/org/alfresco/rest/rm/community/smoke/DispositionScheduleLinkedRecordsTest.java
Labels: PR: partially-approved

#1758 ACS-4653 Migrate to GHA on 721
  .ci.settings.xml
  .github/workflows/ci.yml
  .github/workflows/master_release.yml
  .travis.yml
  README.md
  amps/ags/ci/scripts/getLogs.sh
  packaging/tests/scripts/output_logs_for_failures.sh
  packaging/tests/scripts/output_tests_run.sh
  packaging/tests/scripts/start-compose.sh
  packaging/tests/tas-webdav/src/test/java/org/alfresco/webdav/WebDavTest.java
  pom.xml
  scripts/ci/build.sh
  scripts/ci/build_functions.sh
  scripts/ci/cleanup_cache.sh
  scripts/ci/docker-compose/docker-compose-db.yaml
  scripts/ci/docker-compose/docker-compose.yaml
  scripts/ci/init.sh
  scripts/ci/maven_release.sh
  scripts/ci/prepare.sh
  scripts/ci/tests/AppContext05TestSuite-setup.sh
  scripts/ci/update_downstream.sh
  scripts/ci/verify_release_tag.sh
  scripts/travis/build.sh
  scripts/travis/cleanup_cache.sh
  scripts/travis/source_clear.sh
Labels: PR: reviewed-approved

#1765 ACS-4653 GHA - Fix mySQL tests
  .github/workflows/ci.yml
  scripts/ci/docker-compose/docker-compose-db.yaml
Labels: PR: reviewed-approved

#1768 ACS-3750 Fix cancelling workflow
  .github/workflows/master_release.yml
Labels: PR: partially-approved

#1777 Feature/acs 4653 migrate to gha
  .github/.ci.settings.xml
  .github/workflows/ci.yml
  .github/workflows/master_release.yml
  .travis.yml
  README.md
  amps/ags/ci/scripts/getLogs.sh
  amps/ags/rm-automation/rm-automation-community-rest-api/src/test/java/org/alfresco/rest/rm/community/utils/AlphabeticalPriorityInterceptor.java
  amps/ags/rm-automation/rm-automation-community-rest-api/src/test/resources/testng.xml
  amps/pom.xml
  scripts/ci/build.sh
  scripts/ci/build_functions.sh
  scripts/ci/cleanup_cache.sh
  scripts/ci/docker-compose/docker-compose-db.yaml
  scripts/ci/docker-compose/docker-compose.yaml
  scripts/ci/init.sh
  scripts/ci/maven_release.sh
  scripts/ci/prepare.sh
  scripts/ci/tests/AppContext05TestSuite-setup.sh
  scripts/ci/update_downstream.sh
  scripts/ci/verify_release_tag.sh
  scripts/travis/source_clear.sh
Labels: PR: reviewed-approved

#1757 Feature/acs 4653 migrate to gha 711
  .ci.settings.xml
  .github/workflows/ci.yml
  .github/workflows/master_release.yml
  .travis.yml
  README.md
  amps/ags/ci/scripts/getLogs.sh
  scripts/ci/build.sh
  scripts/ci/build_functions.sh
  scripts/ci/cleanup_cache.sh
  scripts/ci/docker-compose/docker-compose-db.yaml
  scripts/ci/docker-compose/docker-compose.yaml
  scripts/ci/init.sh
  scripts/ci/maven_release.sh
  scripts/ci/prepare.sh
  scripts/ci/tests/AppContext05TestSuite-setup.sh
  scripts/ci/update_downstream.sh
  scripts/ci/verify_release_tag.sh
Labels: PR: partially-approved
